### ISSUE TITLE
Regular expression containing quotation marks breaks highlighting

### ISSUE THREAD

**Issue by treyp** [babel/babel-sublime#105]
When a regex contains two quotation marks, parsing gets a bit messed up:
![screen shot 2015-04-21 at 7 31 35 pm](https://cloud.githubusercontent.com/assets/49319/7265300/17179b78-e85d-11e4-8115-a0f815087c4d.png)

Example code:
```javascript
var websocketUrlRegex = /"(wss:\/\/[^"]+)/g;
var matches = websocketUrlRegex.exec(body);
if (matches && matches[1]) {
    console.log('WebSocket URL found: ', matches[1]);
    setupWebSocket(matches[1]);
} else {
    console.log('No WebSocket URL found in Reddit response. ' +
        'Trying again in five seconds.');
    setTimeout(findWebSocket, 5e3);
}
```

Notice all the white keywords after the regex.

Regular Javascript highlighting looks like this:
![screen shot 2015-04-21 at 7 33 58 pm](https://cloud.githubusercontent.com/assets/49319/7265325/6d64a8a4-e85d-11e4-9360-3b37aa0d73e7.png)

**Comment by zertosh** [comment]
Here is what I see:
![wznas](https://cloud.githubusercontent.com/assets/830952/7265525/4aa133e4-e869-11e4-87dd-7853e88d8f7b.png)

I noticed that in your first screenshot "findWebSocket" is white but your theme looks like the stock Monokai, so it should be greenish. Are you sure you're using babel-sublime? Or could there be something further up in the file that's messing it up?

(Also, could you try updating the package?)

**Comment by treyp** [comment]
You know what. I updated before I submitted this but I didn't restart Sublime. After I restarted, everything is working fine. Sorry for wasting your time!

**Comment by zertosh** [comment]
no worries
