### ISSUE TITLE
Quote characters inside JSX

### ISSUE THREAD

**Issue by marcselman** [babel/babel-sublime#110]
Hi,
In a JSX file inside the html syntax it's perfectly valid to add a single or doublequote character for example:

```
return (
	<div>
		Marc's example
	</div>
);
```

But Babel sees the single quote as the start of a string without end and doesn't highlight this syntax correctly.

**Comment by zertosh** [comment]
It works - see https://github.com/babel/babel-sublime/pull/102. Are you sure you have "JavaScript (Babel)" as the selected syntax?

**Comment by marcselman** [comment]
I'm sorry. Apparently my Babel package was not working properly. Reinstalling latest version fixed it. Thanks.
