### ISSUE TITLE
Punctation has a different color than on screenshots

### ISSUE THREAD

**Issue by kevinsimper** [babel/babel-sublime#111]
Here is what it looks like now
![image](https://cloud.githubusercontent.com/assets/1126497/7474857/51d523ec-f344-11e4-9d8c-6cb246535538.png)

But i actually prefer that the punctation does not have a special color, just like the screenshots.

**Comment by zertosh** [comment]
The screenshots are out of date. I haven't gotten around to updating them. https://github.com/babel/babel-sublime/issues/97 explains why the periods appear colored.
