### ISSUE TITLE
Closing a tag with an attribute hangs Sublime Text 2

### ISSUE THREAD

**Issue by alexturek** [babel/babel-sublime#112]
Environment:
* Sublime Text 2
* Only Package Control and Babel v6.0.0 installed (via Package Control)
* JSX files are set to always open with syntax Babel -> Javascript

Repro steps (100% for me):

1. Create a new file `foo.jsx`
2. Open it in sublime text
3. Type the following in the file: `<a b='c'><`
4. Type `/`

Sublime Text (all windows) completely hangs indefinitely and must be `kill`ed.

Can't repro with:
* Pasting in the closing tag characters `</a`
* The close tag typed on a different line
* A tag with no attributes
* A tag with an attribute set to `{}`

**Comment by zertosh** [comment]
Weird, first time I've heard of this. What OS and Sublime build?

**Comment by alexturek** [comment]
Sublime text: Version 2.0.2, Build 2221
OSX Version: 10.10.3 (14D136)

**Comment by alexturek** [comment]
Any way I can get more information for anyone?

**Comment by zertosh** [comment]
Actually, before I install that version... have you tried Sublime Text 3?

**Comment by alexturek** [comment]
I'll give it a shot and report back. I actually thought I remembered some issue w/ ST3 + Babel, maybe that's really old information or something

**Comment by zertosh** [comment]
The only "issue" is with Sublime's initial indexing - it can be kinda heavy on low-end machines. https://github.com/babel/babel-sublime/issues/108

**Comment by alexturek** [comment]
I'm using a brand new Macbook Pro, so I don't think that qualifies as low end :)

I can't repro this on Sublime Text 3

**Comment by zertosh** [comment]
Interesting - I'm going to leave it as is then. I'll keep this issue in mind, in case others popup. Thanks for the report!

**Comment by alexturek** [comment]
Roger

Thanks for maintaining this plugin!

**Comment by zertosh** [comment]
np!

**Comment by cpsubrian** [comment]
Just want to report that I have the exact same issue with Sublime Text 2 and Babel (via Package Control). Also have a Macbook Pro. Same reproduction steps.

Will try ST3 in the meantime. Let me know if other details would be helpful.

**Comment by zertosh** [comment]
@cpsubrian I've gotten other reports and it's confirmed that it happens in ST2. Since ST3 works, I have no intention of trying to find a workaround. However, if anyone can figure out why it happens and submits a fix, I'd be more than happy to merge it :)

**Comment by cpsubrian** [comment]
Yep no worries @zertosh. Just wanted to make sure the info got here. I've pretty much already migrated to ST3 (~20 mins) and just need to charge the $70 to my employer :)

**Comment by zertosh** [comment]
@cpsubrian heheh totally worth it :smile:

**Comment by rpominov** [comment]
Same here. Maybe worth reopening at least?

**Comment by zertosh** [comment]
Sorry @rpominov, but I have no intensions of supporting ST2. I'm also going to be deprecating old ST3 versions soon (see https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt).

**Comment by rpominov** [comment]
Okay, seems like a lot of people migrated to ST3 because of this, which is a good thing I guess :smile: 
I'll follow as well.
