### ISSUE TITLE
Support Flow primitives

### ISSUE THREAD

**Issue by premasagar** [babel/babel-sublime#113]
I read [elsewhere](https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48) that this supports Flow but I didn't read that directly here. In general, Flow annotations work OK, but fails on primitives like `Array<T>` and `Promise<T>`. Lines following a primitive are incorrectly highlighted:

![babel-sublime](https://cloud.githubusercontent.com/assets/116809/7725924/ba122d70-fef6-11e4-8949-c9233c9dd44a.png)

Is this within scope?

**Comment by zertosh** [comment]
Working on it. It'll be a Sublime 3 thing only since I'm building it using Sublime's new [sublime-syntax](https://www.sublimetext.com/docs/3/syntax.html) format (it's only possible this way).

**Comment by premasagar** [comment]
Great. Thanks
