### ISSUE TITLE
Sublime crashes when attempting to close tag using JSX dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by chrisleeshanok** [babel/babel-sublime#114]
I've come across an issue while writing JSX.
In render() I have to set the innerHTML of a node to embed the navbar returned by one of our services. Here's what I'm trying to write:

```javascript	
render: function () {
    return (
	    <div>
	        <div id="navbar" dangerouslySetInnerHTML={{__html: this.state.navbarBody}}></div>
	    </div>
    );
}
```

When I attempt to close the navbar tag, I get as far as ```</``` before sublime hangs with the beachball of death and I have to force quit.

This only happens when I use dangerouslySetInnerHTML and using the babel javascript syntax. Vanilla Javascript syntax does not have the same effect.

I am using Sublime 2.

**Comment by zertosh** [comment]
hey @chrisleeshanok, this seems to be a bug in Sublime Text 2 - it doesn't happen in Sublime Text 3 (see https://github.com/babel/babel-sublime/issues/112). I've been avoiding looking into it since ST3 works - but if there's a compelling case to be made for ST2, then I'll check it out.

**Comment by zertosh** [comment]
Can you confirm your OS and ST build number?

**Comment by chrisleeshanok** [comment]
No problem. I'm on OS X 10.10.3 (14D136) with ST Build 2221.

I checked out #112 and it is indeed an issue when adding any kind of attribute. This is extremely strange because this wasn't an issue for me up until this morning when I tried using danagerouslySetInnerHTML. No updates to any software to my knowledge.

Will use Sublime Text 3 for now. Thanks for taking a look.

**Comment by zertosh** [comment]
Np!

**Comment by loganfuller** [comment]
Is Sublime Text 2 support being dropped for this package? I'm also running into this issue, which makes it unusable for writing JSX.

**Comment by zertosh** [comment]
Sorry @loganfuller, no support for ST2 – the package works great under ST3!
