### ISSUE TITLE
Support ES6 Template Strings / Interpolation

### ISSUE THREAD

**Issue by brianfeister** [babel/babel-sublime#117]
I find this to be horribly unreadable (line 33)... 
![image](https://photos-3.dropbox.com/t/2/AAAvD-VcUgnRsQb5geOTqVsnfG0nolUU6mwbSRAPDkSzuw/12/2186431/png/32x32/1/1432749600/0/2/Screenshot%202015-05-27%2012.27.58.png/CL-5hQEgASACIAMgBCAFIAYoASgC/ip892O5_2zrYAtFm7ZOgq_bHUv4ssauTrCemW0HFJIU?size=1280x960&size_mode=2)

any chance of getting syntax highlighting like vim

![image2](https://photos-3.dropbox.com/t/2/AAB1nqXYK1sAIfpqtQSKNvUsQDQ2oLzAGvvy-j4qNrR8CA/12/252592390/png/32x32/1/1432749600/0/2/backtick%20syntax%20highlighting.png/CIaCuXggASACIAMgBCAFIAYoASgC/2Dk1UUxym-1JG5SloNtXptrpgmrgdONClpXXLdg1RU4?size=1280x960&size_mode=2)

or emacs 
![image3](https://photos-6.dropbox.com/t/2/AAC1ELoe4a0AMwxdTws0WetxdhGpwDbCOrgxAQPXJkO7BA/12/2186431/png/32x32/1/1432749600/0/2/Screenshot%202015-05-27%2012.31.09.png/CL-5hQEgASACIAMgBCAFIAYoASgC/1XXD3Jr6jjj17J7ehW4WTDjCNCrIIOmJ0O9KAH93et4?size=1280x960&size_mode=2)

has?

**Comment by zertosh** [comment]
The images aren't loading. Can you repost them?

**Comment by brianfeister** [comment]
Sure thing. I think Dropbox requires me to use their links rather than linking to the source directly.

Current in babel-sublime: https://www.dropbox.com/s/nlbyo9ql8owi31u/Screenshot%202015-05-27%2012.27.58.png?dl=0
Vim: https://www.dropbox.com/s/ws7tbllp62kf4zw/backtick%20syntax%20highlighting.png?dl=0
Emacs: https://www.dropbox.com/s/6dcasvldet7gs0k/Screenshot%202015-05-27%2012.31.09.png?dl=0

**Comment by zertosh** [comment]
So that's a theme thing, not a syntax definition issue. The Monokai that comes with babel-sublime isn't very thorough - it's just a quick theme. If you were to put a slightly more complicated expression in the template string, you'd see more color. I recommend that you check out https://github.com/voronianski/oceanic-next-theme, it pairs really well with babel-sublime and it defines more colors for expressions in template strings.

**Comment by brianfeister** [comment]
Ah, sorry for turning this into a teaching session... Switched my Sublime Theme and doing great now... As amazing as that is, I think realizing I can drag-and-drop images into Github comments might be even bigger :+1:  :D  ![level_up](https://cloud.githubusercontent.com/assets/806536/7896177/9d5248e8-0665-11e5-9c6a-ca599bfe05ce.png)

**Comment by zertosh** [comment]
np worries!

**Comment by ansonkao** [comment]
I'd like to re-open this issue: the Babel-Sublime package also comes with a modified version of Monokai - that one should support string interpolation!

**Comment by zertosh** [comment]
@ansonkao I added that a few weeks ago. Make sure you're using ST3 dev (Build 3095) and the latest babel-sublime:

![jxufv](https://cloud.githubusercontent.com/assets/830952/9892469/e153c0b8-5bc3-11e5-8938-37ab9953d1f0.png)

**Comment by ansonkao** [comment]
ahh! I'm on ST2 and just added babel-sublime yesterday through the package installer. No chance of backwards compatibility?

**Comment by zertosh** [comment]
sorry @ansonkao, none what so ever. In fact, as soon as the next beta build of ST3 comes out, I'll drop support for everything before that (see https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt)
