### ISSUE TITLE
Easy way to inherit stock Javascript syntax autocomplete?

### ISSUE THREAD

**Issue by samzhao** [babel/babel-sublime#120]
Hey guys, thanks for creating this package! With the Oceanic theme my editor looks like cotton candies :candy:

I understand that some of the 3rd party snippets might not work with the babel package, but apparently the autocomplete is broken as well... by that I mean when I have some text/string in the file I'm editing, say

```js
var superLongVariableName = ""
```
I can laster on just type "super" and sublime suggests me to use `superLongVariableName`. However, with the Javascript (Babel) syntax, this behaviour is completely gone :(

Is there any way I can bring it back without having to write a whole bunch of user configs?

**Comment by zertosh** [comment]
Sublime's default autocomplete works just fine. Maybe because you switched syntax definition it has to "relearn" your symbols, but I use it everyday. If your autocomplete is provided by some package, that might require additional steps.

**Comment by samzhao** [comment]
OK, you are right. I tested this on another computer, it appears to be some third party packages that's causing the problem. Thanks!

**Comment by springware1** [comment]
@samzhao 
How did you fix it. Please explain step by step.
Thanks.

**Comment by samzhao** [comment]
@springware1 sorry, I can't tell you exactly how I fixed it. If I remember correctly, the problem was caused by another package that I couldn't identify. Trying it on the Sublime installed on another computer worked because it had much fewer packages installed.

**Comment by springware1** [comment]
OK. Thanks.
