### ISSUE TITLE
Add a way to tell that top-level JSX elements are JSX for syntax highlighting

### ISSUE THREAD

**Issue by jtward** [babel/babel-sublime#121]
Child elements in JSX match `meta.jsx.children.js`, but there doesn't seem to be a way to tell that the top-level element is JSX when doing syntax highlighting. Adding `meta.jsx...` to the top-level element would make it easy to highlight parent and child elements the same.

**Comment by zertosh** [comment]
Yeah that would be ideal, but unfortunately it's not possible with Sublime's current syntax format. However, Sublime recently added a format ([sublime-syntax](https://www.sublimetext.com/docs/3/syntax.html)), that would make this possible - I'm working on that version.
