### ISSUE TITLE
JSX Syntax highlighting causing Sublime Text 2 to stop responding

### ISSUE THREAD

**Issue by FullR** [babel/babel-sublime#125]
When I attempt to type or paste this text: `return (<div {...this.props} style={this.getStyle()}></);` into Sublime Text 2 with the Babel syntax highlighting, Sublime stops responding and must be force closed.

**Comment by zertosh** [comment]
That's an issue with Sublime Text 2. It works fine in Sublime Text 3. See https://github.com/babel/babel-sublime/issues/114
