### ISSUE TITLE
Why object keys are highlighted as strings? 

### ISSUE THREAD

**Issue by mbektimirov** [babel/babel-sublime#127]
I think it is much better to highlight object keys as non strings, with black color in this theme. Otherwise it is all green everywhere.

With JSX syntax:
![2015-06-09 16 01 49](https://cloud.githubusercontent.com/assets/918009/8056377/ee94d19a-0ec0-11e5-9bf8-2b175357c10b.png) 

With Babel syntax:
![2015-06-09 15 54 14](https://cloud.githubusercontent.com/assets/918009/8056320/72c260a0-0ec0-11e5-8268-5e77d4e294fd.png)

**Comment by mbektimirov** [comment]
Also destructive assignment name alias highlights as string too:
![2015-06-09 18 59 00](https://cloud.githubusercontent.com/assets/918009/8059513/d6e8bc96-0ed9-11e5-90b6-c2848f89269b.png)

**Comment by zertosh** [comment]
Unquoted keys are captured as [`string.unquoted.label.js`](https://github.com/babel/babel-sublime/blob/540199b/JavaScript%20(Babel).YAML-tmLanguage#L915). And quoted keys are captured as [`string.quoted.single.js`](https://github.com/babel/babel-sublime/blob/540199b/JavaScript%20(Babel).YAML-tmLanguage#L389) and [`string.quoted.double.js`](https://github.com/babel/babel-sublime/blob/540199b/JavaScript%20(Babel).YAML-tmLanguage#L393). What should they be captured as?

If it's the color that bothers you, then you should tweak the colors for those scopes.
