### ISSUE TITLE
Update README.md – nvm with babel-transform

### ISSUE THREAD

**Issue by jevzee** [babel/babel-sublime#129]
Add a special paragraph for nvm users (or any other node version managers) to update the default path to lookup babel in `babel.sublime-settings`.

from this:

```
{
  "node_modules": {
    "linux": "/usr/lib/node_modules",
    "osx": "/usr/local/lib/node_modules"
  }
}
```

to something like this:

```
{
  "node_modules": {
    "linux": "~/.nvm/iojs-v2.2.1/lib/node_modules",
    "osx": "~/.nvm/iojs-v2.2.1/lib/node_modules"
  }
}
```

Or better yet, check if babel is available globally in `babel-transform.js`.

**Comment by jevzee** [comment]
I could submit an update for a `findBabel` function in `babel-transform.js` if you think it's worth adding this feature. Otherwise, I could update README instead.

**Comment by zertosh** [comment]
Ah, so I'm not documenting it yet because it's a "secret" feature. I'm still testing it. If you'd like to write up docs, I'd really appreciate that.

**Comment by zertosh** [comment]
FYI: I'm still trying to figure out how to make the startup faster. Right now, it starts up a new node process every time you run "Babel Transform". I'd like to keep an instance around for a few min to reduce the load times, but my python is pretty bad :(

**Comment by jevzee** [comment]
Docs: what do you think?

**Comment by jevzee** [comment]
I've created a separate issue to discuss `babel-transform` optimizations. IMHO, it's out of this ticket's scope.

**Comment by zertosh** [comment]
Thanks! Moving the discussion to the respective issues.

**Comment by joakim** [comment]
A quick tip… Rather than referencing a specific node/io.js version's `node_modules`, one can set up nvm to create a `current` symlink referencing the active version:

In `~/.bash_profile`, `~/.zshrc` or `~/.profile`:

    export NVM_SYMLINK_CURRENT=true

In `Babel.sublime-settings`:

    {
      "node_modules": {
        "osx": "~/.nvm/current/lib/node_modules"
      }
    }

Documented at the bottom of nvm's [Usage](https://github.com/creationix/nvm#usage) section.

**Comment by cesar2535** [comment]
I get a problem when execute the babel transform command.
And then show me a error for it:
```
Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
```
I just installed the node v0.12.4 with nvm and set the user config, but didn't resolve it.
```json
{
  "node_modules": {
    "osx": "~/.nvm/versions/node/v0.12.4/lib/node_modules"
  }
}
```

**Comment by joakim** [comment]
Apparently `node` isn't in your `$PATH` environment variable. What did `node -v` tell you?

**Comment by cesar2535** [comment]
@joakim Thank for you reply. I open a issue #148 
I follow the suggestion and still it doesn't work
