### ISSUE TITLE
'flow polymorphic type' did not work well

### ISSUE THREAD

**Issue by xinchaobeta** [babel/babel-sublime#132]
#### This code's color  is ok:
![enter image description here](http://7xjrj2.com1.z0.glb.clouddn.com/ok.png)
#### But this code's color has bug (when contain `<...>`):
![enter image description here](http://7xjrj2.com1.z0.glb.clouddn.com/bug.png)

**Comment by zertosh** [comment]
It's a known issue. It's a limitation with Sublime's tmLanguage format. I'm working on re-write using [Sublime Text 3's new `sublime-syntax`](https://www.sublimetext.com/docs/3/syntax.html), hopefully I'll have something soon.

**Comment by davis** [comment]
has this been fixed?

**Comment by zertosh** [comment]
@davis Mostly, but you need to be using the dev channel version of ST3 (not the beta). For the details, check out the release notes for [7.1.0](https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt).

**Comment by davis** [comment]
@zertosh ah. Thanks!
