### ISSUE TITLE
Matching workspace color scheme

### ISSUE THREAD

**Issue by timbur** [babel/babel-sublime#133]
I'm not sure if this is specific to Sublime on Ubuntu, but the workspace is black on white, while the editor itself is of course the preferable white on black.  It would be much easier on the eyes for the workspace to match.  I assumed this was just a limitation of Sublime, but I saw the "material design" theme for Sublime yesterday on HN and the workspace theme matched the text area.

I looked into tackling this myself this morning, but a handful of Google searches didn't return anything useful, or maybe I was searching for the wrong terms.

How can I make the workspace color scheme match the text area?

**Comment by hawkrives** [comment]
Sublime supports two types of themes: color schemes, which only affect the editor, and … themes, I suppose, which only affect the workspace.

See the [color scheme](https://packagecontrol.io/browse/labels/color%20scheme) and [theme](https://packagecontrol.io/browse/labels/theme) tags on the [Package Control website](https://packagecontrol.io) for some examples of both.

**Comment by timbur** [comment]
Ah, I see.  Makes sense.  Any recommendations for a theme that matches `babel-sublime` the closest?

**Comment by timbur** [comment]
Actually, never mind my last comment.  Gonna go with the `SoDaReloaded` theme and the see if I can darken the background a bit.  Thanks for the help!
