### ISSUE TITLE
Flow Array<> Types

### ISSUE THREAD

**Issue by cadebward** [babel/babel-sublime#134]
Hi there! I love the syntax highlighting you guys have made. Its super awesome! Just wondering if there is a way around Flow Array types. When I type Array's, everything after is treated as `HTML`:

![screen shot 2015-06-19 at 9 20 49 pm](https://cloud.githubusercontent.com/assets/3212589/8265843/7cf031f4-16c9-11e5-8f85-8120d75e3bd2.png)

When I close it like it was `HTML`, it returns to normal:
![screen shot 2015-06-19 at 9 21 10 pm](https://cloud.githubusercontent.com/assets/3212589/8265844/7ee357ac-16c9-11e5-9404-dc92b2dc6aa3.png)

The `return` statements are uncolored, and various other things, as you might imagine. Is there any current workaround for this?

**Comment by zertosh** [comment]
It's a known issue - I'm working on it. https://github.com/babel/babel-sublime/issues/132#issuecomment-112383225. With the current sublime regex matching it's impossible to distinguish between JSX and the Flow types you're using.
