### ISSUE TITLE
Toggle comment command broken for CJSX syntax

### ISSUE THREAD

**Issue by binarykitchen** [babel/babel-sublime#137]
Hitting `"ctrl+shift+/"` in React-based, Coffeescript driven template code produces an invalid comment.

This is bad:

```cjsx
  render: ->
    <EmailInput
      # THIS COMMENT WILL BREAK
      {...@props}
    />
```

should be like this

```cjsx
  render: ->
    <EmailInput
      {# THIS IS A GOOD COMMENT }
      {...@props}
    />
```

according to https://github.com/jsdf/coffee-react/issues/13

**Comment by binarykitchen** [comment]
Initially (and wrongly) reported at https://github.com/SublimeTextIssues/Core/issues/904

**Comment by zertosh** [comment]
Wrong repo. We don't support CJSX.

**Comment by binarykitchen** [comment]
Thanks. Hmmm, maybe it is https://github.com/aponxi/sublime-better-coffeescript/issues/218 ...
