### ISSUE TITLE
open files with wrong syntax

### ISSUE THREAD

**Issue by shupeipei** [babel/babel-sublime#139]
![a7a6788a-3154-46a2-83e4-b28afa14447c](https://cloud.githubusercontent.com/assets/12183336/8345559/5c2f63d2-1b23-11e5-9fa8-374e473d6ab0.png)

The first JavaScript(Babel) is correct
When i open a file, I set the syntax with the first JavaScript(Babel), then i close my sublime text, when i open my sublime text again, the syntax was changed to the second JavaScript(Babel), and sublime text alert a exception like following picture

![7903673e-8011-4540-85be-3b7f51249687](https://cloud.githubusercontent.com/assets/12183336/8345566/762279b4-1b23-11e5-8c10-2847cb8873e2.png)

**Comment by zertosh** [comment]
Can you try removing babel-sublime and re-installing babel-sublime? If that doesn't work can you share an entire file that causes this? And your sublime version and list of installed plugins.

**Comment by shupeipei** [comment]
@zertosh 
You can close this issue now.
I upgraded my sublime text to build 3092, and cleaned the 'Sublime Text 3' folder in Application Support, then i re-installed babel-sublime, every thing was normal.
thanks :)

**Comment by zertosh** [comment]
cool!

**Comment by mathieumg** [comment]
> I upgraded my sublime text to build 3092

@zertosh Seeing as we're all on the dev build, do you have any way to validate it works properly on 3083?

**Comment by zertosh** [comment]
@mathieumg no idea how. you do have the ability to define units tests now, but as far as testing particular builds, we're out of luck. One of the reasons I went with a 1-to-1 port first is to be able to pull it out if things break w/o disrupting existing workflows. As the old and new syntax diverge, if there's a showstopper bug, then I'll just call the new syntax "JavaScript (Babel) 2" until things settle down. But this is the first bug I've seen.
