### ISSUE TITLE
Text inside JSX tags is highlighted as Javascript and apostrophes break it

### ISSUE THREAD

**Issue by antialiasis** [babel/babel-sublime#142]
Babel appears to highlight the contents of JSX tags as Javascript, when it seems to me they ought to be highlighted as text (that possibly contains other JSX tags and/or Javascript expressions surrounded by braces). This means, for instance, that Javascript keywords like "for" and "with" are nonsensically highlighted in the middle of a paragraph. More importantly, writing any text with an apostrophe inside a chunk of JSX completely breaks the syntax highlighting, because suddenly the rest of the document until it encounters another stray apostrophe is treated as a string. This is unbearably annoying.

**Comment by zertosh** [comment]
That was fixed a long time ago by https://github.com/babel/babel-sublime/pull/102. Make sure you're using an update version of babel-sublime.

**Comment by antialiasis** [comment]
Huh, my Package Control said I had 7.0.0 and there are no upgrades available, but I uninstalled it and reinstalled it and it seems to be working now. No idea what that was about. Sorry for the bother!

**Comment by zertosh** [comment]
no worries
