### ISSUE TITLE
Sublime syntax -- identifiers (& more?)

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#145]
I saw the update today re: the new sublime syntax. A while ago you sent me down this path and I turned out Ecmascript Sublime. It's pretty different from Babel Sublime because I wanted to scope punctuation semantically, so the "logic" of E-Sublime is probably not useful to you much / at all (the cost of grammatical precision is sensitivity to semantic errors, which I believe B-Sublime would prefer to avoid) -- but I think some of the regex patterns and pattern-snippets might be useful since they don't involve that trade off. For example you might be able to use / adapt its identifier patterns:

```
ID_Continue: '{{ID_Start}}\p{Mn}\p{Mc}\p{Nd}\p{Pc}{{Other_ID_Continue}}'
ID_Start: '\p{L}\p{Nl}{{Other_ID_Start}}'
unicodeEscape: '\\u(?:\h{4}|\{\h+\})'
identifierName: '{{identifierStart}}{{identifierPart}}'
identifierPart: '(?:[\$_‍‍{{ID_Continue}}]|{{unicodeEscape}})*' # ZWN?J after _
identifierStart: '(?:[\$_{{ID_Start}}]|{{unicodeEscape}})'
identifier: >-
  (?x)
    (?! (?:{{reservedWords}})
    [^\$_‍‍{{ID_Continue}}] )
    (?<![{{ID_Continue}}])
    {{identifierName}}
```

(etc...) It looks formidable, but sublime is so fast I haven't noticed a performance difference even on hefty files. The pattern currently used by Babel Sublime-Syntax for identifiers will reject some valid IDs and allow some invalid IDs.

I'd be happy to contribute refinements via pull reqs if you like, once you've got the core settled.

**Comment by zertosh** [comment]
Awesome, yes, PRs welcome :smile:

E-Sublime and babel-sublime have different ideas and different user bases. You're correct in that babel-sublime isn't going for perfect scope punctuation. What I'm aiming for is to provide just enough scope information so significant js tokens are "themed sanely" by standard themes. All while supporting JSX, Flow and other babel supported syntax (ES7).

**Comment by bathos** [comment]
Cool. Yeah, I'm not thinking in terms of adding scopes, just increasing accuracy of what's already present, like correctly disambiguating the ternary colon more often. If I can cook up any non-brittle solutions that don't require a ton of added complexity I'll send them your way.

**Comment by zertosh** [comment]
Thanks, I'd really appreciate it! I can def see people wanting/needing super precise scopes.
