### ISSUE TITLE
What handles how code folding works - is that handled by the theme?

### ISSUE THREAD

**Issue by ryancole** [babel/babel-sublime#146]
I've got two questions relating to code folding ...

1. What determines what code syntax part gets a folding triangle in the gutter? Is this determined by the theme, or is this hard coded into Sublime Text itself?

2. What determines how folding functions? When using code folding in JavaScript, it doesn't bring/fold up the closing curly bracket. This is kind a deal breaker for folding because it's just awkward.

**Comment by zertosh** [comment]
AFAIK it's handled by Sublime based on indentation. There's a script in the Default package called `fold.py` that gets called when you fold/unfold.
