### ISSUE TITLE
No .cjsx syntax highlighting

### ISSUE THREAD

**Issue by rguerrettaz** [babel/babel-sublime#147]
As I remember [sublime-react](https://github.com/reactjs/sublime-react) had support for cjsx syntax highlighting. However, babel-sublime appears to take a crap, which is quite frustrating, especially when `cmd` + `/` doesn't properly comment out the target.

![screen shot 2015-07-17 at 5 28 52 pm](https://cloud.githubusercontent.com/assets/1142155/8759482/678fd5da-2ca9-11e5-8905-fe9ecaa074d9.png)

**Comment by zertosh** [comment]
babel-sublime doesn't support cjsx - nor does it intend to. Other packages now support it though - I think https://github.com/Guidebook/sublime-cjsx is what others are using.

**Comment by rguerrettaz** [comment]
Thank you, greatly, for the resource and rapid response.
