### ISSUE TITLE
Couldn't find Node.js.

### ISSUE THREAD

**Issue by cesar2535** [babel/babel-sublime#148]
I have installed node v0.12.4 with nvm, and set the config for the plugin.
But I get a error when execute the `Babel Transform`:
```
Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
```
by following suggestion I get:
```bash
node -v
v0.12.4

# current $PATH
echo $PATH
/Users/Cesar/.nvm/versions/node/v0.12.4/bin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
```
I don't know what problem it is.

**Comment by zertosh** [comment]
I can't answer this in detail now - I'm not a computer. But can you try the same thing from #129 but with an absolute path to node? Not with a ~

**Comment by zertosh** [comment]
I made some changes in https://github.com/babel/babel-sublime/pull/156 that'll give you a more informative error message. Now you'll know what path is actually used.

**Comment by cesar2535** [comment]
Thanks @zertosh 
I got the reason from it after updated package, and solved it by setting `node` link in `/usr/local/bin` to `~/.nvm/current/bin/node`
