### ISSUE TITLE
Crash when adding className to div

### ISSUE THREAD

**Issue by programmarchy** [babel/babel-sublime#149]
When I type:

```
<div className="any-string-here"><
```

Sublime Text 2 freezes after I type the last `<`.

Workaround is to type: `<div></div>` then edit in the className: `<div className="..."></div>`

Here's some context of the file I'm editing:

```
var Slider = React.createClass({
  render: function () {
    return (
      <div className="flex-col-center">
        <div className="..."></div>
      </div>
    )
  }
})
```

I'm using version 7.2.0.

**Comment by zertosh** [comment]
yup, ST2 isn't supported - sorry. babel-sublime works great in ST3 though.

**Comment by programmarchy** [comment]
Thanks. Have been meaning to upgrade anyway :wink:
