### ISSUE TITLE
the sublime goto_definition bug

### ISSUE THREAD

**Issue by soulcm** [babel/babel-sublime#150]
when press F12 to goto the function's definition, it listed the defined function and call's, but the function's call should not list when press F12. Like I want to find below someMethod where defined, I press F12 on this.someMethod, the defiend place and the call place both show in the list, I think this is a bug?

```
someMethod: function() {},
   
add: function() {
   this.someMethod();
}   
```

**Comment by zertosh** [comment]
Yeah @soulcm, I'm afraid it's because I don't use "goto definition" so I didn't really know how it was supposed to work, but I'm fixing it. It's actually being tracked in https://github.com/babel/babel-sublime/issues/59

**Comment by soulcm** [comment]
OK,Thanks.
