### ISSUE TITLE
wrong highlight in script tag of html

### ISSUE THREAD

**Issue by snadn** [babel/babel-sublime#152]
in \<script\> is right
![image](https://cloud.githubusercontent.com/assets/1269858/9002467/1f2525ea-3797-11e5-9aac-ee6e4f7e392c.png)

in \<script type="text/javascript"> is wrong
![image](https://cloud.githubusercontent.com/assets/1269858/9002479/3701112e-3797-11e5-8e78-d1f81ae9177a.png)

and expect not work in \<script type="text/tmpl"> but now the highlight is
![image](https://cloud.githubusercontent.com/assets/1269858/9002506/a5973fd2-3797-11e5-93a0-b0d7ec514db6.png)

when i disabled babel, all of that is ok.
![image](https://cloud.githubusercontent.com/assets/1269858/9002544/101c4b0e-3798-11e5-89b2-6f88538ff1ae.png)
![image](https://cloud.githubusercontent.com/assets/1269858/9002549/18f39fa2-3798-11e5-9ed6-82510dd74836.png)

**Comment by zertosh** [comment]
That's not babel-sublime causing that. If your syntax is set to "HTML", then it's that syntax that decides what other syntax should match some other embedded content. Seems like a ST3 bug.

**Comment by snadn** [comment]
Is it like this? Why everything is ok when babel-sublime is disabled? May be it is a ST3 bug. Thanks!

**Comment by zertosh** [comment]
@snadn I dug a little and I found out that if you disable the builtin javascript packages (via `ignored_packages` in your `Preferences.sublime-settings`), I get what you're describing. Can you check to see if that's what is going on?

**Comment by snadn** [comment]
@zertosh I did not disable the builtin javascript packages. And whether to disable it, the result is the same.
I test in a new env which just install babel and the highlight of https://gist.github.com/snadn/5d34fa6020d85688f373 is also wrong.

**Comment by zertosh** [comment]
Works for me. I've got ST3 Build 3095 with babel-sublime installed. The file syntax is set to "HTML":

![tlynn](https://cloud.githubusercontent.com/assets/830952/9084350/d096ca84-3b40-11e5-8271-2d0bd79ee230.png)

**Comment by snadn** [comment]
3095? My ST3 is 3083 in windows.
![image](https://cloud.githubusercontent.com/assets/1269858/9086681/681bc5d6-3bb8-11e5-8357-2b35250ad134.png)

**Comment by zertosh** [comment]
[ST3 dev](http://www.sublimetext.com/3dev)

![vluqw](https://cloud.githubusercontent.com/assets/830952/9088058/23432bae-3b5c-11e5-8738-a92ef77087b2.png)

**Comment by snadn** [comment]
sorry i do not have a license for ST3. and do not test in 3095.
if highlight is ok in 3095, I can do is just wait

**Comment by zertosh** [comment]
It's working for me. Sorry.

**Comment by echoyangyang** [comment]
@zertosh thx very much!!☺️

**Comment by hellsinglord22** [comment]
@zertosh its working for you cause you are using tag of type text/javascript, we using tag of type text/babel

**Comment by zheeeng** [comment]
@hellsinglord22 I'm using 'script type="text/babel"', but there is no syntax highlighting, autocompletion. I installed babel plugin, and it works in js file.

**Comment by hellsinglord22** [comment]
@zheeeng i know, it only works in js files 
but it's not working in html files which is a bit frustrating

**Comment by zheeeng** [comment]
@hellsinglord22 I modified packages/HTML/HTML.sublime-syntax, and add regexp to recognize "text/babel". It works.

**Comment by hellsinglord22** [comment]
@zheeeng  can you send me the modified version of your HTML.sublime-syntax file . 
or post it here so everyone can use it :)

**Comment by sebamarullo** [comment]
He never send the file changed. :-(

**Comment by leereichardt** [comment]
You have to appreciate it when people say they fixed it, but don't give you any instructions on how to do it yourself. @zheeeng

**Comment by zheeeng** [comment]
@hellsinglord22 @leereichardt My bad, I missed this notification. Here is the modification:  https://gist.github.com/zheeeng/fc63592bcfc4ea786e668d42bc0732ed#file-html-sublime-syntax-L88. Hope it is helpful for someone.

**Comment by cotyembry** [comment]
@zheeeng - it worked for me - thank you! Ill provide some steps that helped me

for Sublime Text 3 you do:

tools -> developer -> new syntax -> copy and paste https://gist.github.com/zheeeng/fc63592bcfc4ea786e668d42bc0732ed#file-html-sublime-syntax-L88 -> save the file in the user package directory (it was the default folder that came up when I hit save)

next go and switch the syntax to the new HTML syntax definition on the bottom right of the sublime text 3 application

**Comment by hellsinglord22** [comment]
@zheeeng thank you, i started using VScode ever since xD
