### ISSUE TITLE
JSX text is highlighted as Javascript after a tag with an attribute

### ISSUE THREAD

**Issue by antialiasis** [babel/babel-sublime#155]
I'm using 7.2.0. Normally text within JSX tags is correctly treated as text and not given any highlighting. However, it seems that this breaks after a JSX tag with an attribute (at least, as far as I can tell that's the rule).

To reproduce, make a file, set its syntax to Javascript (Babel), then paste the following lines into it:

    <p><a href="blah">Something</a> with a link in it that means it doesn't parse right.</p>

    <p><a href={blah}>Something</a> with a link in it that means it doesn't parse right.</p>

    <p><a className="blah">Something</a> with a link in it that means it doesn't parse right.</p>

    <p><span className="blah">Something</a> with a span in it that means it doesn't parse right.</p>

    <p><a>Something</a> with a link in it that doesn't mean it doesn't parse right.</p>

Expected result: The text is parsed as text in each line, while the JSX tags are highlighted appropriately.

Actual result: Only the final line, where the a tag has no attribute, is highlighted correctly; in the others, after the a/span closing tag, normal Javascript highlighting takes over, picking out "with" and "in" as keywords and regarding everything after the apostrophe in "doesn't" as an unterminated string.
![babel-bug](https://cloud.githubusercontent.com/assets/1326447/9075925/092ea1fe-3b0b-11e5-8eb2-32a9e5b71ae2.png)

**Comment by zertosh** [comment]
There are limits to ST3's regex matcher (see https://github.com/babel/babel-sublime/pull/102). I'm working on fixing this as part of https://github.com/babel/babel-sublime/issues/141
