### ISSUE TITLE
Problem with string and comments inside

### ISSUE THREAD

**Issue by zxqfox** [babel/babel-sublime#157]
When using static and put a comment inside — it breaks everything.

![image](https://cloud.githubusercontent.com/assets/677518/9154746/e1c54726-3ea7-11e5-8c66-7a7aeb0556ce.png)

upd: Same with multiline comments:

```js
class A {
  static str = 'abc/*';
  it's still a comment....
}
```

**Comment by zertosh** [comment]
Works for me. Make sure you have "JavaScript (Babel)" selected as the syntax for that file.

![edgfn](https://cloud.githubusercontent.com/assets/830952/9154931/694425d4-3e74-11e5-8c15-a58816b4faa3.png)

**Comment by zxqfox** [comment]
That's strange. Version 7.3.0, win 7
```
>>> sublime.version()
'3083'
```

![image](https://cloud.githubusercontent.com/assets/677518/9154949/a95d2aae-3eaf-11e5-93e6-50bcbc0b1dc6.png)

What to do with it? ;-)

**Comment by zertosh** [comment]
Ah check out the [v7.1.0 install message](https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt). That's one of the fixes that's only available in the new syntax format. You need build 3084 or higher - which are currently only in [dev channel](http://www.sublimetext.com/3dev).

**Comment by zxqfox** [comment]
Oh, thanks ;-) Switched to dev channel!
