### ISSUE TITLE
Inline JSX?

### ISSUE THREAD

**Issue by Jakobud** [babel/babel-sublime#159]
How do you use this with Inline JSX?

```
<html>
<head>
  <title></title>
</head>
<body>

<script type='text/jsx'>
  // JSX here...
</script>
</body>
</html>
```

It colors all my HTML weird and doesn't really color React stuff very well.

**Comment by Dashed** [comment]
HTML files aren't supported.

**Comment by zertosh** [comment]
Sublime's HTML syntax delegates to the stock JavaScript syntax for these cases, so JSX doesn't render properly. Sorry
