### ISSUE TITLE
Syntax highlighting for functions in enhanced object literals

### ISSUE THREAD

**Issue by santiagoaguiar** [babel/babel-sublime#161]
Writing:
 
```javascript
var foo = {
    bar() {
    }
}
```

Does not highlight bar as a function.

For example: 
![image](https://cloud.githubusercontent.com/assets/963231/9357906/cb51718a-465f-11e5-8788-d3da53fd9c00.png)

First `f2` should also be green.

**Comment by zertosh** [comment]
Works for me. Can you make sure have the latest babel-sublime and latest ST3?

<img width="168" alt="ohqui" src="https://cloud.githubusercontent.com/assets/830952/9362197/183cf638-4654-11e5-8dab-792cf90201e8.png">

**Comment by arhcstolen** [comment]
I had the same problem when babel-sublime was updated, but reinstalling solved it.

**Comment by santiagoaguiar** [comment]
Using 8.0 and ST3 stable 3083 (no available updates). Tried re-installing, but same result. 

Seems to be caused by the color scheme configuration. I was using the default color scheme  (Monokai). 

Once I selected `Monokai Phoenix` from `Color Scheme / Babel / Monokai Phoenix` I started getting highlight. Can it use one of them by default on install? (coworkers have the same issue after installing `babel-sublime` on a fresh ST3 install).

Thanks for the prompt replies :)!

**Comment by zertosh** [comment]
@santiagoaguiar Take a look at my [notes from 7.1.0](https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt). I'm not maintaining the "old" syntax anymore. The "new" one highlights the way you expect with that stock Monokai. Unfortunately, the ST3 beta channel is still at 3083, and it doesn't support the new syntax. If you switch to the [dev channel](http://www.sublimetext.com/3dev) (build 3095), ST3 will automatically use the new syntax.

**Comment by santiagoaguiar** [comment]
Ok, thanks!! Closing the issue.
