### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by syranide** [babel/babel-sublime#164]
![image](https://cloud.githubusercontent.com/assets/1714255/9472100/868d6628-4b53-11e5-829c-45db56f5d50e.png)

```html
<div>
  <div x=""></div> / b
</div>
```

It only seems to happen when `/ b` is put in block where there is a non-self closing tag somewhere before it that also has an attribute.

**Comment by zertosh** [comment]
If you use the latest [ST3 dev build](http://www.sublimetext.com/3dev) (not beta), that issue shouldn't happen. I go into more detail in the release notes for [7.1.0](https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt) as to why. Can you confirm your ST3 build number and babel-sublime version?

<img width="194" alt="dxthl" src="https://cloud.githubusercontent.com/assets/830952/9484627/92e7572a-4b63-11e5-9a46-80a27a718f60.png">

**Comment by syranide** [comment]
Yeah I'm on beta and no biggie anyway :+1:
