### ISSUE TITLE
JSX inside array throws highlighting into disarray

### ISSUE THREAD

**Issue by hawkrives** [babel/babel-sublime#166]
Sublime 3 (Dev), build 3095
Babel (Sublime) v8.0.3

Having a JSX element inside of an array throws off the highlighting of everything until the next closing tag.

```jsx
[<span>{module}</span>]
```

<img width="844" alt="screen shot 2015-08-26 at 11 30 04 am" src="https://cloud.githubusercontent.com/assets/464441/9499616/f6cea9dc-4be5-11e5-9491-78612b04e388.png">

---

As always, thanks so much for working on this!

**Comment by zertosh** [comment]
Ah yeah, that's broken :/ The fix should be to add `\[` like in e7b41c9. I'm not on my personal computer now so I can't really push the fix for like another 8 hrs. Sorry :(

**Comment by hawkrives** [comment]
Would you like a pull request?

**Comment by zertosh** [comment]
Sure, but I still won't be able to publish it to Package Control

**Comment by hawkrives** [comment]
:white_check_mark:

**Comment by zertosh** [comment]
@hawkrives I cherry-picked the commit so you'd get git credit :smile: Thanks! It's published at v8.0.4 It should be picked up by Package Control in ~30min
