### ISSUE TITLE
Couldn't find babel or babel-core

### ISSUE THREAD

**Issue by floriandotorg** [babel/babel-sublime#171]
Hi,

I'm constantly getting "Couldn't find babel or babel-core" when I try to transform a file.
Babel as well as babel-ore are globally installed.

**Comment by sunglee** [comment]
Check you have babel in your /node_modules/ path. If not,

```
npm install -g babel
```
```sudo``` if you need.

**Comment by zertosh** [comment]
I haven't added this to the README yet, but this comment should help you understand what babel is actually used https://github.com/babel/babel-sublime/pull/130#issuecomment-110980249

**Comment by floriandotorg** [comment]
Hi, sorry, forgot to mention, of course I did install babel.

But I guess this happens because I'm using NVM, so my packages lying under ~/.nvm/versions/v0.12.7/lib/node_modules

**Comment by zertosh** [comment]
@floriandotorg when it comes to looking for a global babel install, it looks in the standard places – so not in the nvm directory. You can specify the `node_modules` path in your [`Babel.sublime-settings`](https://github.com/babel/babel-sublime/blob/771aca71887fea5a43385505f5346cfb29c7c97e/Babel.sublime-settings). I should really document all of this :disappointed:

**Comment by danesparza** [comment]
I'm on Windows 7, and I had to:
- first do an `npm install -g babel` (of course) 
- get the path that `%AppData%\npm\node_modules` mapped to. For me, this path ended up being `C:/Users/myusername_here/AppData/Roaming/npm/node_modules`.  Note the use of forward slashes.
- Take this path and place it in the *Babel.sublime-settings* file.  This is pretty easy to spot by going into *Sublime -> Preferences -> Package Settings -> Babel -> Settings - Default*
- Restart sublime (this might have just been my superstition).  
- Open a React flavored .js file and select *Tools -> Babel -> Babel Transform*
- Enjoy your transformed file!

**Comment by zertosh** [comment]
This functionality is going away soon. See #293.
