### ISSUE TITLE
Sublime CPU usage

### ISSUE THREAD

**Issue by lorenmh** [babel/babel-sublime#172]
I might be the only one experiencing this, but when I installed Babel via Sublime's Package Control, the CPU usage for Sublime shot up to 99% on my Mac OS X 10.10 device.  The CPU usage stayed up in the mid to high 90s.

Removing Babel brought the CPU usage of Sublime back down to a normal 3%.

I have removed and installed Babel via Package Control multiple times to confirm that the CPU usage is coming from installing Babel.

Just thought you should know.

**Comment by lorenmh** [comment]
Okay...looks like it was being caused by Sublime Linter in conjunction any JSX syntax, not sure why.  Closing this!

**Comment by edweena** [comment]
i'm having the exact same issue and not using sublime linter. how did you fix it?

**Comment by zertosh** [comment]
@edweena, it may be:
1. Because of #185, but that was fixed in v8.3.1, or
2. ST2 is not supported, or
3. Whenever I publish an update, if you have global indexing turned on, then ST3 re-indexes everything.
