### ISSUE TITLE
JSX block commenting

### ISSUE THREAD

**Issue by jeremejevs** [babel/babel-sublime#173]
When I `Toggle Block Comment` on an element, e.g. a `<Button />`, I get the following:

![](http://i.hizliresim.com/3alrj0.png)

However, that [isn't valid JSX syntax](https://facebook.github.io/react/docs/jsx-in-depth.html#comments). It should be like this:

![](http://i.hizliresim.com/rVNWZa.png)

Is this possible to achieve? That is have block commenting behave differently, depending on the context? If it is, it would also be nice to be able to configure the spacing (I'm using a linting ruleset which requires a single space between the asterisks and the commented content, like on the screenshot above).

**Comment by zertosh** [comment]
Oh interesting. I have no idea how that works, but I'll def look into it. Thanks for pointing it out!

**Comment by hawkrives** [comment]
I know that you can add snippets to the `.sublime-keymap` file, like this chunk from my copy:

```json
// Auto-pair backtick quotes
{ "keys": ["`"], "command": "insert_snippet", "args": {"contents": "`$0`"}, "context":
	[
		{ "key": "selector", "operator": "equal", "operand": "source.js", "match_all": true },
		{ "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
		{ "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
		{ "key": "following_text", "operator": "regex_contains", "operand": "^(?:\t| |\\)|]|\\}|>|$)", "match_all": true },
		{ "key": "preceding_text", "operator": "not_regex_contains", "operand": "[`a-zA-Z0-9_]$", "match_all": true },
		{ "key": "eol_selector", "operator": "not_equal", "operand": "string.interpolated.js - punctuation.definition.string.end", "match_all": true }
	]
},
{ "keys": ["`"], "command": "insert_snippet", "args": {"contents": "`${0:$SELECTION}`"}, "context":
	[
		{ "key": "selector", "operator": "equal", "operand": "source.js", "match_all": true },
		{ "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
		{ "key": "selection_empty", "operator": "equal", "operand": false, "match_all": true }
	]
},
{ "keys": ["`"], "command": "move", "args": {"by": "characters", "forward": true}, "context":
	[
		{ "key": "selector", "operator": "equal", "operand": "source.js", "match_all": true },
		{ "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
		{ "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
		{ "key": "following_text", "operator": "regex_contains", "operand": "^`", "match_all": true },
		{ "key": "selector", "operator": "not_equal", "operand": "punctuation.definition.string.begin", "match_all": true },
		{ "key": "eol_selector", "operator": "not_equal", "operand": "string.interpolated.js - punctuation.definition.string.end", "match_all": true },
	]
},
{ "keys": ["backspace"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Delete Left Right.sublime-macro"}, "context":
	[
		{ "key": "selector", "operator": "equal", "operand": "source.js", "match_all": true },
		{ "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
		{ "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
		{ "key": "preceding_text", "operator": "regex_contains", "operand": "`$", "match_all": true },
		{ "key": "following_text", "operator": "regex_contains", "operand": "^`", "match_all": true },
		{ "key": "selector", "operator": "not_equal", "operand": "punctuation.definition.string.begin", "match_all": true },
		{ "key": "eol_selector", "operator": "not_equal", "operand": "string.interpolated.js - punctuation.definition.string.end", "match_all": true },
	]
},
```

This is a direct copy of the default keymap for auto-pairing single and double quotes, adapted for auto-pairing backticks in JS code.

I'll bet you could do something similar for comments inside of a JSX block.

**Comment by zertosh** [comment]
I'll look into that too. I think that the replacement regex is something you can add to something like https://github.com/babel/babel-sublime/blob/master/Comments.tmPreferences

**Comment by hawkrives** [comment]
Is there a scope that's active only inside of a JSX block?

**Comment by zertosh** [comment]
There used to be, until I removed it in https://github.com/babel/babel-sublime/pull/160. I might have to add it again.

**Comment by hawkrives** [comment]
Yeah. So, if there was a `source.jsx` scope, then you could just add another block to `Comments.tmPreferences`. That might be a nice way.

**Comment by zertosh** [comment]
So this is published in v8.4.0 buttttttt it only works if you disable the stock JavaScript package. ST3 is giving priority to its own package (though I think it's more an alphabetical thing, like if this this called zBabel-Sublime it would load after JavaScript and its settings would control).

**Comment by DylanPiercey** [comment]
@zertosh how do you go about disabling the stock js package?

**Comment by zertosh** [comment]
@DylanPiercey https://github.com/babel/babel-sublime#advanced-usage

**Comment by DylanPiercey** [comment]
@zertosh thanks! Missed that bit.

**Comment by oliverbenns** [comment]
I've created and been using a snippet for this: https://gist.github.com/oliverbenns/5cc9d43966bf268febceaa9a42c5ef42

**Comment by borela** [comment]
It turns out, implementing such a plugin that behaves intuitively when the code is mixed with JSX is not an easy task but I finnally managed to add it to https://github.com/borela/naomi on >= 3.8.0. Relevant issue borela/naomi#23.
