### ISSUE TITLE
ST3 - Completion stops working when switching syntax

### ISSUE THREAD

**Issue by kyleboyle** [babel/babel-sublime#174]
Text completion stops working for me when I switch from default javascript syntax to the Javascript(Babel) syntax in sublime text 3. By stops working I mean that the completion options that I would expect to be available based on the symbols defined in the file aren't there. Any ideas on how to troubleshoot this?

**Comment by zertosh** [comment]
Autocomplete symbols are cached per syntax. So by switching, you're starting "fresh". As you use a file, Sublime will build up the autocompletes for it

**Comment by kyleboyle** [comment]
I see, but shouldn't the symbols that are in the file be available for completion immediately? Right now I'm not getting anything.

**Comment by zertosh** [comment]
This is auto-complete:

<img width="324" alt="mybvt" src="https://cloud.githubusercontent.com/assets/830952/9692730/093415b4-5300-11e5-9cce-f3503230de86.png">

It's sometimes flaky when you first switch syntaxes. You might want to blow away [Sublime's File Index](http://www.sublimetext.com/blog/articles/file-indexing).

This is "Goto Symbol":

<img width="600" alt="qchbh" src="https://cloud.githubusercontent.com/assets/830952/9692829/b8012eba-5300-11e5-90a9-2cc665629122.png">

It works pretty well, but there are issues with "Goto Definition" and "Goto Symbol In Project" (https://github.com/babel/babel-sublime/issues/59). I haven't had time to sort those out.

My best suggestion to you is to try rebuilding the file index.

**Comment by kyleboyle** [comment]
cool, thank you. I blew away my Cache and Index dirs and that made it work.
