### ISSUE TITLE
calculated/symbolic methods are not properly tagged

### ISSUE THREAD

**Issue by benmosher** [babel/babel-sublime#175]
Forgive me if the title is confusing, I'm not familiar with Sublime/TextMate syntax jargon.

Using symbols (or more generally, calculated fields) in class definitions doesn't highlight the same as explicit members:

![screen shot 2015-09-08 at 5 14 28 pm](https://cloud.githubusercontent.com/assets/3709196/9747679/24eb9e08-564d-11e5-885c-245bef26a935.png)

I would expect purple `get/static` and blue parentheses in all cases.

😄

**Comment by zertosh** [comment]
This is a known issue - it's part of other issues related to flow, you can track the progress in https://github.com/babel/babel-sublime/issues/141
