### ISSUE TITLE
Having specific settings just for the JSX

### ISSUE THREAD

**Issue by Calvein** [babel/babel-sublime#176]
I don't know if it's possible but it would be great to be able to have a JSX.sublime-settings (or even HTML.sublime-settings) just for the jsx blocks, e.g:
```json
{
    "trim_trailing_white_space_on_save": false,
    "draw_white_space": "all"
}
```
 Would render something like this:
![image](https://cloud.githubusercontent.com/assets/243189/9777343/92e53824-57a6-11e5-8fec-e097e6c8700a.png)

And so no need for ugly `{' '}`.

**Comment by zertosh** [comment]
Not possible with Sublime (that I know of) – sorry.
