### ISSUE TITLE
Regex highlighting bugs

### ISSUE THREAD

**Issue by Boycce** [babel/babel-sublime#177]
![regex](https://cloud.githubusercontent.com/assets/2629988/9777393/07cd161e-57b8-11e5-8518-4b7f16831cb6.jpg)

`\s` - Displays in a different color.
`[]` - Brackets and characters inside (except for `\t\n\r`) break regex highlighting

**Comment by zertosh** [comment]
It's working as expected. The `\s` is matched as a [`constant.other.character-class.escape.backslash.regexp`](https://github.com/babel/babel-sublime/blob/771aca71887fea5a43385505f5346cfb29c7c97e/Regular%20Expressions%20(Babel).sublime-syntax#L23-L24) and the `[`/`]` are matched as [`constant.other.character-class.set.regexp`](https://github.com/babel/babel-sublime/blob/771aca71887fea5a43385505f5346cfb29c7c97e/Regular%20Expressions%20(Babel).sublime-syntax#L28-L36) – and my guess is that your theme is coloring those as constants (like `null`).

**Comment by Boycce** [comment]
Perfect, thanks for the help.
