### ISSUE TITLE
modifying template to allow for custom template strings

### ISSUE THREAD

**Issue by wprater** [babel/babel-sublime#181]
I've been trying to modify the `JavaScript (Babel)` syntax to allow for a special `literal-quasi`.  however, it seems the template strings are being recognized as `string.interpolated.js` vs `string.quasi.js`.  from within the `class` scope, I wanted to capture `static template = ```` ` as HTML.  

thoughts?

**Comment by zertosh** [comment]
template strings are captured as `string.interpolated.js` inside and outside of classes. I plan on remaining back to `string.quasi.js`. However, how does this affect what you're trying to do?

**Comment by wprater** [comment]
whoops, I was editing the older `JavaScript (Babel).YAML-tmLanguage` and converting it to `JavaScript (Babel).tmLanguage` with AAAPackageDev

**Comment by wprater** [comment]
however, when I try to edit your file for testing and match a new start for a interpolated wtring with this pattern, it does not match.  is that because it's matched by other contexts?

`match: '\bstatic\s*\btemplate\s*=\s*```'`

**Comment by wprater** [comment]
actually, my above fix does not work. when I push the Babel syntax will overwrite my match above.  thoughts on how to achieve this?

**Comment by zertosh** [comment]
```diff
diff --git a/JavaScript (Babel).sublime-syntax b/JavaScript (Babel).sublime-syntax
index 29a0ac97..4df2c90e 100644
--- a/JavaScript (Babel).sublime-syntax
+++ b/JavaScript (Babel).sublime-syntax
@@ -1164,6 +1164,19 @@ contexts:

   # stage 0 proposal: https://gist.github.com/jeffmo/054df782c05639da2adb
   es7-class-properties:
+    - match: \b(static)\s*\b(template)\s*(=)\s*
+      captures:
+        1: storage.type.static.js
+        2: variable.other.property.js
+        3: storage.type.js
+      push:
+        - match: '`'
+          push: 'Packages/HTML/HTML.sublime-syntax'
+          with_prototype:
+            - match: '`'
+              pop: true
+        - match: ''
+          pop: true
     - match: \b(static)?\s*\b({{ident}})\s*(=)\s*
       captures:
         1: storage.type.static.js
```

**Comment by wprater** [comment]
nice, very helpful!!
