### ISSUE TITLE
Crashes on certain minified files

### ISSUE THREAD

**Issue by dogoku** [babel/babel-sublime#185]
I'm not sure exactly what's going on, but it seems like when I try opening certain minified JS files while using the JavaScript (Babel) syntax, sublime just becomes unresponsive, locks to 99% cpu and only way to kill it is force quit (in Mac)

I discovered this because Sublime was getting stuck for a long time while indexing. After checking the console log, I noticed sublime force quitting it's workers for specific minified files. I've since excluded those files from indexing, but you can still get a crush if you open a minified file by mistake.

I've uploaded one of the minified files for reference: https://gist.github.com/dogoku/a00b473eb8c5cadfd2c7

**Comment by johanobergman** [comment]
I can confirm the issue. The sublime console shows the following error:
`worker 958 appears stuck while processing file /Users/....../jquery/jquery.min.js, killing process`

**Comment by zertosh** [comment]
I found the change that was causing this and reverted it. That's definitely a Sublime bug but I guess I'll work around it. Really weird. I published it as v8.3.1, it should get picked up by Package Control soon. Sorry!

**Comment by johanobergman** [comment]
Thanks, that was quick!

**Comment by zertosh** [comment]
@johanobergman Np, do you happen to know how long it was taking the worker to die? And how unresponsive was Sublime during the indexing? Or was it not felt on the app, and it was just the background processes? I'm asking because I keep indexing off, so I wouldn't have noticed this.

**Comment by johanobergman** [comment]
Well, I noticed it because my Macbook Air's fan started spinning like crazy. I'm not sure, perhaps around 20-30 seconds (I have already updated :worried:). Sublime didn't crash for me, and felt kind of normal. The indexing progress was stuck at 99% though, that's when I opened the console and googled the error.

**Comment by dogoku** [comment]
Yep, about 30sec for it to stop the worker. For indexing, Sublime would just slow down considerably, but was still usable. If you try to open a minified directly, sublime will lock permanently and you have to force quit.

**Comment by zertosh** [comment]
Thank you both again! It's good to know that I should test minified files.

**Comment by zertosh** [comment]
For posterity, this was broken by #184.
