### ISSUE TITLE
false is not highlighted correctly

### ISSUE THREAD

**Issue by 807811b0-1373-11e5-b60b-1697f925ec7b** [babel/babel-sublime#188]
![bad-highlighting](https://cloud.githubusercontent.com/assets/12897710/10343576/5464f534-6cec-11e5-9753-8a77d79bf906.png)

I have noticed that false is not being highlighted anymore. Using the latest 8.4.0 and [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme).

**Comment by voronianski** [comment]
@807811b0-1373-11e5-b60b-1697f925ec7b @zertosh +1 

Scope doesn't contain any `boolean` tag.

**Comment by zertosh** [comment]
Sorry about that - The fix is in v8.4.1.
