### ISSUE TITLE
New function scopes?

### ISSUE THREAD

**Issue by voronianski** [babel/babel-sublime#189]
Most of the functions are no longer highlighted properly in Oceanic Next:

<img src="https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-07%20%D0%B2%2020.05.55.png" width="500" />

As you see from screenshot `createReferenceQuestions`, `find` and `toString` are not highlighted with blue color though they were in prev version of babel-sublime.

Here is the list of current scopes in color scheme - `entity.name.function, meta.function-call, support.function, keyword.other.special-method, meta.block-level`.

Is it a bug or there are new scopes to follow? Thanks!

/cc @zertosh

**Comment by zertosh** [comment]
Yes, function calls in the _old_ syntax were incorrectly captured as `entity.name.function.js`, I renamed them to `variable.function.js`. See 5f52601cace48967afe5e26fc89274ec7b38665f and a8f7c8bb9a5e6925241126a96af17d0d5f1a2c25. And 567d81ef5ee216b230d3063aea7ba52b92044e86 may also be relevant.

I personally like function calls highlighted too so in my theme I have [this](https://github.com/zertosh/dracula-theme/blob/5ee54a7819807692413bea699906143cc1fefca7/Dracula.YAML-tmTheme#L203-L206).

**Comment by voronianski** [comment]
@zertosh thx for quick response, will update Oceanic Next then
