### ISSUE TITLE
Sublime hangs when typing "=> <"

### ISSUE THREAD

**Issue by Adam13531** [babel/babel-sublime#190]
Repro is simple:
1. Make new buffer
2. Set syntax highlighting to Babel.
3. Type "=> <" without the quotes.

This causes Sublime to hang indefinitely.

**Comment by zertosh** [comment]
Can't repro. Are you using ST3?

**Comment by Adam13531** [comment]
No, I'm on ST2. If you'd like, email me and I can Skype you a repro.

**Comment by zertosh** [comment]
ST2 hangs for some reason - check the issues. I'm not support it. Sorry.

**Comment by Adam13531** [comment]
Got it, thanks for the quick response. I found the issue you're referring to [here](https://github.com/babel/babel-sublime/issues/112).

Just one more detail before I close this bug: I was originally trying to get this code to work:
    {() => <someTag
        onClickHandler={blah}
        onOtherHandler={blah}/>}

Putting `<someTag` on a new line lets me work around this.
