### ISSUE TITLE
Last update breaks my code

### ISSUE THREAD

**Issue by bcalik** [babel/babel-sublime#191]
Hello,

Today my laravel blade syntax highlighter is broken. I wasted my half an hour to find which package cause this. And the result is Babel.

Screenshots are attached for both enabled/disabled babel package.

<img width="1680" alt="screen shot 2015-10-09 at 13 55 32" src="https://cloud.githubusercontent.com/assets/9222368/10392241/f360b126-6e8d-11e5-9491-db7af363c730.png">
<img width="1680" alt="screen shot 2015-10-09 at 13 54 59" src="https://cloud.githubusercontent.com/assets/9222368/10392242/f362e96e-6e8d-11e5-9d31-9d0dbf0541cb.png">

**Comment by zertosh** [comment]
Please provide me with repro instructions - I don't write PHP and I don't know what Laravel Blade is.

**Comment by bcalik** [comment]
I realized that the problem is about script closing tag </script>.
It does not work if there is a space before.

![out](https://cloud.githubusercontent.com/assets/9222368/10404916/52b4cc8e-6ede-11e5-9a9b-947656f4142f.gif)

--

To produce you can install [Laravel Blade](https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter) package, It just adds a syntax definition.

Then paste the following code, and choose "PHP - Laravel Blade" as syntax.
Notice the space before </script> tag.

```html
<script>
 </script>
<!-- FROM HERE, IT MUST BE HTML -->
```

**Comment by zertosh** [comment]
Works for me. My guess is that you're using ST3 beta and not dev - I took a look at Laravel Blade and just like babel-sublime, they're optimized for newer builds of ST3 (see https://github.com/Medalink/laravel-blade/issues/76). Try ST3 Build 3095 from the [dev channel](http://www.sublimetext.com/3dev).

![jfplu](https://cloud.githubusercontent.com/assets/830952/10409002/a66e75ca-6ec3-11e5-922b-e8690c09d38b.png)

**Comment by ccqgithub** [comment]
I met the same problem.  If i disable the babel package，all is ok !

**Comment by zertosh** [comment]
Have you tried ST3 build 3095?

**Comment by ccqgithub** [comment]
@zertosh build 3083

**Comment by zertosh** [comment]
To run the current version of Laravel Blade simultaneously with the current version of babel-sublime, you need 3095.

**Comment by bcalik** [comment]
Since sublime text's dev build is closed for free public use, this issue should stay open.

**Comment by zertosh** [comment]
@bcalik, you should file an issue with Laravel Blade - your problem is with the _old_ version of it that you're running.
