### ISSUE TITLE
JSX highlighting issue when closing tag on separate line

### ISSUE THREAD

**Issue by dburrows** [babel/babel-sublime#194]
ST3, babel-sublime 8.5

There's an issue with highlighting when closing a JSX tag on a separate line - sets the rest of the code to quoted string highlighting until the next closing tag, see attached image

![jsx-highlight-bug](https://cloud.githubusercontent.com/assets/44306/10480359/bcc726f4-7261-11e5-8439-4031775ff665.png)

Bug Replication Code 
```
// closing tag on same line as last prop def
<Component  onChange={ doFoo }
            className='bar' />
<Component  onChange={ doFoo }
            className='bar' />
<Component  onChange={ doFoo }
            className='bar' />

// closing tag on next line after last prop def
<Component  onChange={ doFoo }
            className='bar' 
            />
<Component  onChange={ doFoo }
            className='bar' />
<Component  onChange={ doFoo }
            className='bar' />

```

**Comment by zertosh** [comment]
It works for me. What build number of sublime are you using?

![cejem](https://cloud.githubusercontent.com/assets/830952/10487560/5ee2a5da-7249-11e5-8dcf-17badc8b8212.png)

**Comment by zertosh** [comment]
I just tried both build 3083 and 3095, and it works. Maybe you don't have "JavaScript (Babel)" selected?

**Comment by dburrows** [comment]
Damn, sorry about that, you are right - seem to have lost some config in an upgrade. Sorry to add noise, thanks for all the hard work on this ;)

**Comment by zertosh** [comment]
np! Thanks! :smile:
