### ISSUE TITLE
hang on arrow function with implicit return of jsx component

### ISSUE THREAD

**Issue by mattybow** [babel/babel-sublime#195]
I'm using Sublime Text 2 and I cannot open or modify files with the following syntax:
```
() => <ReactComponent />
```
Sublime hangs and the CPU spikes on my computer.  There no problem if you put parens around the component like:
```
() => (<ReactComponent />)
```
I'm on 8.3.1, using OSX El Cap. Just went to the [Package Control Page](https://packagecontrol.io/packages/Babel), and saw the ST3 tag, is ST2 just not supported anymore?

**Comment by zertosh** [comment]
Correct, ST2 isn't supported anymore – because of that issue. Sorry

**Comment by NeXTs** [comment]
Thanks for opening this issue, I'm just faced same problem and zertoh's answer was very timely for me. :+1:
