### ISSUE TITLE
Close Tag stopped working

### ISSUE THREAD

**Issue by difelice** [babel/babel-sublime#196]
On latest build the action *close_tag* stopped working.

Placing the cursor right after `{'hello'}` and then hitting **Edit > Tag > Close Tag** (`super+alt+.`) does nothing:
```
render: function() {
        return (
            <div>{'Hello'}
        );
}
```

Before and expected:
```
render: function() {
        return (
            <div>{'Hello'}</div>
        );
}
```

Thank you

**Comment by jasperkuperus** [comment]
Yeah, same here. Confirmed in both Sublime 2 and 3.

**Comment by zertosh** [comment]
Sorry, yeah I have the fix already, I'm just lumping a few more changes together

**Comment by difelice** [comment]
@zertosh no worries, thank you so much.

**Comment by jasperkuperus** [comment]
Works like a charm now, thanks!

**Comment by difelice** [comment]
Same here. Thank you!
