### ISSUE TITLE
Syntax coloring on functions went missing

### ISSUE THREAD

**Issue by dvlsg** [babel/babel-sublime#197]
Hey guys, I believe I received an auto update which caused my javascript functions/methods to stop being highlighted. To show what I mean, I typed out part of the example you have on your front page and took a screenshot:

![sublime-missing_method_syntax](https://github-cloud.s3.amazonaws.com/assets/4721566/10565561/5934d5bc-7588-11e5-893d-268fd0910d10.png)

I would expect `React`, `createClass`, `post`, `send`, and `end` to all be colored in green. The backticks also changed, but I'm guessing that change is intentional? Turns out I miss the colors of executed functions more than I would have guessed, though -- it's quite helpful!

Any idea what's going on? I have the same issue on multiple machines with multiple versions of sublime text.

Sublime Text: v3, build 3095 (dev)
Babel-sublime: v8.5.0

**Comment by zertosh** [comment]
#189 should shed some light on what's going on. Short answer is, you need a new theme, because Monokai doesn't color function calls – it did so before because of a bug.

**Comment by dvlsg** [comment]
Interesting -- thanks for the link, I will probably make that modification to my local copy of Monokai, then. Thanks!

**Comment by dvlsg** [comment]
Just as a follow up, confirmed that making a copy of Monokai.tmTheme and adding these lines to the xml brings the function call coloring back to the old way (mostly -- `React` in `React.createClass` is not colored, which is technically how the old way worked, but this seems better to me):

```
<dict>
    <key>name</key>
    <string>Function call</string>
    <key>scope</key>
    <string>meta.function-call variable.function</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#A6E22E</string>
    </dict>
</dict>
```

![image](https://cloud.githubusercontent.com/assets/4721566/10583779/ce6664a2-7643-11e5-832b-eae6c4adf93e.png)

**Comment by zertosh** [comment]
@dvlsg, here are the [rules](https://github.com/babel/babel-sublime/blob/2203c2c54b0694f823fa9087f1519315df40df5d/JavaScript%20(Babel).YAML-tmLanguage#L696-L758) that match function calls. If you want `React` to be colored, then try `meta.function-call variable.other.class` – it's an `variable.other.class` because it starts with a capital letter (`R`). This may not be what you want exactly, but just look through the different scopes.

**Comment by dvlsg** [comment]
Got it. Personally, I like it without `React` without the color, but when/if I run across something else that feels off to me, I'll definitely reference those rules. Thanks for the link!

**Comment by zertosh** [comment]
I can sympathize with that. This is what I my personal theme looks like:

![aadpx](https://cloud.githubusercontent.com/assets/830952/10585710/882d5234-764d-11e5-9faf-a195553db1ae.png)
