### ISSUE TITLE
close tag support?

### ISSUE THREAD

**Issue by nsfmc** [babel/babel-sublime#202]
Hello, please feel free to autoclose this issue if i am crazy or have misconfigured sublime somehow, but i thought that babel-sublime supported the close tag feature when editing jsx. recently, i set up a new computer and am noticing that babel-sublime doesn't seem to support closing tags in jsx.

i guess two questions: did it *ever*? if it does, has my configuration gotten confused such that it's not behaving for me (using dev channel build 3095)?

thanks and sorry for any annoyance

**Comment by zertosh** [comment]
It does. I broke it v8.5.0 and fixed it in v8.6.0. So just update the package and it should work again :smile:

**Comment by nsfmc** [comment]
thanks so much and thanks for working on this package. i really appreciate it.

**Comment by ashvaibhav** [comment]
With Babel v8.6.3, it seems to work fine for .jsx file but not for .js file.
<img width="491" alt="Screen Shot 2019-05-07 at 8 22 17 AM" src="https://user-images.githubusercontent.com/432355/57311850-47504800-70a1-11e9-8dc4-376bb6de5072.png">

**Comment by ashvaibhav** [comment]
Well, even for jsx files, sometimes it seems to break:
<img width="691" alt="Screen Shot 2019-05-07 at 8 26 54 AM" src="https://user-images.githubusercontent.com/432355/57312213-fab93c80-70a1-11e9-86e7-c6c4f33a60bd.png">

**Comment by a8568730** [comment]
I has the same problem as @ashvaibhav ...
