### ISSUE TITLE
Babel doesn't appear in sublime language selector

### ISSUE THREAD

**Issue by patoroco** [babel/babel-sublime#203]
I was using babel in Sublime Text without problems, but I formated my laptop recently and I needed to reinstall sublime text from the scratch.

The problem is that babel doesn't appear in the language list, and a coworker has the same problem (see below image).

![screen shot 2015-10-21 at 09 06 10](https://cloud.githubusercontent.com/assets/701909/10629950/81e968fe-77d3-11e5-8417-84a1135d8c82.png)

Configuration is the same for both of us: OS X El Capitan, with Sublime Text 2 (I installed it via brew cask), and we installed babel-sublime using the Package Installer.

Do we need some other requirements to show babel in language selector?

**Comment by zertosh** [comment]
ST2 isn't supported anymore - sorry

**Comment by Sotorin** [comment]
I'm actually experiencing the same thing. Yesterday, on a different VM, everything worked perfectly but now, when I performed another clean install it does not work. I'm definitely on ST3 (build 3083) and installed, uninstalled, restarted, rebooted and ... nothing. JavaScript (Babel) does not show up.

**Comment by zertosh** [comment]
@Sotorin that's weird - nobody else is reporting that problem

**Comment by Sotorin** [comment]
Everything is working fine now. I could have sworn that JavaScript(Babel) was under JavaScript, not under Babel. Unfortunately I deleted my VM from couple of days ago so I can't even prove myself wrong. I re-read the docs and sure enough it says Babel->JavaScript(Babel), not JavaScript->JavaScript(Babel).

**Comment by jackiekamara** [comment]
Hi!
I'm experiencing the same problem:  Babel isn't an option in the language selector. Using OS X El Capitan, with Sublime Text 3, installed Babel through PackageControl.

<img width="498" alt="screen shot 2015-12-28 at 12 56 28 pm" src="https://cloud.githubusercontent.com/assets/16366430/12022998/0f432996-ad63-11e5-9d9a-ee4059ebe662.png">

**Comment by Spacelapp** [comment]
+1

**Comment by ramkittu** [comment]
Working for me.
Once you install package control to Sublime, click on 
preferences -> package Control -> package Control : enable package -> select babel

once loaded restart Sublime

**Comment by tavancuong** [comment]
I have the same problem. All you need to do is:
- Make sure that you're using SublimeText3,
- Then go to "preferences",
- Click "Package control",
- Click "Install package",
- Finally, type "Bable" and select it.

**Comment by mcmedal001** [comment]
> Working for me.
> Once you install package control to Sublime, click on
> preferences -> package Control -> package Control : enable package -> select babel
> 
> once loaded restart Sublime

For many having this problem, they probably no longer have Babel package after the update. So, wouldn't even find it. In this case, they are to click "install package" and not "enable package. You then need to type in Babel and click to install it.

**Comment by ClaudyV** [comment]
> > Working for me.
> > Once you install package control to Sublime, click on
> > preferences -> package Control -> package Control : enable package -> select babel
> > once loaded restart Sublime
> 
> For many having this problem, they probably no longer have Babel package after the update. So, wouldn't even find it. In this case, they are to click "install package" and not "enable package. You then need to type in Babel and click to install it.

You are totally right! 
I have installed the package by clicking "preferences => package control => Package control : Install Package => select Babel 
and it works.

**Comment by hassyera** [comment]
I found a solution. first install package control if you don't have package control option in preferences menu.Install package control option is available on one of the menu in menu bar.. after installing it it will be available on preferences.Then select it.Then "Package control : Install Package => select Babel"
DONE!

**Comment by fllopis** [comment]
> Everything is working fine now. I could have sworn that JavaScript(Babel) was under JavaScript, not under Babel. Unfortunately I deleted my VM from couple of days ago so I can't even prove myself wrong. I re-read the docs and sure enough it says Babel->JavaScript(Babel), not JavaScript->JavaScript(Babel).

This works for me.... Babel is not on "B" like in past. Now is  "Javascript (Babel)".

Thank you very much, It was driving me crazy xD
