### ISSUE TITLE
css - inside tag and file have different start/end scopes

### ISSUE THREAD

**Issue by voronianski** [babel/babel-sublime#205]
css content inside `.css` file has such scopes for start/end {} brackets - `source.css meta.property-list.css punctuation.section.property-list.css` / `source.css`.

**This leads to not highlighted closing curly**:

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-22%20%D0%B2%2014.16.40.png)

On the other hand css which is inside `<style></style>` tags, start/end {} brackets have such scopes -

And this makes highlighting of them proper:

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-22%20%D0%B2%2014.18.01.png)

**Comment by zertosh** [comment]
Right repo?

**Comment by voronianski** [comment]
@zertosh does babel-sublime inherit css scopes from defaults?

**Comment by voronianski** [comment]
@zertosh or probably I'm just missing smth :mag:

**Comment by zertosh** [comment]
babel-sublime only sources the [Regular Expressions](https://github.com/babel/babel-sublime/blob/788a87148dd51a774470573acc9e013373c09f94/Regular%20Expressions%20(Babel).YAML-tmLanguage) syntax. However, other syntax definitions like [HTML](https://github.com/sublimehq/Packages/blob/f7f96a0c31f6d6362dcb7ebfab6d1a0db7641f60/HTML/HTML.sublime-syntax#L111) or PHP, source a `source.js` syntax, which depending on whether you've disabled the stock JavaScript package or not, will resolve to babel-sublime. Other third party syntax definitions like [Laravel Blade](https://github.com/Medalink/laravel-blade), also source `source.js` and sometimes mess it up by not properly matching the ending `</script>` and you get #191.

**Comment by zertosh** [comment]
This may be what you're seeing https://github.com/sublimehq/Packages/issues/106
