### ISSUE TITLE
Illegal JSX attribute names are not highlighted as invalid

### ISSUE THREAD

**Issue by aziz** [babel/babel-sublime#207]
I'm trying to recreate what you have in screenshots, but I can't. 
Am I missing something or is this a buh?

**Comment by zertosh** [comment]
I took it off because it was breaking other syntax. I might bring it back because I do like it.

**Comment by aziz** [comment]
Just remove the screenshot from the readme then, cause it's causing confusion at the moment.

**Comment by zertosh** [comment]
I'll gladly take new screenshots if you want to submit a PR

**Comment by zertosh** [comment]
Please make sure they're 728px (or 1456px) wide because they need to fit correctly in the github readme preview and the package control readme. Thanks!

**Comment by aziz** [comment]
I'm not asking for new screenshots. I just removed the screenshot regarding the feature that has been removed.

**Comment by zertosh** [comment]
See re-rewrite babel-sublime #293.
