### ISSUE TITLE
Class properties without semi-colon are not highlighted correctly

### ISSUE THREAD

**Issue by aziz** [babel/babel-sublime#208]
Notice the difference between first and second class definition:
<img width="298" alt="screen shot 2015-10-26 at 11 52 15 am" src="https://cloud.githubusercontent.com/assets/3202/10727186/2fb3d7be-7bd8-11e5-93fe-c9485ae56c69.png">

**Comment by zertosh** [comment]
Yup, known issue. The short version is that is hard to differentiate between a function call and a short method using regexs. #183 fixes that – but I'm still porting it over to master – it's a complete rewrite. Feel free to test it out if you'd like and drop some feedback :smile:
