### ISSUE TITLE
Crashes/hangs sublime on arrow functions

### ISSUE THREAD

**Issue by grantila** [babel/babel-sublime#210]
Given a function `loop`, the following (legal syntax) crashes/hangs sublime:
```jsx
loop( _ => <div/> )
```

**Comment by grantila** [comment]
Has to do with single statement function bodies (i.e. without the curly braces), since the following works:
```jsx
loop( _ => { return <div/>; } )
```

**Comment by zertosh** [comment]
Are you using ST2? That's a known issue there, which is why it's not supported

**Comment by grantila** [comment]
ST2 yes, didn't know it wasn't supported. Maybe the required ST version should be specified in the README.md, I'm unlikely the only one using ST2.

**Comment by zertosh** [comment]
It's already limited to ST3 in package control. But you're right, I should add a note to the README.

**Comment by grantila** [comment]
FYI, I can't remember having had a problem installing it in ST2, so if there is supposed to be a limit in PC, I'm not sure it actually works.
And just like you said, the issue is gone when using ST3, thank you very much.
