### ISSUE TITLE
Context aware comments.

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babel-sublime#213]
I'm not sure if this is something that is possible by this plugin, but it's an inconvenience for sure.
Currently when you try to comment within jsx using shortcuts (not within a tag, but the child section) it tries to do a js comment which is invalid.

```js
<div>
    //<div>hello</div>
</div>
```

Which should be:

```js
<div>
    {/* <div>hello</div> */}
</div>
```

It would also be cool if the syntax highlughting also grayed out the interpolation `{}`.
If any one has a solution let me know.

**Comment by zertosh** [comment]
See https://github.com/babel/babel-sublime/issues/173#issuecomment-146100542
