### ISSUE TITLE
Variable name immediately followed by colons are incorrectly coloured

### ISSUE THREAD

**Issue by AndreDalcher** [babel/babel-sublime#214]
If a variable name is used as part of an operation and directly precedes a colon, e.g. in a ternary, it gets coloured incorrectly.

![image](https://cloud.githubusercontent.com/assets/12794858/11180657/6f79e83e-8c54-11e5-9466-aa35c3633601.png)

**Comment by zertosh** [comment]
Sorry for the super late response. That's a known issue because of how distinguishing between object keys and ternary alternates works.
