### ISSUE TITLE
SublimeText 2 crashes in JSX "=>" fat arrow function

### ISSUE THREAD

**Issue by owenhoskins** [babel/babel-sublime#215]
Hello, I am starting to enjoy these new ES6 syntaxes, thanks for this package!

Desired:
`{this.state.files.map((file) => <img src={file.preview} /> )}`

ST2 freezes on typing the first character within the HTML "<" brackets.

I uninstalled and reinstalled babel-sublime via ST2 Package manager, but to no avail.

Any ideas?

best,
Owen

**Comment by hawkrives** [comment]
Apologies, but `babel-sublime` no longer supports ST2.

@zertosh I just noticed that the README doesn't mention this anywhere. Would you mind a PR adding a notice about the (lack of) ST2 support to the top of the README?

**Comment by zertosh** [comment]
@hawkrives Sorry for the delay. I'd happily merge it :+1:
