### ISSUE TITLE
Some method calls are treated as definitions

### ISSUE THREAD

**Issue by Kos** [babel/babel-sublime#217]
Looks like this syntax sometimes confuses method definitions with method calls. This affects functionality that relies on code indexing, like `Goto: Definition...` (F12) and `Goto: Symbol in project...` (Ctrl+shift+R).

I've also checked the `Javascript Next` syntax that this plug-in is based off. It has similar problems, but the behaviour is actually different, so I'm reporting it here.

Create a file:

```
class Foo {
  one() {
    this.broken(123); // 3
    this.okay();      // 4
  }

  broken() {
  }

  okay() {
  }
}
```

Put your cursor on `broken` in line 3, press F12 (`Goto> Definition...` in command palette). You'll get 2 choices, one pointing to the call itself in line 3, the other pointing to the actual definition below.

Put your cursor on `okay` in line 4, press F12 - you'll be correctly moved to the definition of `okay`.

Run "Ctrl-shift-R", you'll get the following suggestions:

- `Foo` - OK, points correctly to line 1
- `broken` - WRONG, finds 2 definitions, incorrect at line 3 and correct at line 7 (see above)
- `okay` - OK, points correctly to line 10
- `okay()` - WRONG, points incorrectly to line 4, shouldn't be indexed as it's not a definition
- `one()` - OK, points correctly to line 2

**Comment by zertosh** [comment]
It's working for me in ST3 Build 3095 (the current dev version). I wouldn't be surprised if it didn't work in the current beta version because that uses a different less-capable syntax format. Can you confirm the build of ST3 that you're using?

![goto-def](https://cloud.githubusercontent.com/assets/830952/12073077/fff48e28-b0bc-11e5-862b-af147c520a86.gif)
![suggest](https://cloud.githubusercontent.com/assets/830952/12073078/013df9d6-b0bd-11e5-81fb-028e2adf21a0.gif)

**Comment by Kos** [comment]
This might be it, I'm on ST3 build 3083 (from the Ubuntu PPA). Will have a look at the dev builds later today.

**Comment by zertosh** [comment]
@Kos is it working for you?

**Comment by Kos** [comment]
Yeah, can confirm the behaviour is OK on 3095 but broken on 3083.

**Comment by zertosh** [comment]
I figured. The syntax support in 3083 is pretty poor.

**Comment by Kos** [comment]
would you like a PR that will mention in the README that a dev build of Sublime is required? (I wasn't even aware there are newer versions until you pointed it out to me.)

**Comment by zertosh** [comment]
It's not required, it's just got different bugs.

**Comment by zertosh** [comment]
So maybe something that says for best support use "ST3 Build 3095"? I'll take that :smile: Thanks!
