### ISSUE TITLE
Can't find in package control

### ISSUE THREAD

**Issue by TomClarkson** [babel/babel-sublime#218]
Is there something I need to do to be able to install in sublime?

![screen shot 2015-12-03 at 12 44 54 pm](https://cloud.githubusercontent.com/assets/2054503/11547749/42e7b9ee-99bb-11e5-8747-421d58f86a85.png)

**Comment by zertosh** [comment]
It's definitely still available in package control. I know this issue is a month old, but installing it this very moment doesn't work because packagecontrol.io seems to be under a DDOS attack. https://github.com/wbond/package_control/issues/1045

**Comment by tejasmanohar** [comment]
@zertosh I'm facing the same issue. I see the package [here](https://packagecontrol.io/packages/Babel), but it doesn't seem to show up via cmd+shift+p -> "Package Control: Install Package" -> "Babel". I'm on latest ST3 - any ideas? Thanks in advance!

**Comment by zertosh** [comment]
It's there: 
<img width="495" alt="sflcq" src="https://cloud.githubusercontent.com/assets/830952/12360089/a4880d40-bb6a-11e5-8b26-2ef953082309.png">

**Comment by tejasmanohar** [comment]
Doesn't show up for me. Any tips?

**Comment by tejasmanohar** [comment]
Do I need to update repositories on package control or something?

**Comment by zertosh** [comment]
Package control autoupdates, but it sounds like you may have problems with that.

**Comment by wmech16** [comment]
Did anyone solve this? It is not showing for me either.

**Comment by bradAnderson58** [comment]
Doesnt show up for me either

**Comment by Spacelapp** [comment]
+1

**Comment by coolsebz** [comment]
it didn't show up for me either but I managed to solve it by doing the following:
cmd+shift+p -> "Package Control: Add Repository" -> Paste in `https://github.com/babel/babel-sublime` as the Github URL

After Package Control is done syncing you can install it normally
![screen shot 2017-01-25 at 2 29 52 am](https://cloud.githubusercontent.com/assets/2954356/22275717/991d9cea-e2a6-11e6-8908-9b446b0251c0.png)

**Comment by JosephLeon** [comment]
@coolsebz Thanks, worked like a charm!

**Comment by thenonsequitur** [comment]
Not sure why this issue is closed. I just had the same problem. @coolsebz's solution worked for me too though.

**Comment by vinhdang84** [comment]
Updated: CMD+SHIFT+P - "Install Package"
                 Then CMD+SHIFT+P - "Babel"
https://github.com/babel/babel-sublime/issues/327

**Comment by mikepeiman** [comment]
Had same issue, @coolsebz solution also saved me. Thanks!

**Comment by fgermanojr** [comment]
vinhdang84 had key for me, after colesebz (not sure i needed this too); next one here try vinhdan84 suggestion first.

**Comment by HaileHuang** [comment]
@vinhdang84 Thx! work for me~

**Comment by kapitanluffy** [comment]
I have the same problem. I have a ST3 dev build 3142

**Comment by cgat** [comment]
In my case, I had already installed this package many months ago (probably for a non react project, thinking I needed it for es6). When I went to search 'Install Package', 'Babel' didn't show up because it was already installed. Check 'List Packages' to see if it is already installed first.

**Comment by TiagoSilvaPereira** [comment]
+1 I have the same issue

**Comment by stuyam** [comment]
Have the same issue. Adding the repository as @coolsebz suggested worked.

**Comment by alexcroox** [comment]
+1 only babel-snippets shows, had to add git repo as repository before it showed

**Comment by ILovePens** [comment]
If the "adding a repo" method still doesn't work for you (that was the case for me), go see AnneTee's method a bit further up in issue #327 
It consists of manually adding and installing the babel repo inside your sublime text's packages (without using the commande palette). Just make sure you have Xcode or just the Xcode tools (`$ xcode-select --install`) before cloning the repo, and it should be a breeze!

**Comment by XavierMeunier** [comment]
If this doesn't work for you: 
- Package Control: Install
- Babel

Check logs, you may have disabled packages.
I had to do this to install Babel:
- Package Control: Enable Package
- Vintage
