### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Torvin** [babel/babel-sublime#220]
I've installed babel-sublime and haven't changed any settings. When I run 'Babel transform' command, I only get a new document with this content:

> 'NoneType' object is not subscriptable

PS: Sublime Text v3083

**Comment by Torvin** [comment]
Found the cause. `node_bridge()` has a bug here:

    raise Exception('Error: Couldn\'t find "node" in "%s"' % env['PATH'])

while `env` is not assigned when running on Windows and will always be `None`. Suggested fix:

    --- Babel/Babel.py
    +++ Babel/Babel.py
    @@ -79,11 +79,10 @@ class BabelCommand(sublime_plugin.TextCommand):
     
     
     def node_bridge(data, bin, args=[]):
    -	env = None
    +	env = os.environ.copy()
     	startupinfo = None
     	if os_name == 'osx':
     		# GUI apps in OS X doesn't contain .bashrc/.zshrc set paths
    -		env = os.environ.copy()
     		env['PATH'] += ':/usr/local/bin'
     	elif os_name == 'windows':
     		startupinfo = subprocess.STARTUPINFO()

**Comment by zertosh** [comment]
Hmm, does this actually make it work for Windows? Or just fixes showing a better error message?

**Comment by Torvin** [comment]
Yes, it shows the correct error message, instead of crashing miserably.

**Comment by zertosh** [comment]
Cool. Would you like to submit a PR? Or I can do it a bit

**Comment by Torvin** [comment]
I'm too lazy to submit a proper PR :) I was hoping the patch above would be enough.

**Comment by zertosh** [comment]
Fixed in v8.6.4
