### ISSUE TITLE
`type` breaks syntax highlighting

### ISSUE THREAD

**Issue by julien-f** [babel/babel-sublime#221]
``` js
if (type in handlers) { // Syntax highlighting is broken starting from this line.
  ...
}
```

**Comment by faiwer** [comment]
Confirm it:

![img_21_12_17 41 24_3fecbd6076e](https://cloud.githubusercontent.com/assets/744114/11930027/1d989020-a80a-11e5-84c2-a9d5f492f0cb.png)

**Comment by elmigranto** [comment]
Isn't `type` reserved word?

**Comment by zertosh** [comment]
Yeah. This is going to be hard. Sorry for letting this issue slip by.

**Comment by leesei** [comment]
The first line in the loop is not highlighted.
```js
for (let type of types) {
    let foo = bar;
}
```

Here's a workaround:
```js
for (let type of types) {
    ; // fix highlight of Sublime-babel
    let foo = bar;
}
```

**Comment by whw** [comment]
I'm also seeing this.

With `type`:
![screenshot 2016-10-06 11 29 49](https://cloud.githubusercontent.com/assets/62686/19165353/45bf0f2e-8bb8-11e6-87ab-08b47d1beee4.png)


Without `type`
![screenshot 2016-10-06 11 30 00](https://cloud.githubusercontent.com/assets/62686/19165363/53db0c70-8bb8-11e6-896e-f66125d33662.png)
:

**Comment by zertosh** [comment]
See re-rewrite babel-sublime #293.
