### ISSUE TITLE
Issue with rule overriding?

### ISSUE THREAD

**Issue by kzvaigzne** [babel/babel-sublime#223]
So I have a simple file `test.jsx` with the content
```
TestComponent = {};
```

And I'm getting a really weird error when linted:
```
test.jsx: line 1, col 1, Error - Rule 'no-reserved-keys' was removed and replaced by: quote-props (no-reserved-keys)
test.jsx: line 1, col 1, Error - Rule 'no-wrap-func' was removed and replaced by: no-extra-parens (no-wrap-func)
test.jsx: line 1, col 1, Error - Rule 'spaced-line-comment' was removed and replaced by: spaced-comment (spaced-line-comment)
```

What makes no sense is that none of those rules are related to the code actually linted..

Let me know if you need the full .eslintrc file content aswell but it's basically https://github.com/meteor/meteor/blob/devel/scripts/admin/eslint/.eslintrc

**Comment by zertosh** [comment]
Wrong repo
