### ISSUE TITLE
Non-egypt brackets at shorthand methods

### ISSUE THREAD

**Issue by faiwer** [babel/babel-sublime#224]
``` js
let a = {   
    method1()
    {

    },
    method2(){

    },
    method3(){}
};
```

shorten-name of method1 - white. 

![img_14_12_17 51 31_60cd6acaec8](https://cloud.githubusercontent.com/assets/744114/11780324/56b9f01c-a28b-11e5-9d35-49b856995823.png)

**Comment by faiwer** [comment]
Also methods list without `method`

![img_14_12_18 11 02_29ca9399797](https://cloud.githubusercontent.com/assets/744114/11780712/4be3e726-a28e-11e5-9879-4a83eb5a985e.png)

**Comment by zertosh** [comment]
Nothing I can do about this any time soon. The issue is with differentiating between short methods and function calls. It's a non-trivial issue because braces can create blocks or objects.

**Comment by zertosh** [comment]
This will work after "re-rewrite babel-sublime" #293.
