### ISSUE TITLE
Shorthand methods with a space before the parens

### ISSUE THREAD

**Issue by NicoSantangelo** [babel/babel-sublime#225]
Hey!

I don't know if this is the intended behaviour but adding a space before the parens in shorthand methods looks like this:

![image](https://cloud.githubusercontent.com/assets/692077/11989263/8d215754-a9d8-11e5-8af9-15dbe58a7049.png)

I can take a look but I think it might be better if #183 is merged first?

Thanks!

**Comment by zertosh** [comment]
Fixed in v8.6.3, but package control is having issues right now, so it might take a bit for you to see the update.

**Comment by NicoSantangelo** [comment]
Thanks!
