### ISSUE TITLE
Doesn't match React's end of line comments

### ISSUE THREAD

**Issue by wzup** [babel/babel-sublime#226]
React has an end of line comments https://facebook.github.io/react/docs/jsx-in-depth.html#comments
The plugin doesn't match them. Here is an example.

Default ST3 JavaScript syntax, matched:
![js_standard](https://cloud.githubusercontent.com/assets/3880497/12009121/249a7b7c-aca6-11e5-8832-5ab17cfbc73d.png)

JavaScript Babel, not matched
![js_babel](https://cloud.githubusercontent.com/assets/3880497/12009127/5d7fff8e-aca6-11e5-8d75-08025faba6b9.png)

**Comment by zertosh** [comment]
End of line comments within the attributes, not in the body. So the behavior you're seeing is correct. (However, it's doing the incorrect thing in ST3 build 3095 – but again, what you're seeing is correct).

<img width="499" alt="eaivm" src="https://cloud.githubusercontent.com/assets/830952/12073161/34142a74-b0c2-11e5-8f6d-dd926123db6b.png">

**Comment by zertosh** [comment]
You can also see that this is correct in the [transpiled output](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=%20%20%3CComponent%0A%20%20%20%20className%3D%22items%22%20%2F%2F%20comments%20are%20ok%20here%0A%20%20%20%20%3E%0A%20%20%20%20%7BitemNodes%7D%20%2F%2F%20I%20am%20not%20a%20comment%20%3CFoo%2F%3E%20but%20actual%20text%0A%20%20%3C%2FComponent%3E%0A%20%20)
