### ISSUE TITLE
Babel Not an Option under Syntax

### ISSUE THREAD

**Issue by jackiekamara** [babel/babel-sublime#227]
Hi!
I'm experiencing the same problem as folks earlier: Babel isn't an option in the language selector. Using OS X El Capitan, with Sublime Text 3, installed Babel through PackageControl.

<img width="498" alt="screen shot 2015-12-28 at 12 56 28 pm" src="https://cloud.githubusercontent.com/assets/16366430/12023019/57cbc362-ad63-11e5-90a9-852a7f72d3f6.png">

**Comment by zertosh** [comment]
That's weird. Is this still a problem?

**Comment by jackiekamara** [comment]
Yes. Still not working.

**Comment by zertosh** [comment]
Can you try re-installing it? It's never turned out to be a problem with babel-sublime, but it's always something weird with ST3.

**Comment by hoorayimhelping** [comment]
I think this is a package control issue. It's not showing up in search, and it has a badge that says `removed` next to it:

https://packagecontrol.io/search/babel
https://packagecontrol.io/packages/Babel

![](http://i.imgur.com/0L4V4IY.png)
![](http://i.imgur.com/e1qoUl1.png)

**Comment by zertosh** [comment]
I just tried a fresh install of ST3 and Package Control, and it's Babel is there. Feel free to open a new issue if there's something I missed.
