### ISSUE TITLE
Syntax highlighting HTML files (with JavaScript in them)

### ISSUE THREAD

**Issue by MareoRaft** [babel/babel-sublime#228]
Hey there!  I'm very happy with Babel syntax highlighting, but unfortunately it does not work correctly when I have an .html file with javascript in it.

Could there be support for or separate highlighting definition that includes basic HTML stuff?  That way when I write short html files with JS in them, I can see it well just like my javascript files.

Would be super helpful!  Thanks, let me know!

**Comment by zertosh** [comment]
javascript in html files is handled by the stock javascript syntax definition. if you want babel-sublime to take precedent over it, you'll have to disable the builtin one. personally, i do this, but i can't guarantee that other plugins won't suffer as a result. see https://github.com/babel/babel-sublime#advanced-usage

**Comment by MareoRaft** [comment]
Thanks!  So far so good!

**Comment by zertosh** [comment]
Ok cool

**Comment by kaste** [comment]
By disabling the builtin Javascript package, I get

![disable javascript](https://cloud.githubusercontent.com/assets/8558/12418187/fc135bdc-bead-11e5-9194-52cb2cf55653.PNG)
![disable javascript 2](https://cloud.githubusercontent.com/assets/8558/12418190/02ffa450-beae-11e5-8b17-90a8b0c24d02.PNG)

**Comment by zertosh** [comment]
@kaste, disabling the builtin javascript package is a run At Your Own Risk setting. I have no intention of supporting it, I'm just letting users know that that is an option. That said, on Mac and Linux, I've never seen the stock HTML package complain about not finding the stock Javascript package. Maybe it's a windows thing? Sorry.

**Comment by kaste** [comment]
Enabling, disabling things randomly and restarting Sublime several times
before, after and in-between did it. 💪

Andres Suarez <notifications@github.com> schrieb am Di., 19. Jan. 2016
18:30:
