### ISSUE TITLE
Bad export JSX highlighting

### ISSUE THREAD

**Issue by gajus** [babel/babel-sublime#229]
<img width="340" alt="screen shot 2016-01-02 at 14 41 04" src="https://cloud.githubusercontent.com/assets/973543/12074777/de7b5888-b15e-11e5-9343-69c5d89edf49.png">

What it should be:

<img width="348" alt="screen shot 2016-01-02 at 14 41 20" src="https://cloud.githubusercontent.com/assets/973543/12074778/e6d743c0-b15e-11e5-9a90-c8694edb24ad.png">

**Comment by zertosh** [comment]
Fixed in v8.6.5, but package control is still down

**Comment by gajus** [comment]
Awesome. Thank you
