### ISSUE TITLE
Not really an issue but update babel-sublime

### ISSUE THREAD

**Issue by v1rt** [babel/babel-sublime#230]
I installed babel-sublime 6 months ago in my sublime text 3. I would like to update it. How can I update it?

**Comment by hawkrives** [comment]
Package Control usually automatically updates packages. You can check the version that you have installed by opening the Command Pallet (⌘/CTRL-SHIFT-P) and choosing "List Packages".

If it's not up-to-date (my copy is at v8.6.2), then you should be able to update it with the "Upgrade Package" command.

**Comment by v1rt** [comment]
That worked! Thanks!
