### ISSUE TITLE
GraphQL syntax highlighting

### ISSUE THREAD

**Issue by kulakowka** [babel/babel-sublime#231]
Are you plan to support syntax for GraphQL queries?

Now it looks ugly:
<img width="331" alt="2016-01-07 20 22 36" src="https://cloud.githubusercontent.com/assets/557190/12177303/6eb088e4-b57c-11e5-9a90-e6fbc377cd11.png">

**Comment by zertosh** [comment]
I've tried, and I'd love to, but there's a giant problem: Embedding expressions (i.e. `${ }`) break the continuity of the string and it makes useful highlighting impossible. You could end up in a worse off place.

So I'm calling this a won't fix. Sorry.
