### ISSUE TITLE
Advice for Syntax

### ISSUE THREAD

**Issue by Alexey-T** [babel/babel-sublime#232]
Hi; i make syntax for JSX for my editor. Can you advice? Is it good (in syntax lexer) to hilite also JQuery spec words? 

$
add
addBack
addClass
after
ajax

....etc. Or JSX/Babel don't need to hilite these words?

**Comment by hawkrives** [comment]
While it's up to you, I will note that I don't use jQuery in my react apps, so I would likely find the highlighting pointless.

**Comment by Alexey-T** [comment]
thanx.
