### ISSUE TITLE
Possible to use Babel for Markdown?

### ISSUE THREAD

**Issue by wesbos** [babel/babel-sublime#235]
I'm trying to write ES6 in markdown, but it some code like this breaks the highlighter:

I asked this question over at Markdown Editing: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/305 

I'm not sure if you package would be able to play along nicely with markdown editing? 

![](http://wes.io/eqhq/content)

![](http://wes.io/dE5t/content)

**Comment by zertosh** [comment]
Sublime's stock JavaScript package is taken precedence over babel-sublime. The solution is to disable it (see https://github.com/babel/babel-sublime#advanced-usage). However, you're on your own after that. I personally haven't had any problems, but I don't know how many plugins out there expect the stock JavaScript package to be enabled.

**Comment by paullaffitte** [comment]
I tried it but it just made it worse..

**Comment by paullaffitte** [comment]
Still not working

![image](https://user-images.githubusercontent.com/23403270/85393327-03572580-b577-11ea-956f-39ad5ea047bc.png)
