### ISSUE TITLE
Syntax Highlighting: 'static' Keyword and Function Names

### ISSUE THREAD

**Issue by rikkuporta** [babel/babel-sublime#240]
The static Keyword is only highlighted the first time it occurs and the first Function name afterwards is not highlighted at all. This only occurs if you omit the Semicolon after defining the variable. 

I'm not sure if this is valid ES6 Syntax. It seems to produce the same results in code and looks 'valid'. 
![image](https://cloud.githubusercontent.com/assets/3002584/13057478/d777518c-d41c-11e5-9893-6b3f72bf9e5f.png)
![image](https://cloud.githubusercontent.com/assets/3002584/13057489/e67fd348-d41c-11e5-8c73-426295009a8d.png)
![image](https://cloud.githubusercontent.com/assets/3002584/13057506/028ee434-d41d-11e5-8a18-de227ead7c92.png)
![image](https://cloud.githubusercontent.com/assets/3002584/13057523/13834b04-d41d-11e5-9230-e9ec6ac45079.png)

**Update:**
![image](https://cloud.githubusercontent.com/assets/3002584/13060705/92b8929c-d433-11e5-92a4-93d7a1aac7ac.png)
The first Arrow Functions seems also to be affected, but not related to the stuff mentioned before

**Comment by yinzSE** [comment]
+1

**Comment by sotojuan** [comment]
Any update on this? Looks like it'd be an easy PR (no idea how to do Sublime stuff though).

**Comment by gridsane** [comment]
I use the workaround which removes `class-properties` scope:

```diff
diff --git a/JavaScript (Babel).sublime-syntax b/JavaScript (Babel).sublime-syntax
index ec9403e..db44fcf 100644
--- a/JavaScript (Babel).sublime-syntax
+++ b/JavaScript (Babel).sublime-syntax
@@ -199,10 +199,10 @@ contexts:
           scope: punctuation.definition.class.body.end.js
           pop: true
         - include: es7-decorators
-        - include: class-properties
         - include: class-method-definition
         - include: class-method-storage
         - include: brackets
+        - include: expression

   flowtype-declaration:
     - match: (?<!\.)\b(declare)\b
@@ -326,16 +326,6 @@ contexts:
     - match: \*
       scope: keyword.generator.asterisk.js

-  class-properties:
-    - match: ([_$a-zA-Z][$\w]*)(?=\s*[:=])
-      scope: variable.other.property.js
-      push:
-        - meta_scope: meta.class.property.js
-        - match: (?=\s*[;}])
-          pop: true
-        - include: flowtype-annotation
-        - include: expression
-
   literal-method:
     # e.g. play(arg1, arg2) {  }
     - match: >-
```

It completely fits my needs and doesn't have any side-effects for my environment.

**Comment by nathanmarks** [comment]
@rikkuporta Try semicolons after statics and class properties:

![2016-06-27 at 9 41 am](https://cloud.githubusercontent.com/assets/4420103/16381607/56377178-3c4b-11e6-88f3-cbb984c7bd8b.png)

**Comment by antoinerousseau** [comment]
@gridsane does this workaround fixes the issue or does it remove the highlighting on the static props? if it fixes all, can you make a PR?

**Comment by jayseeg** [comment]
@nathanmarks—thanks for the workaround,... hoping for a workaround or fix that doesn't require semicolons.

**Comment by zertosh** [comment]
See "re-rewrite babel-sublime" #293.

**Comment by scarlac** [comment]
@antoinerousseau I tried @gridsane's fix and it work. I see no immediate downside. Highlighting seems to work just fine. I think his fix is just changing the parser so it's using Babel to parse the class properties instead of using it's own regular expression match which was incomplete. A seemingly valid way to fix the issue.

**Comment by antoinerousseau** [comment]
it indeed resolves the bug!
