### ISSUE TITLE
Not highlighting => functions and template strings ` poor readability

### ISSUE THREAD

**Issue by vans163** [babel/babel-sublime#241]
Template strings using grave accent are being highlighted very poorly IMO. They should use the same highlight as "".  Atm they blend in with everything else and its hard to tell if its a string or code.  Atleast highlight the ` gold as well to see where the string starts and ends.  

This seems to be a regression as the image in the README shows grave accent template strings highlighted properly.

Functions using => syntax are not being highlighted in class definitions.  This is a deal breaker as using React with ES6 classes you are required to use them to pass this around.

![](http://i.imgur.com/5nyFSL6.png)

**Comment by zertosh** [comment]
In "re-rewrite babel-sublime" #293, I intend to scope the backticks as "string". However the content of the interpolated expression is **purposefully** not scoped as part of the string. This is so themes  don't turn the entire expression "string colored".

**Comment by vans163** [comment]
I do not agree with this.  A string is a string and should appear as a string, even if its being built in a dynamic way.  When you see things inside grave accented highlighted as not a string, its hard to tell what it belongs to, since the grave accents are so hard to see.
