### ISSUE TITLE
Inline string concat in ternary breaks highlighting

### ISSUE THREAD

**Issue by stevenguh** [babel/babel-sublime#244]
![capture](https://cloud.githubusercontent.com/assets/3455662/13305403/debd056e-db0f-11e5-93ce-b1695a4fb444.png)

As you can see in the picture, the string concat doesn't have correct highlighting if there is no parenthesis around it.

**Comment by woollybogger** [comment]
Adding some more examples in case it helps.

![stringvar](https://cloud.githubusercontent.com/assets/5128013/13417574/47dd69f6-df3b-11e5-8568-83d873c70913.png)

**Comment by zertosh** [comment]
I added a test for this issue to fix it in the re-write. See "re-rewrite babel-sublime" #293.

**Comment by Danetag** [comment]
Sorry for probably commenting on the wrong ticket, but it seems to have the same issue in JSX? 

<img width="552" alt="screen shot 2017-04-11 at 10 18 23 am" src="https://cloud.githubusercontent.com/assets/810008/24913805/50e267fe-1ea0-11e7-9834-c928349e0b7d.png">
