### ISSUE TITLE
Linting errors with JSX

### ISSUE THREAD

**Issue by varunarora** [babel/babel-sublime#247]
I just setup the package. Everything seems to be setup correctly (I have selected the right option for the syntax view), but my JSX seems to have linting errors. Is this related to JSHint? Or this a babel-sublime issue?

![screenshot from 2016-03-02 11 51 22](https://cloud.githubusercontent.com/assets/629203/13473328/bb5f1f18-e06d-11e5-9ec1-ea02d10890dc.png)

Build: 3065; babel-sublime: 8.6.3

**Comment by zertosh** [comment]
That's not babel-sublime. That's your linter package.
