### ISSUE TITLE
Scopes behave differently when have more than fifteen levels in code

### ISSUE THREAD

**Issue by voronianski** [babel/babel-sublime#249]
In regular Sublime's (v3) Javascript syntax highlighter this is not an issue:

![image](https://cloud.githubusercontent.com/assets/974035/13574418/ae7360c0-e48c-11e5-9634-36847ec41f40.png)

**Comment by zertosh** [comment]
That's the mustache support breaking it. I added a test to fix this in the re-write. See "re-rewrite babel-sublime" #293.
