### ISSUE TITLE
JSX components with attributes break highlighting

### ISSUE THREAD

**Issue by beeftornado** [babel/babel-sublime#250]
Desired code, causes rest of file to look blue (in my theme).

![screen shot 2016-03-09 at 4 57 39 pm](https://cloud.githubusercontent.com/assets/1356875/13656075/bde5e3f6-e618-11e5-96ed-b48a6bbed83b.png)

Removing the slash in the self closing tag works but obviously not what I want to do.

![screen shot 2016-03-09 at 4 57 55 pm](https://cloud.githubusercontent.com/assets/1356875/13656093/d2978cfa-e618-11e5-88a9-faeb0b25983d.png)

Removing attributes from the component tag also works, but impractical.

![screen shot 2016-03-09 at 5 01 50 pm](https://cloud.githubusercontent.com/assets/1356875/13656099/e211e054-e618-11e5-8b01-0292c4362654.png)

**Comment by zertosh** [comment]
Pretty sure this isn't an issue anymore.
