### ISSUE TITLE
Highlighting does not match screenshot in readme, invoked functions are not highlighted

### ISSUE THREAD

**Issue by phelma** [babel/babel-sublime#251]
![untitled_and_babel_babel-sublime__syntax_definitions_for_es6_javascript_with_react_jsx_extensions_](https://cloud.githubusercontent.com/assets/4057948/13748008/df149440-e9f2-11e5-9751-cb6ed4eed83d.jpg)

**Comment by rickmed** [comment]
+1

**Comment by ashokfernandez** [comment]
+1 makes code a lot harder to read than when using JavaScript Next

**Comment by joshkpeterson** [comment]
I'm also experiencing this. Additionally, comments inside jsx aren't highlighted correctly. E.g. if I comment out a line of js, it isn't grayed out -- it still has all the normal highlighted colors.

**Comment by zertosh** [comment]
I scoped this incorrectly - sorry. See "re-rewrite babel-sublime" #293.
