### ISSUE TITLE
For-of hightlight

### ISSUE THREAD

**Issue by faiwer** [babel/babel-sublime#253]
``` js
for(let a of list) ;
for(let a of []) ;
for(let a of (list || [])) ;
```

![img_18_03_15 41 55_88f2621d347](https://cloud.githubusercontent.com/assets/744114/13874123/fb30aa8a-ed1f-11e5-989e-f30d3ab5f9b1.png)

White `of` on 3 line

**Comment by leesei** [comment]
```js
for (let type of types) {
    let foo = bar;
}
```

The first line in the loop is not highlighted.

Here's a workaround:
```js
for (let type of types) {
    ; // fix highlight of Sublime-babel
    let foo = bar;
}
```

**Comment by faiwer** [comment]
@leesei , looks like https://github.com/babel/babel-sublime/issues/221

**Comment by leesei** [comment]
@faiwer thanks for the link, I've also post the snippet there.

**Comment by zertosh** [comment]
I just added a test for this to catch it in the re-write. See "re-rewrite babel-sublime" #293.
