### ISSUE TITLE
Babel corrupts the original Javascript syntax definitions, thus making 'Jump to symbol (R)' useless

### ISSUE THREAD

**Issue by karolyi** [babel/babel-sublime#254]
Hey guys,

the folks at Sublime implemented a newer Javascript syntax recently (as of dev build 3103), which in connection with using babel-sublime, breaks the 'Jump to symbol (R)' functionality for the original Javascript syntax (using '`JavaScript (Babel)`' still works).

Here's the issue for Sublime, turns out it's not their fault: https://github.com/sublimehq/Packages/issues/249

Removing babel-sublime and using the default javascript syntax reenables the proper jump to symbol functionality.

Could you loo into this issue? Thx.

**Comment by karolyi** [comment]
ping

**Comment by zertosh** [comment]
babel-sublime targets the same scopes as the stock definition, so you're going to have these issues. I need to look into the latest changes to the stock syntax to see how the selectors changed and what I can do to accommodate.

**Comment by zimenskiy** [comment]
In Sublime's build 3114 goto definition feature works weird with Babel plugin installed: when activating goto definition in the list of search results also appears function calls instead of function definition(s) only.

Jump to symbol seems to work well.

**Comment by davidnormo** [comment]
This would be really helpful to get working!

**Comment by neaumusic** [comment]
This is absolutely absurd and I've wasted so much time because neither CMD+R or CMD+Opt+Down works see https://github.com/SublimeTextIssues/Core/issues/1368

**Comment by zertosh** [comment]
Will be fixed. See "re-rewrite babel-sublime" #293.
