### ISSUE TITLE
What are the provided color schemes for?

### ISSUE THREAD

**Issue by KevinSjoberg** [babel/babel-sublime#255]
I'm new to Sublime Text and when I installed babel-sublime I noticed it shipped with two color schemes. What are those for? Are these color schemes giving me something my standard color scheme isn't? Would love to know.

If they are, I think we should update the `README` to explain this for anyone else having the same question.

**Comment by zertosh** [comment]
One is legacy cruft. The other is for debugging the syntax – it colors everything differently in ugly colors.

**Comment by KevinSjoberg** [comment]
Thank you. Makes sense.
