### ISSUE TITLE
Shorthand if-else is taken for object literal

### ISSUE THREAD

**Issue by Juribiyan** [babel/babel-sublime#256]
```
function fn(a) { return a ? a*a : 0 }
```

The last `a` is highlighted as if it was a property key in an object literal.

**Comment by zertosh** [comment]
Yeah - sorry, this is a bad one. With regexs you can't distinguish between object literals and blocks. So there are weird edge cases like this.

**Comment by zertosh** [comment]
Just added a test for this to catch it in the re-write. See "re-rewrite babel-sublime" #293.
