### ISSUE TITLE
return ’<div></div>‘  syntax highlighting bug

### ISSUE THREAD

**Issue by Princeraul** [babel/babel-sublime#257]
screenshot：
![qq 20160329102458](https://cloud.githubusercontent.com/assets/5966186/14096399/130704fa-f59b-11e5-8c4c-e571ebf2cd6d.png)
![qq 20160329102509](https://cloud.githubusercontent.com/assets/5966186/14096400/195dba2e-f59b-11e5-86db-98374e0c6689.png)

**Comment by caesarsol** [comment]
This doesn't seem a syntax highlighting bug, is it?

**Comment by zertosh** [comment]
That seems to be Sublime's indexer complaining. I could be babel-sublime, or maybe not. What version of Sublime do you have?

**Comment by gfd6th** [comment]
@zertosh I got the same issue. My sublime version is 3114
<img width="297" alt="2016-06-06 5 15 00" src="https://cloud.githubusercontent.com/assets/6814715/15817352/3813bd10-2c0a-11e6-8fb8-091f17a544a5.png">
<img width="696" alt="2016-06-06 5 15 33" src="https://cloud.githubusercontent.com/assets/6814715/15817366/468350d6-2c0a-11e6-96ff-5e4a12025538.png">

**Comment by zertosh** [comment]
I can't repro this. I'm triaging the issues for a re-write, so closing this since it's not actionable. See "re-rewrite babel-sublime" #293.
