### ISSUE TITLE
Add additional syntax highlighting the way Javascript Ultimate does (for instance, JSDOC)

### ISSUE THREAD

**Issue by Palid** [babel/babel-sublime#258]
Right now babel-sublime lacks some of the highlighting for some of the frequently used things like regexes or JSDoc. It would be really great if you could add this highlighting to the package. Javascript Ultimate already implements it, but it doesn't implement ES6, unfortunately.

https://github.com/JoshuaWise/javascript-ultimate

**Comment by zertosh** [comment]
Regex highlighting is really good. I had JSDoc at one point, but I removed it – it got distracting. Do you have an example of bad regex highlighting?

**Comment by zertosh** [comment]
Not going to support jsdoc beyond basic tags in the re-write. See "re-rewrite babel-sublime" #293.
