### ISSUE TITLE
JSX Indentation is not useful

### ISSUE THREAD

**Issue by lawrence-yu** [babel/babel-sublime#261]
Given a JSX file that has been set to use Babel (Javascript) syntax, when I reindent my entire file, the JSX portions do not get properly indented.

![image](https://cloud.githubusercontent.com/assets/3094147/14796340/b0c09052-0ae1-11e6-849a-c4dd54b9a8a6.png)

**Comment by zertosh** [comment]
How are you reindenting?

**Comment by lawrence-yu** [comment]
This behavior occurs when using the two following methods:

1. Using the Ctrl+Shift+P to "Indentation: Reindent Lines" command
2. Using Vintageous, inputing the following key-sequence ```gg=G``` (go to top of the file, then reindent to the bottom of the file).

**Comment by expaand** [comment]
I am having the same problem, in a js file set to use Babel-JS formatting. When I re-indent, all of the JSX loses it's indenting, and gets left justified. It seems to be highlighted correctly, though. And the remainder of the file seems more-or-less correct (but not always).

**Comment by vexpaand** [comment]
Example of incorrect JSX indentation (indent via Ctrl-Shift-P + "Indentation: Reindent Lines"):

Before:
<img width="352" alt="sublime_babel_before" src="https://cloud.githubusercontent.com/assets/7213443/16569559/e7f2debc-4205-11e6-8269-13324e9bdb9a.png">
After:
<img width="336" alt="sublime_babel_after" src="https://cloud.githubusercontent.com/assets/7213443/16569561/f2f84342-4205-11e6-9ab1-12c5d442e055.png">

**Comment by julesmoretti** [comment]
Same thing here. Would love this functionality :)

**Comment by actuallymentor** [comment]
Same as @vexpaand, by workflow I almost automatically press autoindent every few minutes. This plugin while a great highlighter totally mixes up the indentation...

**Comment by zertosh** [comment]
Tracking this in #293.

**Comment by rainitesh** [comment]
I am still facing this issue. has this been resolved?

**Comment by chrislzm** [comment]
I am also encountering this issue.

**Comment by vishwakarma09** [comment]
same here
