### ISSUE TITLE
What is the status of this repo?

### ISSUE THREAD

**Issue by fatfisz** [babel/babel-sublime#263]
@zertosh It seems that for some time there haven't been any new commits despite the not-that-small list of issues. I'm not judging, I'm just curious what are the reasons. Are there any plans to pass the baton to someone else?

**Comment by zertosh** [comment]
I'm terribly sorry for this. Updates and fixes will be coming soon.

Sublime added a new way syntax definition format but it seemed like it was never going to come out of dev and into beta. That changed with http://www.sublimetext.com/blog/articles/sublime-text-3-build-3080. I've was maintaining two different syntax definitions here, with varying degrees of correctness- but now I can focus on the one syntax.

**Comment by fatfisz** [comment]
Don't be, you've done a great work! I was just afraid that this repo was abandoned.

Thanks for your hard work!
