### ISSUE TITLE
Javascript (Babel) not available as a syntax selection

### ISSUE THREAD

**Issue by motleydev** [babel/babel-sublime#264]
I've installed and reinstalled this package but I can't choose the Javascript (Babel) syntax. I have it working on a different machine but on my office iMac it doesn't show up. Any ideas what to try? I see the package listed in my packages.

**Comment by dwayne-roberts** [comment]
Could it be disabled? Check your user settings and see if the package is listed among `ignored_packages`

**Comment by mxchai** [comment]
@motleydev Not sure if you've solved your problem, but for me, I was looking for it under Javascript -> Javascript (Babel) but it was actually under Babel -> Javascript (Babel).

**Comment by dcm4c0** [comment]
Same problem here on Win10, doesnt show up in the context and not listed among ignored_packages"

**Comment by grantdelozier** [comment]
Same issue here on OS X version. I installed via package control, got no error, isn't in ignored packages. Yet still does not appear as an option under View -> Syntax -> Open all with current extension as ->

**Comment by zertosh** [comment]
Not sure what the issue is here, but may have been something transient.

**Comment by SocialHulkHogan** [comment]
I actually just ran into this as well. Issue should probably be looked at again.  its in my installed packages but I can't see it as a syntax option. Very discouraging.
