### ISSUE TITLE
Add highlighting for jsdoc block tags

### ISSUE THREAD

**Issue by dwayne-roberts** [babel/babel-sublime#265]
When I comment my javascript using jsdoc style comments I miss the syntax highlighting of the various block tags (keywords). Everything is the same color in a comment. Could anyone add support for this? Or if someone points me in the right direction I can add support for it myself and make a pull request.

**Comment by zertosh** [comment]
I'll be adding basic tag support. See "re-rewrite babel-sublime" #293.
