### ISSUE TITLE
Suggestion to ignore package "JavaScript" causes error

### ISSUE THREAD

**Issue by jubalm** [babel/babel-sublime#266]
# Not recommending the use of tip [here](https://github.com/babel/babel-sublime#advanced-usage) (Advanced usage), as it spits out the following error.

```
Error loading syntax file "Packages/JavaScript/JSON.sublime-syntax": Unable to read Packages/JavaScript/JSON.sublime-syntax
```

Better stick with the default syntax settings [here](https://github.com/babel/babel-sublime#setting-as-the-default-syntax).

**Comment by aaronromeo** [comment]
Same error here.

**Comment by CrabPin** [comment]
FWIW, I fixed this with a subset of the following:

1. **The important one:** Associated all `.json` and `.sublime-settings` with `Babel > JavaScript (Babel)` (instead of `Babel > JSON`)
1. *(Not sure if this is necessary:)* Closed all existing JSON files (`.json` & `.sublime-settings`)
1. Restarted

**Comment by pksunkara** [comment]
But the syntax highlighting of JSON files go wonky if we do that.

**Comment by zertosh** [comment]
I won't be recommending this anymore. I'll update the README after "re-rewrite babel-sublime" #293.

**Comment by alopatin** [comment]
There's a really simple fix for this: Just copy the `JSON.sublime-syntax` file from `Sublime Text.app/Contents/MacOS/Packages/JavaScript.sublime-package` into `~/Library/Application Support/Sublime Text 3/Packages/User/`.

For convenience, [here is a gist](https://gist.github.com/alopatin/e33136230fbcfd2545ff472644bde359) with the extracted `JSON.sublime-syntax` file.

**Comment by jbruni** [comment]
Thanks, @alopatin 
In my Ubuntu Linux install, the paths were:
- source: `/opt/sublime_text/Packages/JavaScript.sublime-package`
- destiny: `~/.config/sublime-text-3/Packages/User`

**Comment by phil123456** [comment]
I dont get it, the file is already installed in the packages folder, wtf
