### ISSUE TITLE
Static properties combining ::, =>, and number literals break syntax highlighting

### ISSUE THREAD

**Issue by appsforartists** [babel/babel-sublime#270]
Using [transform-function-bind](http://babeljs.io/docs/plugins/transform-function-bind/) and [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) together makes syntax highlighting very fragile.  For instance, this won't highlight:

``` javascript
export class Example {
  _someStream = someOtherStream::map(
    thing => 1
  );

  constructor() {
    console.log('this should be highlighted');
  }
}
```

but replacing the `1` with an identifier will highlight correctly.

**Comment by zertosh** [comment]
Just added a test to catch this in the rewrite. See "re-rewrite babel-sublime" #293.
