### ISSUE TITLE
Syntax Highlighting: void with jsx

### ISSUE THREAD

**Issue by kjs3** [babel/babel-sublime#274]
[This line](https://github.com/facebook/react/blob/master/src/renderers/dom/__tests__/ReactDOMProduction-test.js#L46) in the react codebase breaks highlighting. 

```
void <div>{[<span />]}</div>;
// everything from the "</" on is messed up 
```

**Comment by zertosh** [comment]
Just added a test for this to catch it in the re-write. See "re-rewrite babel-sublime" #293.
