### ISSUE TITLE
Syntax highlight bug when string literal contains left bracket

### ISSUE THREAD

**Issue by felixhao28** [babel/babel-sublime#275]
``` js
if (_.startsWith(line, 'State(')) {
}
```

![image](https://cloud.githubusercontent.com/assets/2417391/17506858/b51de6c6-5e3e-11e6-9293-da95e54ec650.png)

**Comment by zertosh** [comment]
Yeah this is bad :( Just added a test to catch this in the rewrite. See "re-rewrite babel-sublime" #293.
