### ISSUE TITLE
Syntax Highlight Issue with Static Properties

### ISSUE THREAD

**Issue by ChrisPikul510** [babel/babel-sublime#276]
I'm noticing a syntax highlight quirk with static properties. It seems to require a semicolon at the end of declarations in order to correct.

<img width="471" alt="screen shot 2016-08-12 at 4 14 25 pm" src="https://cloud.githubusercontent.com/assets/4327937/17623288/ea9622a8-60a7-11e6-82ac-7419aedb710e.png">

<img width="463" alt="screen shot 2016-08-12 at 4 15 16 pm" src="https://cloud.githubusercontent.com/assets/4327937/17623301/011b3f40-60a8-11e6-9a1f-9fe5449e7e83.png">

**Comment by zertosh** [comment]
Yup, known issue. Will be fixing this soon. See "re-rewrite babel-sublime" #293.
