### ISSUE TITLE
Missing syntax highlighting for nested object destructuring inside function params

### ISSUE THREAD

**Issue by silverlight513** [babel/babel-sublime#285]
I've got a function that is passed the prop location (I'm using redux) and inside that I need to get a query value so I've destructured the object like so:
![image](https://cloud.githubusercontent.com/assets/4225358/19107198/09bd0cc2-8ae3-11e6-9f05-fae07f1e9e56.png)
The first variable that gets created is highlighted but the second is not and neither is the default value.

**Comment by borela** [comment]
Hi, I am writing a new package to try to account for all the specifics of the javascript syntax https://github.com/borela/naomi could try it and see if it solves your problem? The syntax is FJSX15 and right now I only have one color scheme capable of differentiating things like destructuring vs object literals, any help creating new color schemes, reporting bugs, etc is appreciated.

**Comment by zertosh** [comment]
See "re-rewrite babel-sublime" #293.
