### ISSUE TITLE
Syntax highlighting ternary in object expression

### ISSUE THREAD

**Issue by davidnormo** [babel/babel-sublime#288]
![screen shot 2016-10-13 at 14 16 54](https://cloud.githubusercontent.com/assets/881849/19350452/ba74aa6c-914f-11e6-9bf1-3d2b2e0a83d5.png)

It seems if a new line occurs in the ternary, it marks it as a property of the object. v8.6.3

**Comment by zertosh** [comment]
I'm aware of this issue. See "re-rewrite babel-sublime" #293.
