### ISSUE TITLE
syntax highlighting issue

### ISSUE THREAD

**Issue by br4nnigan** [babel/babel-sublime#296]
figured i wanna use static keyword instead of prototype like adding stuff outside, turns out only the first is properly colored. On top if you move the constructor method below it's another color than when above this. Hope this is the right place to post

<img width="309" alt="st-babel" src="https://cloud.githubusercontent.com/assets/10244835/21358401/dece7aaa-c6d8-11e6-954d-501ffdf115fa.png">

**Comment by antoinerousseau** [comment]
https://github.com/babel/babel-sublime/issues/240#issuecomment-223561046 seems to fix this. if so I could make a PR

**Comment by br4nnigan** [comment]
definately a duplicate
