### ISSUE TITLE
syntax highlighting issue with flow

### ISSUE THREAD

**Issue by nishp1** [babel/babel-sublime#297]
When declaring flowtypes inline, I am seeing syntax highlighting not work for the code that follows it. 

<img width="392" alt="screen shot 2016-12-21 at 5 39 02 pm" src="https://cloud.githubusercontent.com/assets/553376/21408706/7274fc72-c7a4-11e6-971e-e6bf69c8c4d9.png">

**Comment by nishp1** [comment]
Looks like adding semicolon to type fixes the issue. Closing now as https://github.com/babel/babel-sublime/issues/293 promises to fix this.

**Comment by Diokuz** [comment]
I dont want to use semicolon, so the problem is actual for me.

**Comment by azymnis** [comment]
I'm using eslint and I don't want semicolons so is there a way to get around this without semicolons?
