### ISSUE TITLE
Flowtype type keyword messes with ordinary JS var type

### ISSUE THREAD

**Issue by StreetStrider** [babel/babel-sublime#298]
The code like:
```js
if (type in types) …
```
prioritizes Flow `type` keyword (even if I'm using oridnary JavaScript). So after `type` syntax highlighting brokes for the rest of the file.

**Comment by ErkanSensei** [comment]
Same here

**Comment by davidbarton** [comment]
Is it same issue as this?

![screencapture at fri jan 27 14 52 30 cet 2017](https://cloud.githubusercontent.com/assets/1619732/22373047/52615cf0-e4a0-11e6-9cbd-b8e3bfe652c8.png)

**Comment by StreetStrider** [comment]
@davidbarton, looks similar, may be caused by the same.

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
