### ISSUE TITLE
Syntax highlighting not working for js files with jsx syntax

### ISSUE THREAD

**Issue by dingn1** [babel/babel-sublime#299]
<img width="1430" alt="screen shot 2017-01-04 at 3 53 43 pm" src="https://cloud.githubusercontent.com/assets/12637101/21658810/07670270-d296-11e6-815f-591757543508.png">

**Comment by souravray** [comment]
It is even worst in my case - 
![screen-grab-sublime-text-babel](https://cloud.githubusercontent.com/assets/364657/24758733/dd5406f0-1b00-11e7-9372-681710891632.png)

I am using SublimeText 3 on Win7

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
