### ISSUE TITLE
Method calls not colored correctly

### ISSUE THREAD

**Issue by bobmoff** [babel/babel-sublime#300]
![2017-01-16 at 10 55](https://cloud.githubusercontent.com/assets/1033236/21978324/66eed2e8-dbda-11e6-9cde-02855222928f.png)

In the screenshots in the README, they are green to separate props from method calls.

When using the JavascriptNext syntax method calls get colored green, but then JSX is not supported.

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi it even supports stage-0 features.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
