### ISSUE TITLE
Problems with syntax highlighting for arrow functions in ES6 class declarations

### ISSUE THREAD

**Issue by huntwj** [babel/babel-sublime#301]
The first arrow function in ES6 class declarations does not highlight correctly.

Example 1: 
<img width="337" alt="screen shot 2017-01-18 at 2 06 28 pm" src="https://cloud.githubusercontent.com/assets/2975468/22085050/59f0f25c-dd87-11e6-8e0b-707b178c3f06.png">

Example 2:
<img width="342" alt="screen shot 2017-01-18 at 2 05 36 pm" src="https://cloud.githubusercontent.com/assets/2975468/22085053/5e2888a8-dd87-11e6-8fd2-a24b12cc1698.png">

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by jbccollins** [comment]
@borela that's pretty sweet! It does have some pretty annoying issues though. I find https://github.com/borela/naomi/issues/72 to be particularly annoying and even with the manual patch described in those comments it still balks on nested objects in some cases.

**Comment by borela** [comment]
@jbccollins I actually prefer keys being highlighted as unquoted strings too, I am thinking about reverting back to unquoted strings and see how many users will complain about it before I implement configurable system.

**Comment by borela** [comment]
@jbccollins Try version >= 3.7.0

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
