### ISSUE TITLE
Using the keyword `type` inside a `for` condition breaks syntax highlighting

### ISSUE THREAD

**Issue by asfktz** [babel/babel-sublime#308]
![screen shot 2017-02-16 at 23 09 54](https://cloud.githubusercontent.com/assets/199747/23041291/15602342-f49d-11e6-869d-ea6cfd6551cc.png)
![screen shot 2017-02-16 at 23 09 51](https://cloud.githubusercontent.com/assets/199747/23041292/158135d2-f49d-11e6-907e-3584d7876122.png)

**Comment by StreetStrider** [comment]
#298

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
