### ISSUE TITLE
Move snippets to separate repo?

### ISSUE THREAD

**Issue by cesarandreu** [babel/babel-sublime#31]
Not a fan of having snippets automatically included :(. Could we move em to a separate repo? 

I have my own set of personal JS snippets, and since you can't disable package-specific snippets my only choice would be to fork 6to5-sublime and keep it up-to-date manually everywhere I have a sublime text installation.

**Comment by zertosh** [comment]
@sebmck Thoughts? Makes sense to me. I actually want to get rid of the snippets all together. The only snippet I use is for `for`-loops lol - I don't know if people actually use them. A wiki section (or a `README-snippets.md` on "Roll your own snippets" with samples could a good compromise.

**Comment by Dashed** [comment]
I'm going to vote in favour of moving snippets out. 

I have preference on something like `snippets.md`, which explains how to copy-paste snippets, and also where folks can PR against to add snippets to various 6to5 features (not just JSX). Something like what gulp does.

**Comment by zertosh** [comment]
Oh yeah, that is what Gulp does. Although it sounds like a cop out, showing users how to get down-and-dirty with snippets means that they can tweak them to their own style. I'd like another :+1: from another collaborator :smile:

**Comment by sebmck** [comment]
@zertosh I don't use snippets at all so I don't really have an opinion. Happy to create a new repo if necessary :stuck_out_tongue_winking_eye:

**Comment by zertosh** [comment]
Fixed by https://github.com/babel/babel-sublime/pull/43

**Comment by cesarandreu** [comment]
Thanks :D!!

**Comment by 0x80** [comment]
Noooo I was just getting used to the snippets! :) Creating them manually with the given instructions is a pain, so I placed them in a [repo](https://github.com/0x80/babel-sublime-snippets) again.

**Comment by zertosh** [comment]
@0x80 What I really wanted to do was have Sublime ignore the snippets, but AFIK there is no way for a package to selectively self-ignore a directory. But, there are two alternatives: I could ZIP up the snippets, or change their extension to something like `whatever.sublime-snippet.disabled`. Both would require some work on part of the user - but less so than copy/pasting. Do you think any of those options works for you?

**Comment by gpbl** [comment]
IMHO is a good idea to keep them in a separate repo, maybe available on package control :-)

**Comment by 0x80** [comment]
A zip would work for me, but maybe a repository makes sense. I would choose a zip over file renaming.

**Comment by zertosh** [comment]
What would a dedicated babel snippets package look like? Just React stuff seems a little odd.

**Comment by zertosh** [comment]
@sebmck can I haz a `babel-snippets` (or `babel-sublime-snippets`) repo?

**Comment by sebmck** [comment]
Tah dah https://github.com/babel/babel-sublime-snippets

**Comment by zertosh** [comment]
@sebmck thanks!

**Comment by jgebhardt** [comment]
FWIW, [sublime-react](https://github.com/reactjs/sublime-react) already provides the original snippets in a separate repo and works in combination with Babel.
