### ISSUE TITLE
Broken highlighting after double slashes inside a string containing unterminated parentheses

### ISSUE THREAD

**Issue by olofssonanton** [babel/babel-sublime#310]
In cases such as this it breaks completely, but even without the double slashes the parentheses are mismatched.
![screenshot from 2017-03-01 14-56-40](https://cloud.githubusercontent.com/assets/6662439/23462747/56b55514-fe8f-11e6-8152-32a29185cb1f.png)

`if (startsWith(testString, 'url("//')) {
  return 'Oh no! Broken highlighting!';
}`

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
