### ISSUE TITLE
Encoding isn't remembered

### ISSUE THREAD

**Issue by yarnball** [babel/babel-sublime#312]
Hi,

Great work on this.

I'm having an issue where whenever I quit sublime test, and re-open a babel file- it doesn't remember to show it in Babel. It reverts back to Javascript.

Is this a known bug?

**Comment by Thom1729** [comment]
In order to always open JavaScript files using the Babel syntax, choose View → Syntax → Open All With Current Extension As… → Babel → JavaScript (Babel).
