### ISSUE TITLE
Cannot transform js files that include jsx statements when use babel-sublime in ST 3

### ISSUE THREAD

**Issue by WeijianXu** [babel/babel-sublime#317]
I tried to use the babel-sublime to transform js files which include  jsx statements. But there were some errors happened. Then I reinstalled this plugin, the errors still happened.
![sublime-babel](https://cloud.githubusercontent.com/assets/18255852/24939007/1f472586-1f6d-11e7-842e-b56416dc3945.png)
My editor is ST 3 with babel-sublime. The opration is that click the "Babel Transform" of "Babel" in Tools tab. My environment is Windows 7, node 6.9.5.

**Comment by Thom1729** [comment]
babel-sublime does not offer any build systems or similar functionality, so this must be a problem with a third-party package.
