### ISSUE TITLE
Syntax highlighting for variables inside template strings

### ISSUE THREAD

**Issue by jericho1ne** [babel/babel-sublime#318]
Any way to have the `${API_BASE}` stick out in Sublime (eg: dollar sign and curly braces as a different color) in regular Javascript (*.js) files?  

I noticed that this template string highlighting is implemented in .jsx and .vue files, but that's most likely due to those respective plugins.  

![image](https://cloud.githubusercontent.com/assets/2898976/25022864/69546f14-204c-11e7-8512-2546e492fdfb.png)

**Comment by Xazzzi** [comment]
![image](https://cloud.githubusercontent.com/assets/1200201/26023699/d76f56b8-37ca-11e7-8889-fb7383f16d25.png)
It should be `JavaScript (Babel)`.

**Comment by AlexKvazos** [comment]
It is already implemented.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
