### ISSUE TITLE
after installing this package, sublime started using up 80% of cpu and became unusable

### ISSUE THREAD

**Issue by jmaher409** [babel/babel-sublime#32]
I was unable to get a screenshot of the memory usage because the machine locked up so I have uninstalled the package.

**Comment by zertosh** [comment]
I'm afraid that I need more information to go on than this. I'm using Sublime 3 Build 3069 on Yosemite 10.10.2 and it works perfectly fine - countless others have been using it w/o a problem.

**Comment by jmaher409** [comment]
No problem. Is it possible that it's a bad interaction with another package? I have the same OS and Sublime 3 build 3065. I can try 3069 later today to see if that resolves the problem.

**Comment by zertosh** [comment]
Any updates @jmaher409? I'd like to close out the issue if it's unrelated to `6to5-sublime`

**Comment by zertosh** [comment]
Closing this out due to irreproducibility.

**Comment by demircancelebi** [comment]
I have the same issue as well

**Comment by zertosh** [comment]
@demircancelebi Can you open a new issue with more detail on your particular case?
