### ISSUE TITLE
Update Package Control Version

### ISSUE THREAD

**Issue by philipbordallo** [babel/babel-sublime#320]
[Package Control](https://packagecontrol.io/packages/Babel) version is 8.6.3 while it seems the latest version is 9.0.0 and around 34 commits ahead.

**Comment by maticrivo** [comment]
any plans for a package control update?

**Comment by fritz-c** [comment]
@zertosh Do you have some reservations about the 9.0.0 release?

**Comment by SlashArash** [comment]
Any progress on this?

**Comment by Thom1729** [comment]
There's a new roadmap described in #379.

I'm not sure what the status is of the 9.0.0 release, but I suspect that the simplest way to move forward would be to skip it and release the changes described in the roadmap as 10.0.0. I'm planning to publish an alpha build this week.

**Comment by Thom1729** [comment]
Closing this issue now that v10.0.0-beta.1 is out.
