### ISSUE TITLE
Performance issues in files with huge comments

### ISSUE THREAD

**Issue by alexkuz** [babel/babel-sublime#321]
I noticed that `babel-sublime` has a problem parsing files with long comment lines. Here's the example file (the line is taken from `jsdiff` dist file):

https://gist.github.com/alexkuz/e4959343131e09c07eec0c2f93b81a06

`babel-sublime` parses this line in 5+ seconds, default js highlighting is doing fine.

I suspect this also could be a reason for sublime crashing while crawling in background (though I don't see why would sublime run the highlighter in that case, so it might be unrelated)

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by alexkuz** [comment]
@borela looks nice, thank you!

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
