### ISSUE TITLE
Package Control instructions are not detailed enough for novice users to install a package (was: Package not showing up)

### ISSUE THREAD

**Issue by arena** [babel/babel-sublime#327]
The instructions say the way to install this package is to search for it via Package Control. However, when I do that I can't find it. 

Why isn't it showing up?
Is there a workaround for installing it when the Package Control route doesn't work?

**Comment by arena** [comment]
Package Control is just not intuitive to use. I didn't realize that I couldn't just Browse Packages. Now I realize that I needed to use Install Package and then select Babel. I wish that was in the instructions.

Now I'm trying to figure out how to tell Sublime to always use it in my project. The files all end with .js not .jsx in the project I'm contributing to.

**Comment by arena** [comment]
To phrase this issue differently. The install instructions are not intuitive to somebody that is unfamiliar with using Package Control. Ideally, they would be simple for the novice user. Here is a suggestion.

**Install the Babel Package**
1. Make sure you have Sublime 3 installed by checking that the build number is "Build 3126" or higher.
2. From the top menu, select: **Sublime Text: Preferences: Package Control**
3. When the command prompt appears, type "**Install Package**" which will cause the prompt to display a list of packages (give it a 1/2 second of so to appear)
4. With the list of packages showing, type "**Babel**", select Babel and then hit return to install it.
Note: if you find yourself with the wrong package control console open, just hit Esc to make it disappear.
**Use the Babel Package**
5. In Sublime, open a .js or .jsx file
6. From the application menu, select **View: Syntax: Open all with current extension as... : Babel : JavaScript (Babel)**

**Comment by hiitsherby** [comment]
Works like charm. Thanks so much!!

**Comment by AnneTee** [comment]
The solution above and the one linked in #218 didn't work for me, so I did the following based on [this answer](https://stackoverflow.com/questions/31840550/cant-find-certain-package-in-package-control-install-package):

```
$ cd /Users/(username)/Library/Application\ Support/Sublime\ Text\ 2/Packages/  
$ git clone https://github.com/babel/babel-sublime
$ mv babel-sublime Babel
```

From here I could install the package.

**Comment by arena** [comment]
Oh, you closed it @ljharb -- did you update the instructions?

**Comment by ljharb** [comment]
Oops, i didn’t realize there was anything actionable here. My bad!

**Comment by wahidc7101** [comment]
Sublime wont give you a notice or an alert saying the package was installed successfully. However you look down all the way at the bottom of sublime it will tell you it was installed. 
Another way is to do the following:
1. go to sublime system :
2.preferences:
3.Package settings: and it will show you all the packages that you have. If babel shows up sucess

**Comment by kennblvnp** [comment]
Thank you! @AnneTee 

This comment works for me:
https://github.com/babel/babel-sublime/issues/327#issuecomment-330360848

**Comment by pranshu2610** [comment]
**Installing Babel from Sublime Text itself**

1. Open the Sublime Text and press Shift+Ctrl+P.
2. Type 'Package Control' and list will appear, select 'Package Control : Install Package'. After clicking it will take some time to install. 
3. Then after installation select 'Preferences' tab and select 'Browse Package'. In Browse Package type 'Babel' and select the first result 'Babel'. Your Babel will start downloading and restart your Editor after installation.
4. Go to View tab and select 'Syntax'
5. You'll now see an option named 'Babel' and hover cursor on it and in side options select JavaScript or JSON accordingly.

**Comment by gk9848970** [comment]
How to install it manually?

**Comment by ianshuman** [comment]
How can I install the beta-versions?

**Comment by Thom1729** [comment]
v10.0.0 is now out, so there's no need to install the beta manually anymore.
