### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by JemarJones** [babel/babel-sublime#328]
Currently there is a build of issues filed on this repo which have been left unaddressed. Along with this the last release seems to have been in January. Is this project maintained? And if not, perhaps new maintainers should be added?

**Comment by rattrayalex-stripe** [comment]
Does anyone know of a good alternative / fork?

**Comment by borela** [comment]
@rattrayalex-stripe https://github.com/borela/naomi

**Comment by Thom1729** [comment]
I am now helping to maintain babel-sublime. There is a new v10.0.0-beta.1 prerelease out with a completely rewritten syntax definition. See #379 for more information.

**Comment by rattrayalex-stripe** [comment]
Cool, congratulations @Thom1729 ! Excited to give it a try and take a look at how it handles various Flow/TS/JSX features.
Have been using `mgmcdermott.vscode-language-babel` in the meantime
