### ISSUE TITLE
Comments as regex in PHP

### ISSUE THREAD

**Issue by MKMatriX** [babel/babel-sublime#329]
```
<script type="text/javascript">
	// here I will put standart js
...
</script>

```
see "//" as regex in usual php files

![image](https://cloud.githubusercontent.com/assets/21899397/26437794/654c632c-4149-11e7-9f51-913c343fad9d.png)

**Comment by Thom1729** [comment]
This looks like an issue with the PHP syntax. Either way, I can't reproduce in the current release.
