### ISSUE TITLE
Adding JavaScript to the ignored packages on Sublime Text 3 throws an error

### ISSUE THREAD

**Issue by yahyazini** [babel/babel-sublime#336]
The readme file has JavaScript with an uppercase S, it needs to be lowercased: Javascript.

**Comment by laistomazz** [comment]
Does it work if you use it lowercased?
For me it only works if I type "JavaScript", but then it shows an error.

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi there will be no need to the disable the core package + it supports many stage-0 features.
