### ISSUE TITLE
support JSX elements as attribute values 

### ISSUE THREAD

**Issue by kedromelon** [babel/babel-sublime#338]
https://github.com/babel/babel/issues/6004 was closed via https://github.com/babel/babel/issues/6006, but this syntax is not yet supported by this plugin

ex: 
```jsx
<div attr=<div /> />
```

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
