### ISSUE TITLE
Make "set syntax: babel" default?

### ISSUE THREAD

**Issue by ckim16** [babel/babel-sublime#339]
Hi all,

Thank you for the cool package first of all.

I was wondering, though, that if there is a way to keep `set syntax: babel` on so that I don't have to do `View -> Syntax -> Babel -> JavaScript(Babel)` for every single file?

Please let me know and thank you again!

**Comment by AlexKvazos** [comment]
When choosing a language, be sure to select this option first

<img width="387" alt="screen shot 2017-08-30 at 10 27 57 pm" src="https://user-images.githubusercontent.com/4448627/29905149-87978314-8dd2-11e7-8465-822f5d61b2f9.png">
