### ISSUE TITLE
Incorrect Highlighting for arrow functions with destructured parameters split in multiple lines

### ISSUE THREAD

**Issue by abenitesDC** [babel/babel-sublime#340]
Destructuring function variables in mutiple lines is not highlighted correctly when using arrow functions. (see image)
Using Javascript (Babel) in Sublime Text 3 build 3126.

![image](https://user-images.githubusercontent.com/13840240/29884510-bea5a422-8d81-11e7-9b27-1f48e5e72414.png)

**Comment by ewendel** [comment]
Anyone got a fix for this? I suppose it would be possible to just edit the language definition files to get a quick fix

**Comment by rattrayalex-stripe** [comment]
@ewendel give it a shot! 😉

**Comment by borela** [comment]
This is a limitation in sublime's regex engine, it can only see one line at a time, in my [syntax](https://github.com/borela/naomi/issues/25), I added a fallback where if it sees a `=>` it will still highlight the function body but the parameters will not have the correct scopes.

While this is not ideal, it helps while support for multi line regexes is not implemented https://github.com/SublimeTextIssues/Core/issues/1693

**Comment by Thom1729** [comment]
A near-future version of Sublime will provide new features that will allow us to address this. I'll leave this issue open in the mean time.

**Comment by dsl101** [comment]
It's now the near future. Any news on this one?

**Comment by Thom1729** [comment]
The new Sublime version is in beta. The latest version of the core JavaScript package fixes this issue, and there's also a core JSX syntax (using the same implementation as the dev version of babel-sublime). In fact, the core JSX syntax is extremely similar to babel-sublime (though lacking Flow types and Styled Components) and would probably work very well as a substitute in the short term. In the medium term, I'll put out a new version of babel-sublime for the Sublime beta.

**Comment by Thom1729** [comment]
Fixed in the v11 beta. If you're running ST4, you can try the beta by specifying `"install_prereleases": ["Babel"]` in your Package Control settings. The stable release should be out soon.

**Comment by dsl101** [comment]
I just set about trying to do this, but it seems ST4 build 4106 already has this fix. :) However, something else broke :( The arrow function isn't scoped as a function now:

![image](https://user-images.githubusercontent.com/900542/118873301-7e3cd380-b8e1-11eb-8f08-cf246ab181dc.png)

I tried adding `"install_prereleases": ["Babel"]` and restarting ST4, but nothing changed. The output for `badHighlight` from scope hunter shows this:

Scope:
```
  source.js meta.binding.name.js variable.other.readwrite.js
```
Scope context backtrace:
```
  main
  expect-semicolon
  variable-binding-list-top
  initializer
  anonymous context 79
  literal-variable
```

**Comment by Thom1729** [comment]
Yeah, the variable name still won't be marked as a function name. That's actually implemented separately from arrow function detection. The current implementation is a regexp lookahead, which won't work in all cases. In principle, it could be made to work in all cases using branching, but I haven't hit upon the right implementation to avoid complexity and performance issues.

**Comment by Thom1729** [comment]
Fixed in v11.
