### ISSUE TITLE
Syntax highlighting error when regular expression contains "/"

### ISSUE THREAD

**Issue by Kannnnng** [babel/babel-sublime#342]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/22359680/31495300-b21109ec-af1c-11e7-8222-931d54311a7d.png)

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
