### ISSUE TITLE
I can't use the constant variable on sublime text 3- Windows

### ISSUE THREAD

**Issue by KIngsleyOkb** [babel/babel-sublime#345]
I have downloaded  "babel" from my package Control and still, I can't get rid of the Error assigned to the constant variable- cont 
I am using JavaScript, what should I do?

**Comment by Thom1729** [comment]
I'm closing this issue because it's not clear what the problem is. If you're still having a problem with babel-sublime, please reopen the issue and add more detail, including example code.
