### ISSUE TITLE
Support styled-components "Extended Styles"

### ISSUE THREAD

**Issue by ziyafenn** [babel/babel-sublime#346]
When using [styled-components's style extensions](https://www.styled-components.com/docs/basics#extending-styles), everything that comes after `Comp.extend` is seen as a multiline text and would be great if it will be supported as well.

Here is an example:
![screenshot 2017-11-28 10 43 05](https://user-images.githubusercontent.com/314302/33312877-5bd98220-d429-11e7-9f1d-40d2622be5a2.png)

**Comment by ziyafenn** [comment]
Same problem exists when attaching [Additional Props](https://www.styled-components.com/docs/basics#attaching-additional-props)  

![screenshot 2017-11-28 11 00 19](https://user-images.githubusercontent.com/314302/33313635-894b6bf4-d42b-11e7-84d7-594eabe1cedd.png)

**Comment by borela** [comment]
Try https://github.com/borela/naomi added styled components some days ago.

**Comment by Thom1729** [comment]
As of v11 (and probably v10 as well, though I haven't checked), `styled.div.attrs({})` works. The `Foo.extend` method has since been deprecated by Styled Components in favor of `styled(Foo)`, which also works in v11.
