### ISSUE TITLE
Highlighter breaks on regex inside of parentheses

### ISSUE THREAD

**Issue by Janpot** [babel/babel-sublime#349]
The highlighter breaks when regex `/\){/` is used inside of parentheses:

![screen shot 2018-01-12 at 11 15 46](https://user-images.githubusercontent.com/2109932/34870384-33cb6116-f78a-11e7-9ff2-bcc234059abf.png)

Outside of parentheses, this is not a problem:

![screen shot 2018-01-12 at 11 18 19](https://user-images.githubusercontent.com/2109932/34870448-6040821c-f78a-11e7-98ca-36d1209d1fff.png)

**Comment by borela** [comment]
This syntax is not being maintained, try FJSX15 https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
