### ISSUE TITLE
Indenting doesn't indent to the correct level

### ISSUE THREAD

**Issue by garyking** [babel/babel-sublime#353]
When using the `JavaScript (Babel)` syntax, and I have the following code:

```javascript
if (a) {
  if (b) {
    c

    d
  }
}
```

If I go to the line between `c` and `d`, and I hit `Tab`, then it only indents one level, rather than two as expected, such as it does in the `Python` syntax.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
