### ISSUE TITLE
Highlighting breaks with Flow without semicolon line-endings

### ISSUE THREAD

**Issue by ryami333** [babel/babel-sublime#354]
Highlight seems to break when you declare a type without a line-ending semicolon. Eg.
See first three lines, Flow defs without semicolons:
<img width="479" alt="screen shot 2018-03-15 at 9 51 13 am" src="https://user-images.githubusercontent.com/12481532/37430246-738a09d8-2836-11e8-8b50-d8ab91672b20.png">

After adding semicolons to those lines, everything OK again:
<img width="468" alt="screen shot 2018-03-15 at 9 51 23 am" src="https://user-images.githubusercontent.com/12481532/37430247-74c4daf8-2836-11e8-8e4e-3f80396d5980.png">

**Comment by STRML** [comment]
Can confirm, this one has been bothersome for a while.

**Comment by borela** [comment]
Alternative https://github.com/borela/naomi

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
