### ISSUE TITLE
html autocomplete with sublime?

### ISSUE THREAD

**Issue by danielzzz** [babel/babel-sublime#357]
hi, sorry if this is a wrong place, but I miss the  html autocomplete within render() for jsx files in sublime 3 with emmet.

is it something that depends on this package? 
if so, is there any way to enable this?

thanks, cheers, dan

**Comment by Thom1729** [comment]
This package provides syntax highlighting, and complex autocompletion is most likely out of scope. If I've misunderstood the question, then please feel free to reopen and comment in more detail.
