### ISSUE TITLE
Anonymous Classes Coloration

### ISSUE THREAD

**Issue by titouandk** [babel/babel-sublime#359]
It seems a coloration glitch happens on anonymous classes.
The first method of the class is not colored.

![bug](https://user-images.githubusercontent.com/5413308/40127713-524cb826-5930-11e8-9307-b4f705142664.jpg)

**Comment by Thom1729** [comment]
I'm planning to overhaul the syntax over the next couple of months (#355). Until then, I recommend trying out [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom), which extends the core JavaScript syntax. It will handle this case correctly.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
