### ISSUE TITLE
Unexpected token = on first function in a class

### ISSUE THREAD

**Issue by Frexuz** [babel/babel-sublime#363]
Why is it complaining on the `=`? :)
![screen shot 2018-08-10 at 01 02 07](https://user-images.githubusercontent.com/49692/43914002-2fef0526-9c39-11e8-850e-15b78a653038.png)

The 2nd function in the class is always fine:
![screen shot 2018-08-10 at 01 03 34](https://user-images.githubusercontent.com/49692/43914031-44f14e20-9c39-11e8-8844-17280e2e81f0.png)

**Comment by pzehle** [comment]
I have the exact same problem, I don't know how to fix it. Any workaround on this?

**Comment by mrgeorge3dy** [comment]
+1

**Comment by Thom1729** [comment]
This problem seems to concern a third-party linter, not babel-sublime itself, so I'm closing this issue.
