### ISSUE TITLE
Support comments for sytled-components

### ISSUE THREAD

**Issue by dantehemerson** [babel/babel-sublime#364]
Currently the comments within the styled-components looks like this
![Using babel-sublime inside JSX](http://i.imgur.com/ha4PTvN.png)

You could improve this to make it look like:
![Only SCSS](http://i.imgur.com/Q94EQg8.png)

**Comment by Thom1729** [comment]
I've completely rewritten the Styled Components highlighting in v11.1.0-beta.1.

**Comment by Thom1729** [comment]
Fixed in v11.1.0.
