### ISSUE TITLE
Several scope names per pattern

### ISSUE THREAD

**Issue by pchaigno** [babel/babel-sublime#365]
Some of the patterns in the grammar file have several scope names:
https://github.com/babel/babel-sublime/blob/a9a908fe1d39ec84893e6edcbb146f09e9e60cc6/JavaScript%20(Babel).YAML-tmLanguage#L1270-L1275

I don't know whether this works in Sublime Text, but when using this grammar to highlight files on GitHub.com (cf. github/linguist#4223), it causes HTML highlighting to break inside JSX files, as shown in [this Ligthshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fgithub-linguist%2Fbabel-sublime%2Fblob%2Fmaster%2FJavaScript%2520%28Babel%29.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2Fmaster%2Fsamples%2FJSX%2Fsample.jsx&code=).

**Comment by Thom1729** [comment]
Can you provide more context on how you are using babel-sublime outside Sublime? I am currently working on a complete replacement of the syntax definition with a new `.sublime-syntax`, and this will probably not be compatible with tools other than Sublime.

**Comment by pchaigno** [comment]
We use a fork of babel-sublime in [Linguist](https://github.com/github/linguist) to highlight JSX code on GitHub.com (cf. github/linguist#4223). Linguist doesn't support `.sublime-syntax` unfortunately (cf. github/linguist#3214).

**Comment by Thom1729** [comment]
Unfortunately, I don't think it will be practical to maintain the old tmLanguage definition going forward. It's very badly out of date, and `.sublime-syntax` is capable of providing much better highlighting. If Linguist is using a fork, then it probably makes the most sense to maintain that fork to serve Linguist's needs without worrying about divergence from babel-sublime.
