### ISSUE TITLE
A `<dom-tag>` inside a string

### ISSUE THREAD

**Issue by brianmhunt** [babel/babel-sublime#367]
I didn't see this issue already, so I thought to report syntax issues with this sample code:

```jsx
   throw new Error('<async-button> needs a function-`action`')
```

(the relevant bit is the string, but I've copied it to mirror the screenshot)

![image](https://user-images.githubusercontent.com/135528/53496302-c6a51800-3a6f-11e9-937c-77b6146810a8.png)

It appears that `<async-button>` is highlighted (even though it's inside a string, and more problematic is that this seems to mess up all syntax highlighting following this string.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
