### ISSUE TITLE
Shorthand JSX Fragments breaks syntax highlighting

### ISSUE THREAD

**Issue by Svish** [babel/babel-sublime#368]
The shorthand version of writing react jsx fragments breaks all the syntax highlighting after its closing tag:

![capture](https://user-images.githubusercontent.com/142162/53600951-323fd000-3bab-11e9-825c-40576050cda6.PNG)

😟

**Comment by simonpai** [comment]
The last commit of this project was in May 2018. 
You can try either [Naomi](https://github.com/borela/naomi) or [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) as an alternative.

**Comment by fedecarg** [comment]
For feature reference, the extension that break JSX in VSCode is: `Babel ES6/ES7`. It's promoted in the Marketplace as the oficial Babel extension, but it's not.

dzannotti/vscode-babel#23

**Comment by scottmartin-ln** [comment]
The bug is triggered by the opening tag; changing `<>` to `<x>` will restore syntax highlighting to the code outside the fragment.

**Comment by IanIsFluent** [comment]
> The bug is triggered by the opening tag; changing `<>` to `<x>` will restore syntax highlighting to the code outside the fragment.

But. That's invalid? How is that a solution!?

**Comment by scott-ln** [comment]
No no, you misunderstand! I was just describing exactly how to trigger the bug.

**Comment by IanIsFluent** [comment]
> No no, you misunderstand! I was just describing exactly how to trigger the bug.

Sorry! I think the party popper reactions suggested this was a solution, not so much the wording of your comment! 😆

**Comment by icharge** [comment]
![image](https://user-images.githubusercontent.com/1619007/71191760-a58d0c80-22b9-11ea-95da-23f09fe3e106.png)
Set TypeScript React for *.js  it worked

**Comment by icharge** [comment]
> ![image](https://user-images.githubusercontent.com/1619007/71191760-a58d0c80-22b9-11ea-95da-23f09fe3e106.png)
> Set TypeScript React for *.js or *.jsx it worked

This way will product warnings about typing. So better way than this is add comment slashes after `</>`  

Before:

![image](https://user-images.githubusercontent.com/1619007/71897037-ee810400-3187-11ea-978d-63b18dd67f2a.png)

After:

![image](https://user-images.githubusercontent.com/1619007/71897089-1bcdb200-3188-11ea-86f4-8b7f8ec64848.png)

Hope this will help.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.

**Comment by IPWright83** [comment]
@Thom1729 how do you go about installing a beta package to test this?

**Comment by Thom1729** [comment]
You have to tell Package Control to install prerelease versions of Babel:

1. Run `Preferences: Package Control Settings — User` from the command palette to open your Package Control settings.
2. Add `install_prereleases: ['Babel']`. (If you already had `install_prereleases`, add Babel to the list.)
3. Run `Package Control: Upgrade Package` and select `Babel`, or just wait for the next time Package Control checks for new package versions.

**Comment by jrandyanderson** [comment]
@Thom1729 This worked for me! Thank you.

**Comment by MKorostoff** [comment]
@Thom1729  this worked for me! thanks!

**Comment by williampratt** [comment]
Sorry for commenting on a closed issue, but any time frame for a new release to include fixes like this so we don't have to always update to pre-release? Thanks for the solution though @Thom1729!

**Comment by sshadmand** [comment]
![Screen Shot 2020-07-13 at 6 09 46 PM](https://user-images.githubusercontent.com/68735/87368963-28b2d000-c534-11ea-9d59-94777e30910f.png)
![Uploading Screen Shot 2020-07-13 at 6.09.32 PM.png…]()

**Comment by williampratt** [comment]
Go to Preferences -> Package Settings -> Package Control -> Settings - User and add the following:

`	"install_prereleases":
	[
		"Babel"
	],`

Then Tools -> Command Palette -> Package Control: Upgrade Package

That should do it!

**Comment by sshadmand** [comment]
Thanks for the steps. Was able to follow along to get this:

<img width="528" alt="Screen Shot 2020-07-14 at 6 06 00 PM" src="https://user-images.githubusercontent.com/68735/87491322-b22dd500-c5fc-11ea-948e-f91fda609f4b.png">
<img width="872" alt="Screen Shot 2020-07-14 at 6 05 51 PM" src="https://user-images.githubusercontent.com/68735/87491325-b4902f00-c5fc-11ea-9892-3131deb3d851.png">


🤔  but still get an "unexpected token" error on the line with the shorthand. 

<img width="327" alt="Screen Shot 2020-07-14 at 6 04 58 PM" src="https://user-images.githubusercontent.com/68735/87491280-97f3f700-c5fc-11ea-9e34-a33390052eac.png">

**Comment by sshadmand** [comment]
<img width="872" alt="Screen Shot 2020-07-14 at 6 05 51 PM" src="https://user-images.githubusercontent.com/68735/87491569-5c0d6180-c5fd-11ea-9383-05f5de6983ca.png">

<img width="528" alt="Screen Shot 2020-07-14 at 6 06 00 PM" src="https://user-images.githubusercontent.com/68735/87491578-60397f00-c5fd-11ea-9aa5-1c8930d76ffc.png">

<img width="327" alt="Screen Shot 2020-07-14 at 6 04 58 PM" src="https://user-images.githubusercontent.com/68735/87491580-60397f00-c5fd-11ea-8478-4285df020e21.png">

<img width="322" alt="Screen Shot 2020-07-14 at 6 11 21 PM" src="https://user-images.githubusercontent.com/68735/87491610-721b2200-c5fd-11ea-96e4-45056748aad8.png">

**Comment by williampratt** [comment]
What version do you see when you run Package Control: List Packages? I am not seeing the issue in v 10.0.0-beta.2

<img width="597" alt="babel" src="https://user-images.githubusercontent.com/94806/87620829-2ba0f280-c6e5-11ea-9645-d8fd859af08b.png">

**Comment by woonketwong** [comment]
The step works for me.

**Comment by larrymoe** [comment]
Worked for me. Thanks @williampratt
