### ISSUE TITLE
Package missing in Package Control list

### ISSUE THREAD

**Issue by arzatskis** [babel/babel-sublime#37]
Wasn't following this repo, but this is probably due to renaming GitHub org

![](https://dl.dropboxusercontent.com/spa/zfzkcxbd46m4ot2/en9emkba.png)

![](https://dl.dropboxusercontent.com/spa/zfzkcxbd46m4ot2/3s89kzbz.png)

**Comment by sebmck** [comment]
Damn, I've moved this repo temporarily to the old org. Feel free to move it back once everything's sorted @zertosh, you should have access.

**Comment by zertosh** [comment]
Thanks @arzatskis, It's all sorted out now under the new name. 

![babel-install-package](https://cloud.githubusercontent.com/assets/830952/6205103/7ed7e200-b530-11e4-9e16-e6781c9d2bc6.jpg)
