### ISSUE TITLE
Gulpfile.js comment highlight bug

### ISSUE THREAD

**Issue by vovka93** [babel/babel-sublime#370]
![image](https://user-images.githubusercontent.com/3983526/59179211-fd5bf580-8b69-11e9-8c94-eaad8c042c09.png)
The situation occurs when the javascript and vintage packages is disabled

**Comment by Thom1729** [comment]
It looks like you're using a syntax called “JavaScript (Gulpfile)” that is not part of babel-sublime. Therefore, I'm closing this issue as unrelated. If the problem occurs with the “JavaScript (Babel)” syntax, please feel free to reopen and post a sample.
