### ISSUE TITLE
Indentation for new lines is incorrect in JSX

### ISSUE THREAD

**Issue by adamwathan** [babel/babel-sublime#373]
Hey folks! I noticed when hitting enter at the end of a line of JSX that my cursor is in the wrong place on the new line:

![Screen Recording 2019-08-16 at 8 20 18 AM](https://user-images.githubusercontent.com/4323180/63167285-d6ed8700-bffe-11e9-93c2-9a2905fbab26.gif)

The cursor moves to the same indentation as the previous line instead of the correct indentation for a new line. Happy to try and fix this myself if someone could point me in the right direction.

Thanks!

**Comment by Thom1729** [comment]
I can't reproduce in v10.0.2. Is this still an issue?

**Comment by Thom1729** [comment]
Please reopen if you can reproduce in v10.
