### ISSUE TITLE
Syntax Highlighting for Unnamed Class Expressions

### ISSUE THREAD

**Issue by jarrodchung-dev** [babel/babel-sublime#375]
It seems to work for name class expressions but not unnamed class expressions.

![image](https://user-images.githubusercontent.com/53537663/70602324-2402f380-1bc2-11ea-8a9b-1f3f27eea265.png)

Is there a quick workaround for this?

Thanks!

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
