### ISSUE TITLE
trying to use the json babel syntax with json file (Help)

### ISSUE THREAD

**Issue by gonzalohp96** [babel/babel-sublime#376]
As said, i have changed js file to use the babel javascript syntax by default following the steps indicated in the guide. But when doing that to json files (especifically, "JSON(NPM)" files) the setting isnt saved. I really like the color that json babel gives to json files so i would like to use it as a default, but cant find the way to saved that config.
Hope someone can help me with this

**Comment by yogevHenig** [comment]
Hi, im facing the same issue.. did you figure that out? thanks
