### ISSUE TITLE
Syntax Highlighting Not Recognized 

### ISSUE THREAD

**Issue by jarrodchung-dev** [babel/babel-sublime#377]
<img width="292" alt="Screenshot 2019-12-24 23 04 32" src="https://user-images.githubusercontent.com/53537663/71431726-caaac200-26a1-11ea-93ef-29ab0ac1216b.png">

There seems to be a conflicting scope when it comes to using a single open-parentheses within a string of a method call but does not continue to show to the same issue with a closing parentheses are if additional characters follow. Is there a fix that can be implemented here or a scope that I can alter in my Sublime's repository that will fix this?

**Comment by ljharb** [comment]
You’re not returning anything there and strings are immutable - it should still highlight correctly, of course.

**Comment by jarrodchung-dev** [comment]
Hey! Thanks for getting back on this so soon. I thought that this could show a better example of the syntax highlighting issue.

<img width="369" alt="Screenshot 2019-12-24 23 16 29" src="https://user-images.githubusercontent.com/53537663/71431908-7274bf80-26a3-11ea-942c-1b4c4cd8fe2f.png">

**Comment by ljharb** [comment]
(You’d need a `return` in front of that for the function to make sense)

**Comment by jarrodchung-dev** [comment]
> (You’d need a `return` in front of that for the function to make sense)

Right, I do realize that but followed up with a clarifying example showing the exact same issue with the syntax highlighting where the open parentheses enclosed in quotes is not being recognized as a string.

**Comment by Thom1729** [comment]
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.
