### ISSUE TITLE
No indentation for nested brackets (for beta v10)

### ISSUE THREAD

**Issue by jarrodchung-dev** [babel/babel-sublime#380]
![no-indent](https://user-images.githubusercontent.com/53537663/72741711-320b4300-3b76-11ea-972e-df6e59007594.gif)

I upgraded to the new syntax beta and am not able to find the setting that indents for nested brackets.

Which setting can I edit to allow this?

**Comment by simov** [comment]
I think this have something to do with the missing indentation definitions:

- https://github.com/babel/babel-sublime/blob/v8.6.3/JavaScript%20Indent.YAML-tmPreferences
- https://github.com/babel/babel-sublime/blob/v8.6.3/JavaScript%20Indent.tmPreferences

Indentation is totally messed up on my end as well. /cc @Thom1729

**Comment by Thom1729** [comment]
@simov Are you on 10.0.1? I copied the indentation rules from the core JavaScript package so that they'd work for users who'd disabled the core package.

**Comment by simov** [comment]
Not sure but I just figured this was the case. I have removed the default snippets from the JavaScript package but I forgot to zip it back as `.sublime-package` and Sublime was ignoring it. I noticed that it was missing from the list of available syntax definitions.

Seems to be working on my end now.

**Comment by jarrodchung-dev** [comment]
https://user-images.githubusercontent.com/53537663/114634191-0818d180-9c90-11eb-8ea7-65d405175378.mov

Thought I'd add additional closure by showing that it looks good for me as well.

**Comment by Thom1729** [comment]
Thanks. I'll close this issue, then.
