### ISSUE TITLE
Is there a way to use with Svelte and HTML <script> syntax?

### ISSUE THREAD

**Issue by Sawtaytoes** [babel/babel-sublime#385]
I'd like to use babel-sublime with `.svelte` files; although, I'm pretty sure they're using HTML syntax highlighting behind the scenes.

Is there a way to swap out the JavaScript syntax highlighting in the `<script>` tags of HTML to use `babel-sublime` instead?

Unlike the default and Naomi syntax highlighting schemes for JavaScript, babel-sublime is the only one compatible with [Colorcoder](https://github.com/vprimachenko/Sublime-Colorcoder).

**Comment by A-312** [comment]
(I'm not sure) You should try to find `source.js` and replace by `source.jsx` in your HTML syntax file

Line should be somthing like `embed: scope:source.js`
