### ISSUE TITLE
Syntax highlighting is broken for React fragment closing tags

### ISSUE THREAD

**Issue by estradanic** [babel/babel-sublime#387]
When writing React fragments like this:
`<>
    Fragment here
</>
Rest of page`

everything after the closing tag `</>`, in the "Rest of page" section is treated like a literal regex until it finds another '/' character.

![download](https://user-images.githubusercontent.com/16547547/85343447-ba816d00-b4a1-11ea-8d57-ab792710117d.png)

**Comment by pioug** [comment]
I faced the exact same issue. It seems to be fixed already in a pre-release version of the plugin. See https://github.com/babel/babel-sublime/issues/379, and more precisely: https://github.com/babel/babel-sublime/issues/379#issuecomment-576048073:
> You can start using it by adding install_prereleases: ['Babel'] to your Package Control settings.

**Comment by muya** [comment]
Just in case you're wondering where to find "Package Control" settings

<img width="1653" alt="sublime-package-control-settings" src="https://user-images.githubusercontent.com/1861055/89166452-be191100-d582-11ea-9646-b8a2ab855812.png">


Add "Babel" to the `install_prereleases ` settings:
<img width="498" alt="sublime-package-control-settings-2" src="https://user-images.githubusercontent.com/1861055/89166575-edc81900-d582-11ea-8901-5f12df849bd6.png">


Finally, update the 'Babel' Package to have it update to the pre-release version

![st3-upgrade-package](https://user-images.githubusercontent.com/1861055/89166991-83fc3f00-d583-11ea-86da-67e7a228b3f0.gif)


(The GIF says no packages to upgrade coz I'd already upgraded Babel)

**Comment by consciousnessdev** [comment]
> 
> 
> Just in case you're wondering where to find "Package Control" settings
> 
> <img alt="sublime-package-control-settings" width="1653" src="https://user-images.githubusercontent.com/1861055/89166452-be191100-d582-11ea-9646-b8a2ab855812.png">
> 
> Add "Babel" to the `install_prereleases ` settings:
> <img alt="sublime-package-control-settings-2" width="498" src="https://user-images.githubusercontent.com/1861055/89166575-edc81900-d582-11ea-8901-5f12df849bd6.png">
> 
> Finally, update the 'Babel' Package to have it update to the pre-release version
> 
> ![st3-upgrade-package](https://user-images.githubusercontent.com/1861055/89166991-83fc3f00-d583-11ea-86da-67e7a228b3f0.gif)
> 
> (The GIF says no packages to upgrade coz I'd already upgraded Babel)

Thanks! it solved :smiley:

**Comment by Thom1729** [comment]
Fixed in v10.0.0.
