### ISSUE TITLE
Impossible to use shortcut to comment Javascript lines (beta version)

### ISSUE THREAD

**Issue by pioug** [babel/babel-sublime#388]
I am using the pre-release (https://github.com/babel/babel-sublime/issues/379) and it seems like I can't comment line(s) in JavaScript files via the shortcut `Command ⌘ + /`.

**Comment by cbeley** [comment]
I'm experiencing the same issue on Linux.

FYI, Naomi likely doesn't have this issue, but it breaks the markdown plugin (and Naomi also seems to not be very maintained anymore).

**Comment by Thom1729** [comment]
@pioug Can you post a concrete example? Commenting works for me, but I might be looking at something different from you.

Have you disabled the core JavaScript package by any chance? The readme suggest that, but babel-sublime doesn't actually provide its own copy of the commenting rules. I decided to remove that suggestion for the next version.

**Comment by pioug** [comment]
I am closing the issue. I don't remember what were the conditions. I moved to ST4 and stopped babel-sublime at that time 😶 I'll check out again when you release the stable version! Thanks!
