### ISSUE TITLE
sublimeLinter-jshint disables when syntax is set to Javascript (Babel)

### ISSUE THREAD

**Issue by robmcguinness** [babel/babel-sublime#39]
Might be related to https://github.com/SublimeLinter/SublimeLinter-jshint/pull/28

**Comment by zertosh** [comment]
jshint doesn't support jsx, so adding support for babel in SublimeLinter-jshint would cause a ton of problems for users that do develop jsx. If you need to lint with jshint then you can use  https://github.com/SublimeLinter/SublimeLinter-jsxhint which already works with babel. Another alternative is to use eslint, which does support jsx, and bebel already has support in https://github.com/roadhump/SublimeLinter-eslint.

**Comment by robmcguinness** [comment]
ah i was missing the jsxhint linter...thanks for the help much obliged.
