### ISSUE TITLE
<></> breaks syntax highlighting

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [babel/babel-sublime#391]
React offers the possibility to write 

```jsx
<>
  .. code
</>
```

Which breaks the syntax highlighting... :(

**Comment by kevinleguillou** [comment]
It was supposed to be fixed on #348 
I've switched to https://github.com/borela/naomi for now as some suggested in the comments, and it works well with React and JSX fragments.

**Comment by fcrezza** [comment]
If you only want syntax highlighting feature from naomi, but don't want to include other naomi features such as color scheme, you can use a package named [naomi-syntax](https://packagecontrol.io/packages/naomi-syntax)

**Comment by Oleg2tor** [comment]
https://github.com/babel/babel-sublime/issues/379#issuecomment-576048073
This fixes the issue

**Comment by Fox4148** [comment]
#https://github.com/babel/babel/issues/12720

**Comment by Thom1729** [comment]
Fixed in v10.0.0.
