### ISSUE TITLE
Can't find Babel in Package Control when using Alpha Build of Sublime Text 4

### ISSUE THREAD

**Issue by ivan-denysov** [babel/babel-sublime#392]

**Comment by JLHwung** [comment]
This package current only supports ST3, PR is welcome for ST4 support.

**Comment by ivan-denysov** [comment]
Are there any known blockers or could it be as easy as lifting some version restriction? 🙂

**Comment by Thom1729** [comment]
I just tested on build 4094 and there was no problem. Babel appeared in the list and installed correctly.

I also checked the [channel repository](https://github.com/wbond/package_control_channel/blob/master/repository/b.json) to be sure, and the only restriction is `"sublime_text": ">=3000"`, which includes ST4. In addition, as far as I know there is no reason that any part of the package should not be fully future-compatible.

Can anyone reproduce this?

**Comment by Thom1729** [comment]
I'm going to close the issue, as it seems it can't be reproduced.
