### ISSUE TITLE
Template literal operators lost syntax highlighting in v10

### ISSUE THREAD

**Issue by simov** [babel/babel-sublime#397]
![template-literal](https://user-images.githubusercontent.com/1694112/114311084-fc91a300-9af5-11eb-8a4b-38db42a6149f.png)

As you can see the backticks and the expression operator inside the template literal is not red like the assignment operator.

Might be something on my end, but that worked before updating to v10 today. So any pointers would be helpful.

**Comment by Thom1729** [comment]
This is working as intended. The new release is derived from the core syntax and uses the same scopes, including the standard scopes for interpolations in strings.

If you prefer the way the old scopes looked, you can target `punctuation.section.interpolation` in your color scheme.

**Comment by simov** [comment]
Thanks, that worked for the expression, but not for the backticks:

![template-literal-expr](https://user-images.githubusercontent.com/1694112/114312717-52694980-9afc-11eb-8d24-4edc455d8bbe.png)

Can you point to the place where I can find all scopes available .. even though I have a custom theme I can't remember.

**Comment by simov** [comment]
Found it, it's in the syntax obviously, and now I see that the template literal uses the same scope as string, which makes sense.

Not an issue for me, thanks for the help :+1:
