### ISSUE TITLE
Comment Toggle no longer works in .js and no longer works correctly in .vue

### ISSUE THREAD

**Issue by tbtalbottjr** [babel/babel-sublime#399]
Sublime Text 3: 3.2.2 build 3211
Babel-sublime: 10.0.0

I've been using this package for VueJs development to edit Javascript (.js) and single file component (.vue) files. Up until the forced 10.0.0 update, it has worked sublime. :)

Today .js files stopped allowing me to toggle comments and commenting within a .vue file only does an html comment and does not honor the sections (template,script,style). This is a huge setback for me. Is there a way to roll back to a previous version?

Just to follow up: 

This package is recommended here: https://github.com/vuejs/vue-syntax-highlight/tree/new#enabling-jsx-highlighting 

I have removed Babel from Sublime Text and re-enabled the standard Javascript syntax package. Commenting now works again, but I have lost JSX highlighting.

**Comment by Thom1729** [comment]
Is the core JavaScript package disabled?

Can you post a list of the packages you have installed?

The new version doesn't specify comment rules for basic JavaScript, but the old version didn't either. I'm not sure why it would have changed. There was another report of a similar issue, but it turned out to be (apparently) unrelated to the release. If it is related to the release, I do have a fix in mind and I can push it out this afternoon.

**Comment by tbtalbottjr** [comment]
I added the below to the description while you were asking:

This package is recommended here: https://github.com/vuejs/vue-syntax-highlight/tree/new#enabling-jsx-highlighting

I have removed Babel from Sublime Text and re-enabled the standard Javascript syntax package. Commenting now works again, but I have lost JSX highlighting.

**Comment by tbtalbottjr** [comment]
Is there an easy way to get a list of packages?

**Comment by Thom1729** [comment]
Ah; from your edit it sounds like the core JavaScript package was disabled. I would expect commenting to break if the core package is disabled, but I would also expect it to have broken under the old version. Nevertheless, the old readme suggested disabling the core package for some reason. I updated the readme, but there are surely more people running with it disabled.

I'm just going to copy the commenting/symbol/etc files from the core package and push out a bugfix release. That should solve the problem for everyone.

N.B. in the mean time everything should work fine if Babel is installed but the core package is not disabled.

**Comment by tbtalbottjr** [comment]
OK. Thanks. I will give that a try

**Comment by Thom1729** [comment]
Also — if you have the core package disabled, won't regular expression highlighting break?

**Comment by Thom1729** [comment]
v10.0.1 is out, bundling the core JavaScript support files. (It might take an hour or two to trickle out through Package Control.) Please let me know if this does not solve the problem.

**Comment by tbtalbottjr** [comment]
> Also — if you have the core package disabled, won't regular expression highlighting break?

I had not noticed that.

**Comment by Thom1729** [comment]
Eh. I bundled everything JavaScript-related into the new release just to be sure. (In ST3, JSON highlighting will still break if you disable the JavaScript package. In ST4, JSON has been moved out into its own core package, so it would work when the JavaScript package is disabled.)

**Comment by tbtalbottjr** [comment]
With 10.0.0 and core Javascript enabled, I have commenting back again. 

Unfortunately, it disables the JSX highlighting within a .vue file, which is why the readme for the vue-syntax-highlighting says to disable it.

Hopefully, 10.0.1 will fix the problem.

**Comment by tbtalbottjr** [comment]
Just got 10.0.1. Looks good so far with core Javascript disabled.

Thanks for the quick turnaround. 

Closing...
