### ISSUE TITLE
Syntax highlighting with braces broken in JSX with latest 10.x.x updates

### ISSUE THREAD

**Issue by meetajhu** [babel/babel-sublime#402]
![image](https://user-images.githubusercontent.com/3233495/114693333-1ec63380-9d37-11eb-806c-d060bffd442b.png)

All the Braces {} used to get highlighted in red now its in white. With style={{object}} only the outer braces will be highlighted in red now both are white. It gets even confusing when using conditions inside template literals.

**Comment by Thom1729** [comment]
This is working as intended — the new scopes are in accordance with current best practices (and are the same scopes used in the core JavaScript syntax).

But if you want to color those braces differently, you can. Just edit your color scheme, targeting the `punctuation.definition.interpolation` and `punctuation.definition.interpolation` scopes. You can restore the prior coloration or set it to anything you like.

**Comment by meetajhu** [comment]
Need to have a better solution. These settings cannot be synced using [Sublime-settings-sync](https://github.com/mfuentesg/SyncSettings) when i am trying to setup Sublime Text on a new machine or setup. i may forget what i did in a year or two.

**Comment by Thom1729** [comment]
The most popular alternative is directly syncing your User directory via something like DropBox. I did that for a while and it worked well.

What I currently do is keep my custom settings, UI tweaks, and commands in a GitHub repository. This is probably the most robust solution, though it does take a few minutes to set up.
