### ISSUE TITLE
Syntax highlighting on multiline comments

### ISSUE THREAD

**Issue by titoBouzout** [babel/babel-sublime#403]
There's seems to be some issues with multiline comments

````javascript 
;(function () {
  'use strict'

  /* asd 
   */

  function test(){

  }
})(this)
````
shows as 

![030786d89b 1](https://user-images.githubusercontent.com/64156/115039414-d168d400-9ea6-11eb-8713-e2039271a685.png)

adding the semicolon to the end of use strict fix it 

![9795156bd6 1](https://user-images.githubusercontent.com/64156/115039464-da59a580-9ea6-11eb-9b82-034778032f41.png)

this file is also giving problems 

![8c2d13d923 1](https://user-images.githubusercontent.com/64156/115039792-27d61280-9ea7-11eb-87f0-db6c259f8e95.png)

also adding the semicolon to just before the comment fixes it, have the file to test it
[dom-to-image.txt](https://github.com/babel/babel-sublime/files/6325857/dom-to-image.txt)

**Comment by Thom1729** [comment]
Sorry I missed this a couple days ago. I can confirm this is broken. Neither the core syntax nor JS Custom with default settings has this problem, so it must be a bug in one of the JS Custom extensions that babel-sublime is using. I wasn't planning to mess with v10 any more, but this has to be fixed. Hopefully it shouldn't take an hour.

**Comment by Thom1729** [comment]
Minimal example:

```js
{
  ''/**/

  ''
  /**/
}
```

The second fails. It some kind of issue with the automatic semicolon insertion code for expression statements, but that should be identical to core, which doesn't have this problem. I almost wonder if it's some kind of bizarre parser corner case.

**Comment by Thom1729** [comment]
v10.0.5 is out with a fix. It turns out this was already fixed in core for ST4, so this won't be an issue in v11.

**Comment by titoBouzout** [comment]
awesome, thank you I can confirm its fixed
