### ISSUE TITLE
Lost syntax highlighting of symbols

### ISSUE THREAD

**Issue by Jimbly** [babel/babel-sublime#405]
Just restarted Sublime and got an update message from this package, and syntax highlighting of some punctuation/symbols has disappeared.  Rolling back to 8.6.3 fixes it.
![image](https://user-images.githubusercontent.com/774383/115282615-40406a00-a0ff-11eb-8e74-90b922799460.png)

Seems to be all `.`s and `${}` things inside of string literals.

**Comment by Thom1729** [comment]
This is working as intended. See the new #406 for more information.
