### ISSUE TITLE
Syntax highlighting changes in v10

### ISSUE THREAD

**Issue by Thom1729** [babel/babel-sublime#406]
Version 10 features a complete rewrite of the syntax definition. As a result, highlighting of some symbols has changed to conform to the core Sublime syntaxes, the scope naming guidelines, and community consensus.

| Symbol | Old scope | New Scope
| -- | -- | --
| Dot accessor | `keyword.operator.accessor` | `punctuation.accessor`
| Backtick in templates | `keyword.other.template` | `punctuation.definition.string`
| `${}` in templates | `keyword.other.substitution` | `punctuation.section.interpolation`

Depending on your color scheme, this will probably affect the color of those symbols. This is not a bug.

If you prefer the way it looked in previous versions, you can restore the old behavior by [customizing your color scheme](https://www.sublimetext.com/docs/3/color_schemes.html#customization). On Sublime Text 4, choose Preferences → Customize Color Scheme from the menubar or “UI: Customize Color Scheme” from the command palette, and add whatever rules you like. On Sublime Text 3, follow the directions in the link to create an override. For instance:

```json
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
    "variables":
    {
    },
    "globals":
    {
    },
    "rules":
    [
        {
            "scope": "source.js punctuation.accessor",
            "foreground": "var(pink)"
        },
        {
            "scope": "source.js punctuation.section.interpolation",
            "foreground": "var(pink)"
        }
    ]
}
```

(The above example is for Mariana; specifics will depend on your color scheme of choice.)

**Comment by Thom1729** [comment]
Apparently that command is new in ST4. Thanks for pointing that out.

**Comment by howdoimakethiswork** [comment]
CSS in styled-components parts is a bit inconsistent with this update. Can we revert to displaying styled-components as just strings (except for the ${} javascript parts), like before? Manually overriding the language seems very cumbersome, since the keywords appear to belong to many different scopes (maybe there is an appropriate single, overaching scope that can be overwritten?), thank you!

**Comment by Thom1729** [comment]
Can you post an example of a Styled Components template that's highlighted differently in v10 versus v8?

It's possible — even probable — that v10 *detects* templates that should be highlighted using Styled Components differently from the previous version. Hopefully, it does a better job, not a worse job. But the actual Styled Components highlighting should be identical between the versions, and if it's not, then that might be a bug.

I'd rather not eliminate Styled Components support since that's been part of babel-sublime for a while. If you specifically don't want Styled Components support, I'd recommend using JS Custom and disabling the option. But if there are defects in Styled Components highlighting that weren't in the previous version, then this is a regression that should be fixed.

FYI, rewritten Styled Components highlighting is on my to-do list for a future version of JS Custom, so any examples of poor highlighting would be helpful even if they aren't regressions.

**Comment by howdoimakethiswork** [comment]
Here are some photos, all from ST3. I experimented with different color schemes, two built in and one given by Babel. In the first two, the inconsistencies are visible (difference in colors before/after dashes). In the third, Marianna, the colors appear (almost?) correct (should no-repeat be the same color as flex-start?). Maybe this is a color scheme issue? Or does Marianna handle less scopes so the issues don't show up? I don't know how this works, but I hope it is useful!

Next (from Babel):
![colors3](https://user-images.githubusercontent.com/82541534/115344697-bda9c000-a17b-11eb-9291-2ed66c084291.png)

Celeste (built in): 
![colors2](https://user-images.githubusercontent.com/82541534/115344732-c69a9180-a17b-11eb-94fe-09cdff19aab1.png)

Marianna (built in):
![colors1](https://user-images.githubusercontent.com/82541534/115344950-15482b80-a17c-11eb-9e89-64f04043046a.png)

**Comment by Thom1729** [comment]
It definitely looks like there are bugs in the Styled Components syntax. But absent some indication to the contrary, I suspect that those are existing bugs, not regressions.

I haven't changed the Styled Components syntax definition at all, and it's probably in need of a rewrite itself. At the moment, I'm thinking of rewriting it for v11 (or, more specifically, rewriting it for JS Custom v3, which babel-sublime v11 will use).

**Comment by itsjohncs** [comment]
It does seem like there may be bugs that are falling out for first time. Here's a snippet I was staring at to try and learn the new colors but I couldn't figure out what was going on. I think the parser's just getting confused.

![Screen Shot 2021-04-22 at 1 43 40 PM](https://user-images.githubusercontent.com/367832/115782782-ecd55280-a370-11eb-9d73-76a8a06b945f.png)

**Comment by Thom1729** [comment]
I got a notification for a comment, but I don't see it here for some reason. Maybe it was deleted?

In case it's still a live issue, could you post a complete self-contained example snippet as text? I'm not familiar with that color scheme and nothing jumps out to me, and if there is a bug I'll need the full context to test it myself.

**Comment by itsjohncs** [comment]
I did delete it. There might be a bug but I thought of a consistent story for the highlighting (I think parameters to an arrow function and a non-arrow function are marked differently and then colored differently in my scheme for some reason, and the rest sorta fell into place from there). I wouldn't worry about it, I'll open up a bug report if I dig into it and find something I'm confident is misbehaving.

**Comment by Thom1729** [comment]
All function parameters should be scoped `variable.parameter.function`, so they *should* be highlighted identically (unless your color scheme is doing something strange).

There is a known issue where complex and/or multiline arrow function parameter lists won't be recognized (#340), but that shouldn't apply here. I tried the following example, and all of the parameter names are scoped `variable.parameter.function` and are highlighted the same in Mariana:

```js
class C {
    static createFromMove({previousMapState, mapState, cells, tokenIds, offset, layers}) {
        const operation = new UpdateForMove({});

        const updateOperation = (cells, getter, setter) => {
            
        }
    }
}
```

What color scheme are you using? It's possible that it's doing something strange. If not, then there might be something in the other parts of your file that is causing a problem.

**Comment by itsjohncs** [comment]
Looks like [my color scheme](https://gist.github.com/itsjohncs/bb5b71696f7987c2b5ec77b74b03b228) was doing something strange. The [Solarized package in the index](https://packagecontrol.io/packages/Solarized%20Color%20Scheme) doesn't have the same problem, so I'm all set now. Thank you for getting me to take another look.
