### ISSUE TITLE
Can't override function color for JSX files

### ISSUE THREAD

**Issue by boycce** [babel/babel-sublime#407]
I can't seem to override `source.js meta.function-call.js support.function.dom.js` in my `.tmTheme` for JSX files?

![image](https://user-images.githubusercontent.com/2629988/115636282-b93efc00-a361-11eb-99cd-17c95cca0714.png)

Here is my `material.tmTheme` file

``` xml
<dict>
  <key>name</key>
  <string>Function, Special Method, Block Level</string>
  <key>scope</key>
  <string>source meta.function-call.js support.function.dom.js</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#6699CC</string><!-- blue -->
  </dict>
</dict>
```

**Comment by Thom1729** [comment]
That would only happen if the two files are being displayed with different syntax definitions. I suspect that the JSX file is using a syntax definition other than babel-sublime. Can you confirm?

**Comment by boycce** [comment]
Hey @Thom1729, both are using `Babel -> JavaScript (Babel)`

**Comment by Thom1729** [comment]
If both files are using the same syntax definition, then they will apply identical scopes. Something odd must be going on.

**Comment by boycce** [comment]
Maybe a conflicting package somewhere, I'll need to do some more testing sometime.
