### ISSUE TITLE
declaring EventEmitter variable causes it to have a hardly visible color

### ISSUE THREAD

**Issue by mareksuscak** [babel/babel-sublime#41]
![this](https://cloud.githubusercontent.com/assets/613647/6225382/a66670de-b689-11e4-8a47-da9220a3bce7.PNG)

**Comment by zertosh** [comment]
Node constructs are scoped as [`support.class.node.js`] [1] and colored as [`#1224fe`] [2]. You can try a different theme that colors them differently - or run your own modified Monakai that doesn't color them (or colors them differently).

I use https://github.com/zenorocha/dracula-theme and it colors them like this:
![nbcte](https://cloud.githubusercontent.com/assets/830952/6231371/4e5cbf00-b694-11e4-8caa-a3a224a3b9cf.png)

[1]: https://github.com/babel/babel-sublime/blob/141cbcc/JavaScript%20(Babel).YAML-tmLanguage#L895
[2]: https://github.com/babel/babel-sublime/blob/141cbcc/Monokai%20Phoenix.YAML-tmTheme#L115
