### ISSUE TITLE
Sublime 4 Crashing

### ISSUE THREAD

**Issue by audetcameron** [babel/babel-sublime#416]
Just sharing that sublime 4 crashes when using this plugin.

**Comment by Thom1729** [comment]
Can you be more specific? It's not supposed to crash and this is very concerning, but this probably isn't enough information to go on.

Can you post the complete list of packages you have installed?

**Comment by audetcameron** [comment]
> Can you be more specific? It's not supposed to crash and this is very concerning, but this probably isn't enough information to go on.
> 
> Can you post the complete list of packages you have installed?

Sure thing,

`		"A File Icon",
		"ApacheConf",
		"BracketHighlighter",
		"Django",
		"DocBlockr",
		"Dockerfile Syntax Highlighting",
		"DotENV",
		"Laravel Blade Highlighter",
		"Liquid",
		"MarkdownPreview",
		"Material Theme",
		"nginx",
		"Package Control",
		"PackageResourceViewer",
		"PHP Companion",
		"Pretty JSON",
		"Python 3",
		"Sass",
		"SFTP",
		"SideBarEnhancements",
		"Slugify",
		"Tailwind CSS",
		"Tailwind CSS Autocomplete",
		"Twig",
		"View In Browser",
		"Vue Syntax Highlight",`

When installing babel, it would crash on "indexing" so it would stay open for about 20 seconds then just shut down. I'll replicate and get the error.  

However, it's worth saying that I just reinstalled to get the error and it appears to be working properly.
Maybe a uninstall and reinstall was all it needed?  Sorry I didn't give more info earlier.

**Comment by Thom1729** [comment]
If it crashed on installation once, but the crash isn't reproducible, then I suspect coincidence. Please post if it happens again and I'll reopen the issue.

**Comment by audetcameron** [comment]
> If it crashed on installation once, but the crash isn't reproducible, then I suspect coincidence. Please post if it happens again and I'll reopen the issue.

You bet,  I'm willing to suspect something else at this point, this is working very well and is a great addition.
Thanks again,
