### ISSUE TITLE
Possible highlighting error using a nested ternary

### ISSUE THREAD

**Issue by Mariede** [babel/babel-sublime#417]
Coding some functions for a back-end application sometime ago, I found this little weird behavior:

- Using a ternary to output a function (bad foward highlight):
![image](https://user-images.githubusercontent.com/4501798/139127029-125f70f6-1bcc-4725-9330-688a2281b9ab.png)

See that if remove the ternary, then the highlighting becomes fine afterwards:

- Using if / else if to output the same function (good foward highligh):
![image](https://user-images.githubusercontent.com/4501798/139127642-68c90398-6e81-4317-bb49-9ac40ccfa0d1.png)

Thank's for helping.

**Comment by Thom1729** [comment]
Fixed in v11.1.0.
