### ISSUE TITLE
ST4 Autocomplete does not consider state variables defined in a map

### ISSUE THREAD

**Issue by leevlad** [babel/babel-sublime#420]
When using Sublime Text 4:

When defining state variables in a map like so: `this.state = { testVar: "" }`, autocomplete does not offer `testVar` when typing out `this.state.testVar`. This used to work in Sublime Text 3.

For example, paste the snippet below into Sublime Text 4, set syntax to `JavaScript (Babel)`, then do what's noted in the comments:
```js
import React from "react"
import PropTypes from "prop-types"

class TestComponent extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      testVar: 0,
    }
  }

  testFunc = () => {
    // E.g. type "this.state.testV" on the line below, and press Ctrl+Space, see that it errors out with "No available completions"

    return 0
  }

  render () {
    return (
      <div>Same here. Put cursor at the end of "testV" here, press Ctrl+Space, and see "No available completions": {this.state.testV}</div>
    )
  }
}

TestComponent.propTypes = {
}

export default TestComponent
```

Please let me know if perhaps this is more of a question for Sublime Text team.

**Comment by Thom1729** [comment]
I suspect that this is not something that can reasonably be addressed in the syntax definition. Marginal improvement may be possible, but the built-in completion system is fairly dumb by nature. For better language-specific completions, I strongly recommend LSP. I use LSP-typescript myself.
