### ISSUE TITLE
Missing Babel option in syntax selector.

### ISSUE THREAD

**Issue by shot-codes** [babel/babel-sublime#421]
I've installed the babel package, expecting afterwards to find an entry for it under view > syntax > babel. However it doesn't pop up. I'm running on Mac OS, and have tried uninstalling and reinstalling to no avail.

**Comment by shot-codes** [comment]
ah, it seems it was under Javacript (babel). My mistake.

**Comment by abrambailey** [comment]
Actually this seems poorly documented. Thanks.
