### ISSUE TITLE
Highlighting of `filter` in `styled-components` seems to break—

### ISSUE THREAD

**Issue by aresnick** [babel/babel-sublime#422]
When I include a `filter` attribute in a styled component, babel-sublime doesn't seem to appropriately highlight it as a CSS attribute— seemingly flagging the parens as errors, and tagging filter as a reserved word, presumably confusing it with JavaScript's Array `filter` method.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/14084/155208447-b615bf9c-42f2-456b-9a29-08c0e7f2560b.png">

My only installed Sublime packages are Babel v11.1.1, Git v1.0.8, JsPrettier v1.50.1, and Package Control v3.4.1, all running on ST4 stable, Build 4126.

Any thoughts on addressing this would be appreciated!

**Comment by Thom1729** [comment]
This is (unsurprisingly) a bug in the Styled Components definition. It's actually confusing `filter` with the SVG `<filter>` tag — it thinks that `filter` is the start of a nested declaration. I wasn't aware that there were any CSS properties with the same name as an HTML/SVG tag. This should be an easy fix.

**Comment by aresnick** [comment]
Ah, got it!  Thank you for taking a look— FWIW, a quick comparison of the SVG tags [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) and CSS properties [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference) suggests that there are four tags which appear as CSS properties: [`filter`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter), [`mask`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask), [`font`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font) (deprecated), and [`cursor`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/cursor) (deprecated).

**Comment by Thom1729** [comment]
I can confirm that this is definitely fixed as of v11.2.0.
