### ISSUE TITLE
css Styled Component helper utility improperly highlighted

### ISSUE THREAD

**Issue by aresnick** [babel/babel-sublime#423]
I'm new to Styled Components, but I believe this usage of [the `css` helper](https://styled-components.com/docs/api#css) is appropriate, but incorrectly highlighted:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/14084/155861458-e5b14531-0d6b-417d-a99d-7275a2d67e4a.png">

Installed Sublime packages:
* Babel v11.1.1
* Git v1.0.8
* JsPrettier v1.50.1
* Package Control v3.4.1

…all running on ST4 stable, Build 4126.

**Comment by Thom1729** [comment]
I don't actually use Styled Components myself, but are you sure that's correct?

If `css` tagged templates can contain any arbitrary CSS substring, then it may be difficult or impossible to highlight them in every case.

**Comment by Thom1729** [comment]
Looking at this again, with reference to the linked documentation, I don't think it's correct to use the `css` tag for strings like `1em`.

Moreover, there are fundamental limitations here. Informally speaking, Sublime's engine can only track one language's structure at a time. When it sees `` css`1em` ``, it can't “carry forward” the outer CSS context into the template string; it merely sees the `css` tag and highlights the template as though it were a complete Style Components block. There are underlying mathematical limitations here; it's basically the same reason why Sublime can't keep track of both the structure of C code and the structure of C preprocessor conditionals, or both the structure of PHP code and the structure of the HTML that the PHP is embedded in.

So the only way to get `` css`1em` `` to highlight as you would want is for the Styled Components syntax to highlight arbitrary CSS values at top level. But the same text could often be either a selector or a value, so this wouldn't work in theory, and would probably work very badly in practice.

**Comment by aresnick** [comment]
Got it; thank you!
