### ISSUE TITLE
JS #myPrivateClassMethod() breaks syntax highlighting

### ISSUE THREAD

**Issue by ch3ll0v3k** [babel/babel-sublime#425]
sublime 3.1.1

![image](https://user-images.githubusercontent.com/7377121/195371501-1ca2b01d-259f-4877-9c23-3d35d3ae7fe4.png)

**Comment by Thom1729** [comment]
I tried a simplified version of this and could not reproduce. Most likely it was fixed at some point. If you still have this issue or a similar issue, please post the exact code that triggers the bug as text.

**Comment by ch3ll0v3k** [comment]
Sure
![image](https://github.com/babel/babel-sublime/assets/7377121/8a018150-4290-47c9-afff-9c4471c35513)

```javascript
class MyClass{

  #privateProp = null; // OK
  publicProp = null; // OK

  constructor(){

  }

  publicMethod(){ // OK

  }

  // this (#) private method break all syntax highlighting after it self
  #privateMethod(){

  }

  wrongSytaxtHighlighting(){
    const a = 12;
  }

  someMethod(){
    const a = 12;
  }

}
´´´

**Comment by ch3ll0v3k** [comment]
![image](https://github.com/babel/babel-sublime/assets/7377121/fdffb03a-d610-401d-ac2b-2844325aaaef)
![image](https://github.com/babel/babel-sublime/assets/7377121/8d02ba19-24cf-4846-bbf9-00af4f7234b7)

**Comment by Thom1729** [comment]
Ah, I see the issue. It looks like you're running Sublime Text 3, which won't run babel-sublime v11 or later. ST4 added powerful new syntax highlighting features that are especially relevant to the JavaScript family, and current versions of babel-sublime rely deeply on these features and provide much better highlighting.

You can fix the issue by upgrading to current versions of Sublime and babel-sublime. I acknowledge that this may not be a very helpful answer.

I'll do some thinking about the status of the v10 branch. Currently, it's not maintained and I have no plans to update it to add new features or fix bugs. If there is substantial interest in contributing patches for v10, I could set up a dedicated branch for people to work on.

**Comment by ch3ll0v3k** [comment]
ahh, oke. thank you for this info!
sorr ...

**Comment by ch3ll0v3k** [comment]
Awesome ))) it does work in ST4. thx
