### ISSUE TITLE
Interface in extends class is not well Colored

### ISSUE THREAD

**Issue by Wei-1** [babel/babel-sublime#429]
<img width="1014" alt="Screenshot 2023-05-28 at 11 43 28" src="https://github.com/babel/babel-sublime/assets/10698262/113fca2b-3da6-42ed-a2d9-eca1694c99dd">

As can be seen in the image, when we define an interface and use it in the extends class, the color is weird and the interface itself has no color applied to it.

**Comment by Thom1729** [comment]
My guess is that the code before the screenshot is the problem. Please post a complete sample in text form. It's fine to excerpt only a piece, but copy-paste that piece into its own tab first to make sure that the excerpt exhibits the problem by itself.

**Comment by Thom1729** [comment]
Also, that kind of looks like TypeScript. This package should highlight Flow types, but it does not support TypeScript. Can you clarify what type system you're using?

**Comment by Wei-1** [comment]
<img width="1017" alt="Screenshot 2023-05-28 at 16 28 09" src="https://github.com/babel/babel-sublime/assets/10698262/52240e0c-dab0-4dfe-8a6a-8e3722b84859">

You are right, the code structure is actually copied from a typescript example. Thanks for answering.

**Comment by Thom1729** [comment]
For TypeScript with JSX, Sublime's built-in TSX syntax is best. Alternatively, you can try [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom), which you can configure to support TS, JSX, and various other customizations. This package is actually built directly from JS Custom with a fixed set of configuration options.
