### ISSUE TITLE
spread "this" isn't highlighted

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel-sublime#44]
`this` is highlighted everywhere except for here: (from the readme)

![screen shot 2015-02-18 at 11 14 30 pm](https://cloud.githubusercontent.com/assets/952783/6262987/20c43f92-b7c4-11e4-8b6b-c979bf42c5c5.png)

**Comment by zertosh** [comment]
Fixing upstream, then I'll merge it back down

**Comment by zertosh** [comment]
Fix by https://github.com/babel/babel-sublime/pull/45 and published as https://github.com/babel/babel-sublime/releases/tag/v4.0.1. And the screenshots were updated in https://github.com/babel/babel-sublime/pull/46.

@thejameskyle The new version should get picked up by Package Control within an hour.
