### ISSUE TITLE
Is atom.io version planned?

### ISSUE THREAD

**Issue by steida** [babel/babel-sublime#47]

**Comment by sebmck** [comment]
See previous discussion [here](https://github.com/babel/babel-sublime/pull/1#issuecomment-70346280).

**Comment by Dashed** [comment]
Looks like this wouldn't be a trivial port to Atom. https://github.com/babel/babel-sublime/pull/1#issuecomment-75414992

If someone really wanted to, they'd have to port babel-sublime to atom from scratch or something.
