### ISSUE TITLE
Scoping JSX snippets to HTML?

### ISSUE THREAD

**Issue by joemaller** [babel/babel-sublime#48]
Just started thinking about this, but I wanted to get a conversation going. 

It should be possible to scope React's JSX blocks to HTML, most likely named `text.html.jsx`. If that worked, wouldn't we suddenly gain access to all of the HTML tools available to Sublime? At very least, this should enable Sublime's build-in Expand Selection to Tag. Formatters/Tidy would be welcome. 

I haven't looked into what they're doing, but [Allan Hortle's JSX package](https://github.com/allanhortle/JSX) does allow Expand Selection to Tag to function correctly.

**Comment by zertosh** [comment]
Interesting. I wonder if it breaks eslint. It shouldn't break JSXHint because there's a transpile step there. But I think eslint only lints certain scopes. I could be mistaken. I'll investigate. Good call!

**Comment by zertosh** [comment]
Hey @joemaller, I fixed the "Expand Selection to Tag" bug in https://github.com/babel/babel-sublime/pull/70. I also looked into scoping JSX as `text.html.*` and it didn't really work with other HTML tools as you suggested. If you have any luck with this, PRs are welcome or open another issue.
