### ISSUE TITLE
multiline arguments/parameters are not formatted in class functions

### ISSUE THREAD

**Issue by ms88privat** [babel/babel-sublime#50]
example:

constructor({name = 'abc', data = []}) {
  // name and data are formatted
}

constructor({
 name = 'abc',
 data = []
}) {
// name and data NOT formatted
}

anyway, thanks for this plugin :)!

**Comment by zertosh** [comment]
Hey @ms88privat, glad you like it. Unfortunately this is a known Sublime limitation. The regex parsing can't match across lines :disappointed:

**Comment by zertosh** [comment]
sorry, closed it too soon. A _hack_ you can use to get around this, is to use a theme that colors arguments/params the same as variable assignments. For example,

![hywss](https://cloud.githubusercontent.com/assets/830952/6362991/ddf46966-bc60-11e4-9021-009ea15b8cd0.png)
 ^ this is [dracula](https://github.com/zenorocha/dracula-theme), my personal theme of choice - which much like whatever you're using, colors params/args and variables differently.

![icgxq](https://cloud.githubusercontent.com/assets/830952/6362996/f937c772-bc60-11e4-89ff-3a1bbb13acd1.png)
^ this is [predrawn](https://github.com/jamiewilson/predawn), it colors both the same, so it masks the problem.

Hope this helps!
