### ISSUE TITLE
Support ES6 class static properties

### ISSUE THREAD

**Issue by tomatau** [babel/babel-sublime#52]
You supply nice highlighting on 

```
get methodName(){
```

Would be nice if you also supported

```
static methodName(){
```

And if it's not too much trouble: async (supported in objects but not classes) and memo (experimental but very powerful) http://babeljs.io/docs/usage/transformers/#es7-experimental-

Generator `*`s, could be more clear too as they currently blend in with the `function` word

**Comment by zertosh** [comment]
Fixed in https://github.com/babel/babel-sublime/pull/53. Package Control should pick up the update within an hour.

![fixed async generators](https://cloud.githubusercontent.com/assets/830952/6428853/4cd87cf2-bf7f-11e4-8bbc-af240b9e56f1.png)

**Comment by tomatau** [comment]
nice thanks :dancer:
