### ISSUE TITLE
es6 functions not showing up in goto symbol in project

### ISSUE THREAD

**Issue by vanntastic** [babel/babel-sublime#57]
Just noticed that es6 functions aren't showing up in the goto symbol in project command palette - they show up just fine in the goto symbol (in the current file) palette. Is there some symbol re-indexing that I need to do? Or is there something else that needs to happen?

**Comment by zertosh** [comment]
Thanks for the report! Fixed in https://github.com/babel/babel-sublime/pull/58. The update should get picked up by Package Control in about ~30min.

**Comment by vanntastic** [comment]
just updated the package, works great! you guys are awesome! thanks!
