### ISSUE TITLE
Does not highlight dot before "static" methods

### ISSUE THREAD

**Issue by roadhump** [babel/babel-sublime#68]
Dot inside  `Cursor.from` can't be highlighted

![screenshot 2015-03-14 21 57 09](https://cloud.githubusercontent.com/assets/234692/6653098/4c505e3c-ca95-11e4-883f-a4e1aad73768.png)

**Comment by zertosh** [comment]
Fixed in https://github.com/babel/babel-sublime/pull/69. Package Control should pick up the update in ~40min.
