### ISSUE TITLE
Slashes break template string highlighting

### ISSUE THREAD

**Issue by klaemo** [babel/babel-sublime#72]
Hey,
while template strings in general are highlighted correctly, it seems like when they contain slashes everything following these is treated as a comment.

![bildschirmfoto 2015-03-19 um 11 22 51](https://cloud.githubusercontent.com/assets/778624/6728547/d809cce0-ce2a-11e4-8a8e-5035b6a085aa.png)

Thank you!

**Comment by sebmck** [comment]
Are you sure you're using `babel-sublime`? Template literals are escaped and syntax highighted correctly for me.

![screen shot 2015-03-19 at 9 29 48 pm](https://cloud.githubusercontent.com/assets/853712/6728630/3203706c-ce7f-11e4-8619-ee1741c31369.png)

**Comment by klaemo** [comment]
haha sorry! my entire project uses babel-sublime except that one file for some reason! :laughing:
