### ISSUE TITLE
syntax highlighting for fat arrow functions with one parameter and no parentheses

### ISSUE THREAD

**Issue by ryanberckmans** [babel/babel-sublime#73]
When a fat arrow function has one parameter it may legally omit parentheses. In this case syntax highlighting is disabled for the fat arrow function:

![image](https://cloud.githubusercontent.com/assets/299324/6766047/56c93608-cfcd-11e4-8a52-fc622214d64a.png)

**Comment by roman01la** [comment]
+1

**Comment by zertosh** [comment]
Sorry, I've been waiting this to merge upstream, but I'll just merge it here and then later revert when I sync back down the changes.

**Comment by zertosh** [comment]
Fixed in https://github.com/babel/babel-sublime/pull/74. Published as v4.0.14. Package Control should pick up the update in like an hour.
