### ISSUE TITLE
Escaped characters in interpolated strings ("quasis")

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#78]
It looks like these don’t currently have a scope I can target.

**Comment by zertosh** [comment]
Just pushed the fix as v4.0.15. Package Control should pick up the update within the next hour.

**Comment by bathos** [comment]
Awesome. I just added two more issues. It's a fantastic package, I'm having great fun trying to write my first theme!

**Comment by zertosh** [comment]
Thanks! That's great, let me know when you have it ready so I can check it out :smile:
