### ISSUE TITLE
Regexp delimiters

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#81]
Given a regexp:

    /hello/

The opening slash only has the scope `string.regexp.js` while the closing slash has the scope `string.regexp.js punctuation.definition.string.end.js`. It seems like both should be targettable.

**Comment by zertosh** [comment]
Hmm this one is complicated. I'm going to need some time.

**Comment by zertosh** [comment]
Fixed by https://github.com/babel/babel-sublime/pull/90. It _works_ but the regexp matching is really weird, so if issues crop up, I might have to revert it and find another fix.
