### ISSUE TITLE
Odd scope encountered -- correct behavior?

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#85]
I'm not sure what's going on here with the maxLogs identifier (yellow):

![image](https://cloud.githubusercontent.com/assets/6257356/7071646/8bb0fc2a-deb4-11e4-9c00-7119f791b18a.png)

The scope on maxLogs is:

`(...) constant.other.object.key.js string.unquoted.label.js`

If I enclose it in parentheses, the scope changes to `variable.other.readwrite`, which is how it gets identified everywhere else it appears. To replicate this, the pattern seems to be:

In any ternary, if the expression between ? and : is not enclosed in parentheses, and the last value is an identifier, and the total expression is not just a single identifier, then that last value will get this odd scope.

**Comment by zertosh** [comment]
The syntax matching has no sense of order of operation - It's all dumb regexs. Operators like arithmetic, `?` or `:`, get [matched individually](https://github.com/babel/babel-sublime/blob/0941f77a977f047d1ff5b36d489e2108418f849f/JavaScript%20(Babel).YAML-tmLanguage#L762-L839). Sublime's regex can't match across lines. It's a terrible limitation - just look through the issues. To compensate, there are a lot of _heuristics_ to accommodate for the most common use case. What you're seeing is [this](https://github.com/babel/babel-sublime/blob/0941f77a977f047d1ff5b36d489e2108418f849f/JavaScript%20(Babel).YAML-tmLanguage#L855-L859). Notice that to match an object key there is no concept of being in an object or anything. It's all just trickery in the other in which the regexs [run](https://github.com/babel/babel-sublime/blob/0941f77a977f047d1ff5b36d489e2108418f849f/JavaScript%20(Babel).YAML-tmLanguage#L14-L23).

I'm afraid this is a "Can't fix".

**Comment by bathos** [comment]
Understood! Honestly I'm amazed by the regex wizardry tmTheme requires and it's not surprising that it has limits like this. Actually it left me wondering why the standard for this stuff is based on pattern matching instead of actual tokenization, which seems like it must be more efficient, but a standard is a standard.

**Comment by zertosh** [comment]
Sublime just released (this week) a [new syntax format](http://www.sublimetext.com/docs/3/syntax.html). I haven't had a chance to dig into it yet, but it looks promising.
