### ISSUE TITLE
yield* asterisk not recognized correctly

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#88]
In `yield* iterable` (or `yield * iterable` or `yield *iterable`, all valid forms), the asterisk is being mistaken for the multiplication operator.

**Comment by sebmck** [comment]
Do you have full code examples?

**Comment by bathos** [comment]
sure, but it's been true in every variation I've tried, so I figured the rule was just missing?

    function* foo() {
        yield * [1, 2];
    }

**Comment by sebmck** [comment]
Oh shit whoops, I thought this was an issue on the main `babel` repo... sorry!

**Comment by bathos** [comment]
oh haha -- no, Babel always works perfectly :>

**Comment by zertosh** [comment]
@sebmck lol

**Comment by zertosh** [comment]
Fixed by https://github.com/babel/babel-sublime/pull/89
