### ISSUE TITLE
Missing support identifiers

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#92]
`support.class.builtin.js` is missing WeakSet and Symbol (I think Symbol is not a class, technically, but I'm not sure where else it should go).

`support.type.object.node` is missing require (could be grouped with support functions I suppose, but it does also have properties)

`support.module.node.js` is missing querystring

`support.class.builtin.js` is missing all of the typed arrays plus ArrayBuffer and DataView -- Babel doesn't (can't, at least meaningifully, I imagine) implement typed arrays though, so this may be intentional. On the other hand, Proxy is there and not in Babel either. I think this regex should cover the typed arrays plus Array collectively:

`(Float(32|64)|(Ui|I)nt(8|16|32)|Uint8Clamped)?Array`

Also absent: JSON, Reflect, and Intl.

And: setTimeout, clearTimeout, setInterval, clearInterval, setImmediate and clearImmediate (didn't even know that last one existed till just now!).

**Comment by zertosh** [comment]
A few months later, but done!

**Comment by zertosh** [comment]
https://github.com/babel/babel-sublime/pull/184
