### ISSUE TITLE
Feature request: decorator support

### ISSUE THREAD

**Issue by axefrog** [babel/babel-sublime#93]
@decorators are currently missing syntax highlighting support

Further info can be found here: https://github.com/wycats/javascript-decorators
This spec seems to be catching on and has already been integrated into Aurelia. Would love to see syntax highlighting in sublime.

**Comment by zertosh** [comment]
Published as v5.0.3. The update should get picked up by Package Control in ~10min.

**Comment by axefrog** [comment]
Thanks, nice work!
