### ISSUE TITLE
Hyphenated custom elements syntax-highlighted incorrectly

### ISSUE THREAD

**Issue by axefrog** [babel/babel-sublime#94]
Hyphenated elements are are not syntax-highlighted correctly. The first part of the element comes out in one colour and everything after the first hyphen comes out in another colour.

**Comment by zertosh** [comment]
They work for me. Are you sure you've got "JavaScript (Babel)" as the syntax? Can you post a screenshot?

**Comment by axefrog** [comment]
Sorry I assumed that HTML was supported as well, custom elements being enabled as part of the Web Components spec, but realised using HTML. I just realised that this is nothing to do with Babel though. In any case, if you want your included color schemes to support custom elements, that'd be nice.

**Comment by zertosh** [comment]
I'm confused. They _color_ just fine. No?

![zuceu](https://cloud.githubusercontent.com/assets/830952/7109299/b4fe3e10-e168-11e4-9c8b-87236b4d478f.png)

**Comment by axefrog** [comment]
That's a JavaScript file utilizing JSX syntax.

I'm talking about the syntax highlighting in a literal HTML file.

**Comment by Dashed** [comment]
@axefrog babel-sublime doesn't provide highlighting for HTML files.
