### ISSUE TITLE
Coffeescript?

### ISSUE THREAD

**Issue by mstrandgren** [babel/babel-sublime#98]
sublime-react syntax highlighting supported cjsx, i.e. coffeescript with jsx. Any plans for babel to do the same? I can't get the deprecated sublime-react syntax highlighting to work anymore.

**Comment by zertosh** [comment]
Sorry, no plans whatsoever.

Side note: I feel that this something that the coffeescript community should take over. The sublime-react repo is still there, anyone can fork it and re-publish just the coffeescript parts.
