### ISSUE TITLE
Syntax highlighting of "yield" inside other words

### ISSUE THREAD

**Issue by jamwaffles** [babel/babel-sublime#99]
As far as I know this is only for `yield`. Test case:

```javascript
let savedGroup = yieldgroup.save()
```

![image](https://cloud.githubusercontent.com/assets/800791/7200230/d174d684-e4f2-11e4-873d-41be5636150b.png)

`yield` shouldn't be purple as it's part of another word. As far as I know this doesn't happen with any other keywords.

**Comment by zertosh** [comment]
I broke that in https://github.com/babel/babel-sublime/pull/89 :(

**Comment by zertosh** [comment]
Published as v5.0.4. The update should get picked up by Package Control in about an hour.
